### ISSUE TITLE
cannot import name properties

### ISSUE THREAD

**Issue by ldiqual** [Kozea/WeasyPrint#10]
I'm trying to use WeasyPrint in my virtualenv. I followed the Homebrew steps [from the installation instructions](http://weasyprint.org/install/), but I get an error while trying to generate a simple PDF:

```
Traceback (most recent call last):
  File "/Users/ldiqual/Documents/Projects/app-django/app_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/ldiqual/Documents/Projects/app-django/app_env/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/ldiqual/Documents/Projects/app-django/backend/views/admin/actions.py", line 87, in handle_admin_actions
    return generate_contract(request, vendor)
  File "/Users/ldiqual/Documents/Projects/app-django/backend/utils/contract_generator.py", line 28, in generate_contract
    pdf = render_to_pdf(request, "backend/steps/contract/contract.html", context_dict)
  File "/Users/ldiqual/Documents/Projects/app-django/backend/utils/common.py", line 61, in render_to_pdf
    weasyprint.HTML(string=html).write_pdf(target=result)
  File "/Users/ldiqual/Documents/Projects/app-django/app_env/lib/python2.7/site-packages/weasyprint/__init__.py", line 98, in __init__
    from .html import find_base_url
  File "/Users/ldiqual/Documents/Projects/app-django/app_env/lib/python2.7/site-packages/weasyprint/html.py", line 22, in <module>
    from .formatting_structure import boxes
  File "/Users/ldiqual/Documents/Projects/app-django/app_env/lib/python2.7/site-packages/weasyprint/formatting_structure/boxes.py", line 63, in <module>
    from ..css.computed_values import ZERO_PIXELS
  File "/Users/ldiqual/Documents/Projects/app-django/app_env/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 51, in <module>
    from . import properties
ImportError: cannot import name properties
```

The error comes from `weasyprint/css/__init__.py`:

```
import tinycss
import cssselect
import lxml.etree

from . import properties # <=== This line
from . import computed_values
from .validation import preprocess_declarations
```

**Comment by marianobianchi** [comment]
I know it is closed but after one year i run into the same problem again. I installed pycparser and everything seems to work fine again.

**Comment by SimonSapin** [comment]
@marianobianchi Was pycparser not already installed as a (recursive) dependency?

**Comment by marianobianchi** [comment]
I was having another problem and was installing all packages with "--no-deps" option in pip. That made me run into this problem again and found this old bug report. I thought it was a good idea to comment the solution that worked for me this time, but wasn't sure if this was the correct place to do it.

I have just installed using "pip install weasyprint" and it installed all the dependencies fine. So i think it's nothing to worry about...

**Comment by SimonSapin** [comment]
Although the error message could definitely be better, I’m not too surprised that installing without dependencies doesn’t work.
