### ISSUE TITLE
Error installing WeasyPrint in python 3.8.0 32 with windows x32

### ISSUE THREAD

**Issue by antoinefradin** [Kozea/WeasyPrint#1008]
Hi, 
I followed the instructions for the correct installation of / ** WeasyPrint ** / on Windows and I get the error (Step 3 ):

-----------------------------------------------------------------------------------------------------
```
C:\Users\Kandy-2>py -m pip install WeasyPrint
Collecting WeasyPrint
  Using cached https://files.pythonhosted.org/packages/ca/1a/1925cf1e39e5526d9c686a31f798523e06ea45f20c958a429317a1110ee4/WeasyPrint-50-py3-none-any.whl
Collecting tinycss2>=1.0.0
  Using cached https://files.pythonhosted.org/packages/94/2c/4e501f9c351343c8ba10d70b5a7ca97cdab2690af043a6e52ada65b85b6b/tinycss2-1.0.2-py3-none-any.whl
Collecting Pyphen>=0.8
  Using cached https://files.pythonhosted.org/packages/15/82/08a3629dce8d1f3d91db843bb36d4d7db6b6269d5067259613a0d5c8a9db/Pyphen-0.9.5-py2.py3-none-any.whl
Collecting cffi>=0.6
  Using cached https://files.pythonhosted.org/packages/f8/26/5da5cafef77586e4f7a136b8a24bc81fd2cf1ecb71b6ec3998ffe78ea2cf/cffi-1.13.2-cp38-cp38-win32.whl
Requirement already satisfied: setuptools>=39.2.0 in c:\users\kandy-2\appdata\local\programs\python\python38-32\lib\site-packages (from WeasyPrint) (42.0.2)
Collecting cssselect2>=0.1
  Using cached https://files.pythonhosted.org/packages/c4/a1/1a37602bbcfa2f7c079758f31555776a00a947e43457a3e0110b2165c7d9/cssselect2-0.2.2-py2.py3-none-any.whl
Collecting CairoSVG>=2.4.0
  Using cached https://files.pythonhosted.org/packages/8e/3a/762f9272c20db092f4d537aaf364dd0770ecf8f7101b58c4e933e99ee2f6/CairoSVG-2.4.2-py3-none-any.whl
Collecting cairocffi>=0.9.0
  Using cached https://files.pythonhosted.org/packages/f7/99/b3a2c6393563ccbe081ffcceb359ec27a6227792c5169604c1bd8128031a/cairocffi-1.1.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Kandy-2\AppData\Local\Programs\Python\Python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Kandy-2\\AppData\\Local\\Temp\\pip-install-zfxh8hcm\\cairocffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Kandy-2\\AppData\\Local\\Temp\\pip-install-zfxh8hcm\\cairocffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Kandy-2\AppData\Local\Temp\pip-install-zfxh8hcm\cairocffi\pip-egg-info'
         cwd: C:\Users\Kandy-2\AppData\Local\Temp\pip-install-zfxh8hcm\cairocffi\
    Complete output (46 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: 'C:\Users\Kandy-2\AppData\Local\Programs\Python\Python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Kandy-2\\AppData\\Local\\Temp\\pip-wheel-hufdnh6t\\pycparser\\setup.py'"'"'; __file__='"'"'C:\\Users\\Kandy-2\\AppData\\Local\\Temp\\pip-wheel-hufdnh6t\\pycparser\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Kandy-2\AppData\Local\Temp\pip-wheel-s5rxkihs'
           cwd: C:\Users\Kandy-2\AppData\Local\Temp\pip-wheel-hufdnh6t\pycparser\
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for pycparser
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "C:\Users\Kandy-2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "C:\Users\Kandy-2\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Users\\Kandy-2\\AppData\\Local\\Programs\\Python\\Python38-32\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Kandy-2\\AppData\\Local\\Temp\\tmp21lvr52j', '--quiet', 'pycparser']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Kandy-2\AppData\Local\Temp\pip-install-zfxh8hcm\cairocffi\setup.py", line 10, in <module>
        setup(
      File "C:\Users\Kandy-2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "C:\Users\Kandy-2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\Users\Kandy-2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 718, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:\Users\Kandy-2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "C:\Users\Kandy-2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "C:\Users\Kandy-2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "C:\Users\Kandy-2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "C:\Users\Kandy-2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['C:\\Users\\Kandy-2\\AppData\\Local\\Programs\\Python\\Python38-32\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Kandy-2\\AppData\\Local\\Temp\\tmp21lvr52j', '--quiet', 'pycparser']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
-----------------------------------------------------------------------------------------------------

Please give me a help, I will be grateful in advance.

Greetings.

**Comment by liZe** [comment]
It's probably because of Kozea/cairocffi#140, you can launch `py -m pip install wheel` and try to install WeasyPrint again.

**Comment by antoinefradin** [comment]
Thanks a lot!
