### ISSUE TITLE
"TypeError: Type str doesn't support the buffer API" on import

### ISSUE THREAD

**Issue by mtkennerly** [Kozea/WeasyPrint#105]
I looked through the current issues and didn't see this. Sorry if I missed something.

I'm on Windows 7 with Python 3.3.2 (also tried 3.2) using WeasyPrint 0.19.2. Installing with Pip didn't work because of some error with trying to use one of the cp### encodings, so I downloaded it from PyPi and ran `setup.py install`. I installed the dependencies using Pip and the download links from http://weasyprint.org/docs/install/#windows .  I'm trying to run the following (test1.py) in IDLE:

    import weasyprint

    myHTML = """
    <p>Hello!</p>
    """

    wpHTML = weasyprint.HTML(string=myHTML)
    print("Step 1 worked")
    wpHTML.write_pdf("test1.pdf")
    print("Step 2 worked")

It produces the following:

    Traceback (most recent call last):
      File "C:\Users\Matthew\Desktop\weasyprint\test1.py", line 1, in <module>
        import weasyprint
      File "C:\Python33\lib\site-packages\weasyprint-0.19.2-py3.3.egg\weasyprint\__init__.py", line 305, in <module>
        from .html import find_base_url, HTML5_UA_STYLESHEET
      File "C:\Python33\lib\site-packages\weasyprint-0.19.2-py3.3.egg\weasyprint\html.py", line 34, in <module>
        filename=os.path.join(os.path.dirname(__file__), 'css', 'html5_ua.css'))
      File "C:\Python33\lib\site-packages\weasyprint-0.19.2-py3.3.egg\weasyprint\__init__.py", line 219, in __init__
        check_css_mime_type=_check_mime_type,)
      File "C:\Python33\lib\site-packages\weasyprint-0.19.2-py3.3.egg\weasyprint\__init__.py", line 268, in _select_source
        base_url = path2url(filename)
      File "C:\Python33\lib\site-packages\weasyprint-0.19.2-py3.3.egg\weasyprint\urls.py", line 81, in path2url
        path = pathname2url(path)
      File "C:\Python33\lib\nturl2path.py", line 46, in pathname2url
        if not ':' in p:
    TypeError: Type str doesn't support the buffer API

In urls.py, adding `print(path)` before `path = pathname2url(path)` gives:

    b'C:\\Python33\\lib\\site-packages\\weasyprint-0.19.2-py3.3.egg\\weasyprint\\css\\html5_ua.css'

In urls.py, I tried changing line 81 to `path = pathname2url(path.decode())` and adding `print(path)` immediately afterward, which gives:

    ///C:/Python33/lib/site-packages/weasyprint-0.19.2-py3.3.egg/weasyprint/css/html5_ua.css

With this change, test1.py gets as far as printing `Step 1 worked`, but then pythonw.exe crashes (no traceback):

    Files that help describe the problem:
    C:\Users\Matthew\AppData\Local\Temp\WERA710.tmp.WERInternalMetadata.xml
    C:\Users\Matthew\AppData\Local\Temp\WERBE59.tmp.appcompat.txt
    C:\Users\Matthew\AppData\Local\Temp\WERBEA8.tmp.mdmp

Here's a *.zip file with these files: https://docs.google.com/file/d/0BxUBm3Nh0bh5aHhSV0hnOG1seTg/edit

Any ideas on how to fix this?

**Comment by liZe** [comment]
@mtkennerly is this problem fixed for you?
