### ISSUE TITLE
Unable to import or use WeasyPrint after installations

### ISSUE THREAD

**Issue by BenyKammoun** [Kozea/WeasyPrint#1127]
Hi, i followed carefully the step by step installation guide; my python version is 64-bit and i have installed the 64-bit GTK+ version via pacman (MSYS2). Then, I manually added the appropriate folder (C:\msys64\mingw64\bin in my case) into the Path and still getting the following error message:

Traceback (most recent call last):
  File "C:/Users/benyk/PycharmProjects/HtmlToPdf/convert.py", line 1, in <module>
    from weasyprint import HTML
  File "C:\Users\benyk\AppData\Local\Programs\Python\Python38\lib\site-packages\weasyprint\__init__.py", line 440, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "C:\Users\benyk\AppData\Local\Programs\Python\Python38\lib\site-packages\weasyprint\css\__init__.py", line 30, in <module>
    from . import computed_values, media_queries
  File "C:\Users\benyk\AppData\Local\Programs\Python\Python38\lib\site-packages\weasyprint\css\computed_values.py", line 18, in <module>
    from .. import text
  File "C:\Users\benyk\AppData\Local\Programs\Python\Python38\lib\site-packages\weasyprint\text.py", line 14, in <module>
    import cairocffi as cairo
  File "C:\Users\benyk\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\benyk\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e 

I tried to run the WHERE command and the system didn't find the libcairo-2.dll library. after manually adding it with SET command it worked but i cannot figure out how to fix it permanently especially if i want to use it as a python library.

Thanks for your help

**Comment by BenyKammoun** [comment]
After pyCharm restart it works.
