### ISSUE TITLE
Traceback that didn't occur previously

### ISSUE THREAD

**Issue by pepa65** [Kozea/WeasyPrint#1167]
After more than 4 years of running `weasyprint -v file.html file.pdf` I now get this traceback (and the pdf is no longer generated...):
```
INFO: Step 6 - Drawing
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 11, in <module>
    load_entry_point('WeasyPrint==51', 'console_scripts', 'weasyprint')()
  File "/usr/local/lib/python3.6/dist-packages/WeasyPrint-51-py3.6.egg/weasyprint/__main__.py", line 214, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/WeasyPrint-51-py3.6.egg/weasyprint/__init__.py", line 227, in write_pdf
    .write_pdf(target, zoom, attachments))
  File "/usr/local/lib/python3.6/dist-packages/WeasyPrint-51-py3.6.egg/weasyprint/document.py", line 645, in write_pdf
    self.add_hyperlinks(links, anchors, context, scale)
  File "/usr/local/lib/python3.6/dist-packages/WeasyPrint-51-py3.6.egg/weasyprint/document.py", line 579, in add_hyperlinks
    context.tag_begin(cairo.TAG_LINK, attributes)
AttributeError: 'Context' object has no attribute 'tag_begin'
```
Until commit 6454e5ee5b0ef64a97fdd208eff8ddd50ce2db29 all is fine, after that it no longer works (for me).

**Comment by liZe** [comment]
Hello @pepa65!

This error probably means that your version of CairoCFFI is outdated: you need at least version 0.9.0.

**Comment by pepa65** [comment]
Ubuntu 18.04's python3-cairocffi is 0.8.0-0ubuntu2... What is the best way to install this outside of the repo??

**Comment by liZe** [comment]
You can safely install the package from 20.04 manually on your 18.04 Ubuntu.

If you want to keep everything clean, you should create a virtual environment, as it’s explained [at the top of the Installation page](https://weasyprint.readthedocs.io/en/latest/install.html#id5). That’s the best way to keep Python dependencies independent from your system packages.

**Comment by pepa65** [comment]
Did that and now it all works again - thanks!
