### ISSUE TITLE
AttributeError: 'BlockBox' object has no attribute 'index'

### ISSUE THREAD

**Issue by vpoulailleau** [Kozea/WeasyPrint#1168]
First, thanks for WeasyPrint, it's really great!

I encountered a crash with:

```bash
python -m weasyprint "https://fr.wikipedia.org/wiki/Python_(langage)" --stylesheet https://vpoulailleau.github.io/formation/css/main.css python.pdf
```

Python is Python 3.8.4, WeasyPrint is WeasyPrint 51.

Here is the traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/__main__.py", line 216, in <module>
    main()
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/__main__.py", line 212, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/__init__.py", line 208, in write_pdf
    return self.render(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/__init__.py", line 166, in render
    return Document._render(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/document.py", line 393, in _render
    [Page(page_box, enable_hinting) for page_box in page_boxes],
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/document.py", line 393, in <listcomp>
    [Page(page_box, enable_hinting) for page_box in page_boxes],
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/__init__.py", line 126, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/pages.py", line 804, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/pages.py", line 741, in remake_page
    page, resume_at, next_page = make_page(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/pages.py", line 551, in make_page
    root_box, resume_at, next_page, _, _ = block_level_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 61, in block_level_layout
    return block_level_layout_switch(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 75, in block_level_layout_switch
    return block_box_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 128, in block_box_layout
    block_container_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 504, in block_container_layout
    collapsing_through) = block_level_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 61, in block_level_layout
    return block_level_layout_switch(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 75, in block_level_layout_switch
    return block_box_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 128, in block_box_layout
    block_container_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 504, in block_container_layout
    collapsing_through) = block_level_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 61, in block_level_layout
    return block_level_layout_switch(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 75, in block_level_layout_switch
    return block_box_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 128, in block_box_layout
    block_container_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 504, in block_container_layout
    collapsing_through) = block_level_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 61, in block_level_layout
    return block_level_layout_switch(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 75, in block_level_layout_switch
    return block_box_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 128, in block_box_layout
    block_container_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 504, in block_container_layout
    collapsing_through) = block_level_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 61, in block_level_layout
    return block_level_layout_switch(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 75, in block_level_layout_switch
    return block_box_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 128, in block_box_layout
    block_container_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 504, in block_container_layout
    collapsing_through) = block_level_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 61, in block_level_layout
    return block_level_layout_switch(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 75, in block_level_layout_switch
    return block_box_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 128, in block_box_layout
    block_container_layout(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 348, in block_container_layout
    result = find_earlier_page_break(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 817, in find_earlier_page_break
    result = find_earlier_page_break(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 817, in find_earlier_page_break
    result = find_earlier_page_break(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 817, in find_earlier_page_break
    result = find_earlier_page_break(
  File "/home/vincent/venv_deleteme/lib/python3.8/site-packages/weasyprint/layout/blocks.py", line 824, in find_earlier_page_break
    resume_at = (new_child.index, resume_at)
AttributeError: 'BlockBox' object has no attribute 'index'
```

**Comment by Tontyna** [comment]
Doesn't crash here. Maybe in the meantime the offending code has been edited on Wikipedia?

**Comment by vpoulailleau** [comment]
Well… The page changed yesterday. I can't reproduce the bug either…

I also tried with the version in Wikipedia history (the rendering is not exactly the same, it mentions the fact that this is an archive). But I don't get any error.

I also checked the CSS history, it hasn't changed since the issue creation.

Here is the command with the version in Wikipedia history (without any exception):

```sh
python -m weasyprint "https://fr.wikipedia.org/w/index.php?title=Python_(langage)&oldid=172701309" --stylesheet https://vpoulailleau.github.io/formation/css/main.css python.pdf
```

I don't know what to do here. We may close the issue as not reproducible (but I got the traceback several times, since I reproduced it to open the issue 8 days ago…)

**Comment by Tontyna** [comment]
Saved the archived Wikipedia article and your stylesheet locally. Now I get the AttributeError.

**Comment by Tontyna** [comment]
BTW: When I do the same (local files) with the current Wikipedia version it crashes, too!

Ah I see: Some images fail to load in the localized version, probably changing the layout/pagination in a way that causes the crash.

**Comment by Tontyna** [comment]
Finally succeeded in creating a minimal snippet to trigger the crash:

```html
<style>
.neverbreak {
  column-width: 17cm; 
  break-after:avoid;
}
@page {
  size: 21cm 10cm;
  margin: 2cm;
}
</style>
<div class="neverbreak">
  <p>Here column-width doesn't generate columns, but 
  suppresses break-inside.</p>
  <p>In combination with break-after:avoid
  the following floating and page-crossing div crashes WeasyPrint.
  </p>
</div> 

<div style="float:right">
  <p>line1</p>
  <p>line2</p>
  <p>line3</p>
  <p>too many</p>
  <p>lines</p>
</div>
```

On the Wikipedia page the *neverbreak* is triggered by the "Notes et références" list (`column-width`) followed by a `break-avoiding` heading.

Crash happens, when the subsequent "Sur les autres projets Wikimedia" (`boite-a-droite`)
coincidentally meets the end of a page.

**Comment by Tontyna** [comment]
So this is another #36

**Comment by vpoulailleau** [comment]
OK, it seems to be a big issue in the layout engine. So that you know, I don't need any correction, this issue report was just to improve WeasyPrint. But for my "real" need, WeasyPrint is perfect.

**Comment by liZe** [comment]
That’s actually the same bug as #1191.
