### ISSUE TITLE
Problem with WeasyPrint

### ISSUE THREAD

**Issue by Guidito** [Kozea/WeasyPrint#1178]
Hi. I am installed and trying to use WeasyPrint with Django and by running the command: python -m weasyprint http://weasyprint.org weasyprint.pdf.
I get the following error: 

`Traceback (most recent call last):
  File "c: \ users \ user \ appdata \ local \ programs \ python \ python38-32 \ lib \ runpy.py", line 184, in _run
_module_as_main
    mod_name, mod_spec, code = _get_module_details (mod_name, _Error)
  File "c: \ users \ user \ appdata \ local \ programs \ python \ python38-32 \ lib \ runpy.py", line 143, in _get
_module_details
    return _get_module_details (pkg_main_name, error)
  File "c: \ users \ user \ appdata \ local \ programs \ python \ python38-32 \ lib \ runpy.py", line 110, in _get
_module_details
    __import __ (pkg_name)
  File "D: \ Files \ Guido \ Django by Example \ e-commerce \ myshop_env \ lib \ site-packages \ weasyprint \ _
_init__.py ", line 440, in <module>
    from .css import preprocess_stylesheet # noqa isort: skip
  File "D: \ Files \ Guido \ Django by Example \ e-commerce \ myshop_env \ lib \ site-packages \ weasyprint \ c
ss \ __ init__.py ", line 30, in <module>
    desde . import computed_values, media_queries
  File "D: \ Files \ Guido \ Django by Example \ e-commerce \ myshop_env \ lib \ site-packages \ weasyprint \ c
ss \ computed_values.py ", line 18, in <module>
    from .. import text
  File "D: \ Files \ Guido \ Django by Example \ e-commerce \ myshop_env \ lib \ site-packages \ weasyprint \ t
ext.py ", line 14, in <module>
    import cairocffi as cairo
  File "D: \ Files \ Guido \ Django by Example \ e-commerce \ myshop_env \ lib \ site-packages \ cairocffi \ __
init__.py ", line 48, in <module>
cairo = dlopen(
  File "D:\Archivos\Guido\Django by Example\e-commerce\myshop_env\lib\site-packages\cairocffi\__
init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

`

Can you help me? Thank you.

**Comment by liZe** [comment]
Hello!

You’ll find more information about this problem in [the documentation](https://weasyprint.readthedocs.io/en/stable/install.html#windows), and in particular [step 5](https://weasyprint.readthedocs.io/en/stable/install.html#step-5-run-weasyprint).
