### ISSUE TITLE
cannot load library 'C:\msys64\mingw64\bin\libcairo-2.dll': error 0x7f

### ISSUE THREAD

**Issue by HexCodeFFF** [Kozea/WeasyPrint#1285]
I've tried to install GTK3+ both through the installer and msys2, and i'm given the same error.

```
(caption bot) C:\Users\minec\PycharmProjects\CaptionX>python -m weasyprint http://weasyprint.org weasyprint.pdf
Traceback (most recent call last):
  File "C:\Users\minec\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\minec\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\minec\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\minec\.PyCharm2018.3\caption bot\lib\site-packages\weasyprint\__init__.py", line 469, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "C:\Users\minec\.PyCharm2018.3\caption bot\lib\site-packages\weasyprint\css\__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "C:\Users\minec\.PyCharm2018.3\caption bot\lib\site-packages\weasyprint\css\computed_values.py", line 15, in <module>
    from .. import text
  File "C:\Users\minec\.PyCharm2018.3\caption bot\lib\site-packages\weasyprint\text.py", line 11, in <module>
    import cairocffi as cairo
  File "C:\Users\minec\.PyCharm2018.3\caption bot\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\minec\.PyCharm2018.3\caption bot\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
cannot load library 'C:\msys64\mingw64\bin\libcairo-2.dll': error 0x7f
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7f
```
It gives a strange error code, `0x7f`. `0x7e` is the code for not found, and this is proven when libcairo isnt in the path, since this is the error it returns, but libcairo IS in the path, it even prints the path right there, it just errors out. I tried to debug further but I cannot find any information on what `error 0x7f` is.

Some extra info:
```
(caption bot) C:\Users\minec\PycharmProjects\CaptionX>python --version --version
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
```
```
(caption bot) C:\Users\minec\PycharmProjects\CaptionX>pip freeze
aiodns==2.0.0
aiofiles==0.6.0
aiohttp==3.6.3
async-timeout==3.0.1
attrs==20.3.0
brotlipy==0.7.0
cairocffi==1.2.0
CairoSVG==2.5.1
cchardet==2.1.7
cffi==1.14.3
chardet==3.0.4
colorama==0.4.4
coloredlogs==15.0
colorlog==4.6.2
cssselect2==0.4.1
defusedxml==0.6.0
discord.py==1.6.0
html5lib==1.1
humanfriendly==9.1
humanize==3.2.0
humansize==1.0
idna==2.10
imgkit==1.0.2
multidict==4.7.6
Pillow==8.0.1
pycares==3.1.1
pycparser==2.20
Pyphen==0.10.0
pyreadline==2.1
python-magic==0.4.13
python-magic-win64==0.4.13
PythonMagick @ file:///C:/Users/minec/PycharmProjects/caption%20bot/PythonMagick-0.9.19-cp38-cp38-win_amd64.whl
six==1.15.0
tinycss2==1.1.0
Wand==0.6.4
WeasyPrint==52.2
webencodings==0.5.1
yarl==1.5.1
```

**Comment by HexCodeFFF** [comment]
So, in the middle of writing this issue, i figured it out on my own. I want to post it anyways for others. Turns out, GTK has a file called `zlib1.dll` and my system happened to already have a file with the exact same name on the path, contained in some intel folder. renaming the duplicate fixed the issue.
