### ISSUE TITLE
AttributeError: 'TextBox' object has no attribute 'layout'

### ISSUE THREAD

**Issue by i-sf** [Kozea/WeasyPrint#1297]
Python 3.9, Windows 10, WeasyPrint version https://github.com/Kozea/WeasyPrint/commit/224f7b3e8fc0859520b274b525973237387a0622:

```
Collecting WeasyPrint
  Cloning https://github.com/Kozea/WeasyPrint.git (to revision 224f7b3e8fc0859520b274b525973237387a0622)
  -snip-
    Uninstalling WeasyPrint-52.2:
      Successfully uninstalled WeasyPrint-52.2
Successfully installed WeasyPrint-53.0
```

Traceback:

```
Traceback (most recent call last):
  -snip-
    doc.write_pdf(output)
  File "C:\Python39\lib\site-packages\weasyprint\document.py", line 1028, in write_pdf
    page.paint(stream, scale=scale)
  File "C:\Python39\lib\site-packages\weasyprint\document.py", line 713, in paint
    draw_page(self._page_box, context)
  File "C:\Python39\lib\site-packages\weasyprint\draw.py", line 158, in draw_page
    draw_stacking_context(context, stacking_context)
  File "C:\Python39\lib\site-packages\weasyprint\draw.py", line 277, in draw_stacking_context
    draw_stacking_context(context, child_context)
  File "C:\Python39\lib\site-packages\weasyprint\draw.py", line 272, in draw_stacking_context
    draw_inline_level(
  File "C:\Python39\lib\site-packages\weasyprint\draw.py", line 1023, in draw_inline_level
    draw_inline_level(
  File "C:\Python39\lib\site-packages\weasyprint\draw.py", line 1018, in draw_inline_level
    draw_text(context, child, child_offset_x, text_overflow)
  File "C:\Python39\lib\site-packages\weasyprint\draw.py", line 1062, in draw_text
    pango.pango_layout_get_context(textbox.layout),
AttributeError: 'TextBox' object has no attribute 'layout'
```

**Comment by grewn0uille** [comment]
Hello!
Can you provide the HTML/CSS used please?

**Comment by i-sf** [comment]
This fails:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
</head>
<body>
<table>
    <tr>
        <td>
            <p><a href="https://example.org">Example</a></p>
        </td>
    </tr>
</table>
</body>
</html>
```

This works:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
</head>
<body>
<table>
    <tr>
        <td>
            <p>Example</p>
        </td>
    </tr>
</table>
</body>
</html>
```

**Comment by i-sf** [comment]
Thank you!

**Comment by liZe** [comment]
Text decoration was broken, thanks a lot for the report. It’s fixed now, with tests to prevent this problem from coming back (the layout of decorated text was already tested, but not the drawing).
