### ISSUE TITLE
utf-8 error with hypens:auto and line-clamp combination

### ISSUE THREAD

**Issue by colorcube** [Kozea/WeasyPrint#1305]
Let's say you've this css

```
ul {
            continue: discard;
            widows: 1;
            orphans: 1;
            block-ellipsis: auto;
}
```

which cuts off an `<li>` and appends an ellipses when needed

If you add
```
ul {
            hyphens: auto;
}
```

It's possible that weasyprint crash. That happens when the last word which would be displayed can be devided (hyphen).

However one time I could create 'ghfdhgfdgh-...' in the last line (without crash). Hyphen and ellipses.
I think the right solution would be to not hyphen the last word when the `<li>` would be cut off?!

WeasyPrint version 52.3
The Trace:
```

Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/weasyprint/__main__.py", line 214, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/weasyprint/__init__.py", line 320, in write_png
    self.render(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/document.py", line 802, in write_png
    surface, max_width, sum_heights = self.write_image_surface(resolution)
  File "/usr/local/lib/python3.8/site-packages/weasyprint/document.py", line 778, in write_image_surface
    page.paint(context, pos_x, pos_y, scale=dppx, clip=True)
  File "/usr/local/lib/python3.8/site-packages/weasyprint/document.py", line 282, in paint
    draw_page(self._page_box, cairo_context, self._enable_hinting)
  File "/usr/local/lib/python3.8/site-packages/weasyprint/draw.py", line 161, in draw_page
    draw_stacking_context(context, stacking_context, enable_hinting)
  File "/usr/local/lib/python3.8/site-packages/weasyprint/draw.py", line 275, in draw_stacking_context
    draw_stacking_context(context, child_context, enable_hinting)
  File "/usr/local/lib/python3.8/site-packages/weasyprint/draw.py", line 269, in draw_stacking_context
    draw_inline_level(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/draw.py", line 1031, in draw_inline_level
    draw_text(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/draw.py", line 1059, in draw_text
    show_first_line(context, textbox, text_overflow, block_ellipsis)
  File "/usr/local/lib/python3.8/site-packages/weasyprint/text.py", line 1277, in show_first_line
    new_text = utf8_slice(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/text.py", line 577, in utf8_slice
    return string.encode('utf-8')[slice_].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 43-44: unexpected end of data
```

**Comment by liZe** [comment]
Two problems have been solved.

1. The crash was caused by a classical bytestring / unicode-string mismatch.
2. The last word is removed if it’s hyphenated. It’s not specified at all and browsers currently do very strange things (Firefox displays both the hyphen and the ellipsis, **superposed**), but it’s much better this way.

Tests are welcome :smile:.
