### ISSUE TITLE
WeasyPrint Navigator doesn't work

### ISSUE THREAD

**Issue by asyschikov** [Kozea/WeasyPrint#133]
weasyprint.navigator

```
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
Traceback (most recent call last):
  File "/var/www/toured_dev/lib/python2.6/site-packages/weasyprint/navigator.py", line 171, in <module>
    run()
  File "/var/www/toured_dev/lib/python2.6/site-packages/weasyprint/navigator.py", line 156, in run
    from werkzeug.serving import run_simple
  File "/var/www/toured_dev/lib/python2.6/site-packages/werkzeug/__init__.py", line 154, in <module>
    __import__('werkzeug.exceptions')
  File "/var/www/toured_dev/lib/python2.6/site-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/var/www/toured_dev/lib/python2.6/site-packages/werkzeug/wrappers.py", line 36, in <module>
    from werkzeug.utils import cached_property, environ_property, \
  File "/var/www/toured_dev/lib/python2.6/site-packages/werkzeug/utils.py", line 18, in <module>
    from html.entities import name2codepoint
  File "/var/www/toured_dev/lib/python2.6/site-packages/weasyprint/html.py", line 22, in <module>
    from .formatting_structure import boxes
ValueError: Attempted relative import in non-package
```

**Comment by liZe** [comment]
Using [Flask's CLI](http://flask.pocoo.org/docs/0.11/cli/) is the way to go.

**Comment by fried-sausage** [comment]
That means documentation is outdated.
http://weasyprint.readthedocs.io/en/latest/install.html
```
You can also play with WeasyPrint Navigator. Start it with
python -m weasyprint.navigator
```

**Comment by liZe** [comment]
> That means documentation is outdated.

Indeed, and I'm not even sure that the current code works with the CLI. That's why this issue is open :wink:.

**Comment by liZe** [comment]
The navigator wasn't using Flask, only Werkzeug. As it wasn't that useful, I've removed it and only used the builtin HTTP server.

**Comment by SimonSapin** [comment]
Werkzeug provides a reloader and debugger, which are nice when working on WeasyPrint itself. But they’re probably better integrated through the Flask CLI now.
