### ISSUE TITLE
MacBook Pro M1 OSError: no library called "cairo" was found

### ISSUE THREAD

**Issue by vasile-corobceanu** [Kozea/WeasyPrint#1340]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/weasyprint", line 5, in <module>
    from weasyprint.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weasyprint/__init__.py", line 469, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weasyprint/css/computed_values.py", line 15, in <module>
    from .. import text
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weasyprint/text.py", line 11, in <module>
    import cairocffi as cairo
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cairocffi/__init__.py", line 50, in <module>
    ('libcairo.so.2', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cairocffi/__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 2): image not found
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 2): image not found
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 2): image not found

**Comment by liZe** [comment]
Hello!

This error appears when WeasyPrint can’t find Cairo. Moreover, it looks like you use macOS’ version of Python.

Using WeasyPrint on macOS is easier if you use Homebrew, as explained in [the documentation](https://weasyprint.readthedocs.io/en/stable/install.html#macos). You should follow the installation guide and try to use Homebrew, it will probably fix your problem.

**Comment by vasile-corobceanu** [comment]
Thanks

**Comment by HenryMehta** [comment]
I followed the instructions within the setup (ie using HomeBrew) and I get the same error on a MacBook Pro M1

**Comment by vasile-corobceanu** [comment]
> I followed the instructions within the setup (ie using HomeBrew) and I get the same error on a MacBook Pro M1

Hey 👋 
I found Conda environment from Anaconda and only this worked for me. Other stuff not working for me.

**Comment by HenryMehta** [comment]
```
(autumna-dev) henrymehta@Henrys-MBP autumna % brew install cairo
Warning: cairo 1.16.0_5 is already installed and up-to-date.
To reinstall 1.16.0_5, run:
  brew reinstall cairo
(autumna-dev) henrymehta@Henrys-MBP autumna % brew install python3 cairo pango gdk-pixbuf libffi
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
sqlbench

Warning: python@3.9 3.9.5 is already installed and up-to-date.
To reinstall 3.9.5, run:
  brew reinstall python@3.9
Warning: cairo 1.16.0_5 is already installed and up-to-date.
To reinstall 1.16.0_5, run:
  brew reinstall cairo
Warning: pango 1.48.5 is already installed and up-to-date.
To reinstall 1.48.5, run:
  brew reinstall pango
Warning: gdk-pixbuf 2.42.6 is already installed and up-to-date.
To reinstall 2.42.6, run:
  brew reinstall gdk-pixbuf
Warning: libffi 3.3_3 is already installed and up-to-date.
To reinstall 3.3_3, run:
  brew reinstall libffi(autumna-dev) henrymehta@Henrys-MBP autumna % pip install WeasyPrint                            
Requirement already satisfied: WeasyPrint in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (52.4)
Requirement already satisfied: html5lib>=0.999999999 in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (from WeasyPrint) (1.1)
Requirement already satisfied: Pyphen>=0.9.1 in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (from WeasyPrint) (0.10.0)
Requirement already satisfied: tinycss2>=1.0.0 in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (from WeasyPrint) (1.1.0)
Requirement already satisfied: cssselect2>=0.1 in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (from WeasyPrint) (0.4.1)
Requirement already satisfied: cairocffi>=0.9.0 in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (from WeasyPrint) (1.2.0)
Requirement already satisfied: cffi>=0.6 in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (from WeasyPrint) (1.14.5)
Requirement already satisfied: setuptools>=39.2.0 in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (from WeasyPrint) (57.0.0)
Requirement already satisfied: Pillow>=4.0.0 in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (from WeasyPrint) (8.2.0)
Requirement already satisfied: CairoSVG>=2.4.0 in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (from WeasyPrint) (2.5.2)
Requirement already satisfied: defusedxml in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (from CairoSVG>=2.4.0->WeasyPrint) (0.7.1)
Requirement already satisfied: pycparser in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (from cffi>=0.6->WeasyPrint) (2.20)
Requirement already satisfied: webencodings in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (from cssselect2>=0.1->WeasyPrint) (0.5.1)
Requirement already satisfied: six>=1.9 in /Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages (from html5lib>=0.999999999->WeasyPrint) (1.15.0)
(autumna-dev) henrymehta@Henrys-MBP autumna % ./src/manage.py runserver                         
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/henrymehta/Documents/Sites/autumna-dev/autumna/src/core/urls.py", line 79, in <module>
    path('stats/', include('stats.urls')),
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/henrymehta/Documents/Sites/autumna-dev/autumna/src/stats/urls.py", line 3, in <module>
    from . import views, autocomplete
  File "/Users/henrymehta/Documents/Sites/autumna-dev/autumna/src/stats/views.py", line 8, in <module>
    from django_weasyprint import WeasyTemplateResponseMixin
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django_weasyprint/__init__.py", line 1, in <module>
    from .views import WeasyTemplateResponseMixin, WeasyTemplateView, WeasyTemplateResponse
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/django_weasyprint/views.py", line 1, in <module>
    import weasyprint
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/weasyprint/__init__.py", line 469, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/weasyprint/css/computed_values.py", line 15, in <module>
    from .. import text
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/weasyprint/text.py", line 11, in <module>
    import cairocffi as cairo
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/cairocffi/__init__.py", line 48, in <module>
    cairo = dlopen(
  File "/Users/henrymehta/.local/share/virtualenvs/autumna-dev-bzb1azv8/lib/python3.8/site-packages/cairocffi/__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 2): image not found
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 2): image not found
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 2): image not found
```

Please note, this is in a Python 3.8 virtualenv

**Comment by liZe** [comment]
> Please note, this is in a Python 3.8 virtualenv

You have to use Homebrew’s Python to have everything’s working. Creating your virtual environment using Hombrew’s Python (that’s 3.9, not 3.8) should work correctly.

**Comment by HenryMehta** [comment]
Same result - if I install using pip3 in Homebrew's Python it still will not work in the virtualenv, or are you saying the virtualenv Python MUST match the Homebrew Python. (please note, I have it working on Linux Ubuntu 20.04 where it doesn't match) ?

**Comment by liZe** [comment]
> Same result - if I install using pip3 in Homebrew's Python it still will not work in the virtualenv, or are you saying the virtualenv Python MUST match the Homebrew Python. (please note, I have it working on Linux Ubuntu 20.04 where it doesn't match) ?

Homebrew is designed to handle libraries for you, as long as you use the applications installed with Homebrew. If you use another Python to create your virtualenv, then you’re on your own to make your application find the libraries installed by Homebrew.

It’s different on Ubuntu, where the libraries installed by apt in a path that is by default automatically available for all applications.

**Comment by ezscode** [comment]
```shell
conda install cairo pango 
```
