### ISSUE TITLE
cannot load library 'pango-1.0-0': pango-1.0-0 issue

### ISSUE THREAD

**Issue by aabanaag** [Kozea/WeasyPrint#1424]
I got this error suddenly and not sure why, it was working perfectly earlier I was using django-weasyprint previously I removed it and used weasyprint then on my Dockerfile I added this.

```
# Install apt packages
RUN apt-get update && apt-get install --no-install-recommends -y \
  # dependencies for building Python packages
  build-essential \
  # psycopg2 dependencies
  libpq-dev \
  # WeasyPrint dependencies
  libpango-1.0-0 \
  libharfbuzz0b \
  libpangoft2-1.0-0
```

Previous I have this on my Dockerfile

```
  # WeasyPrint dependencies
  libcairo2 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libgdk-pixbuf2.0-0 \
  libffi-dev \
  shared-mime-info
```

Error from the console
```
water_conservation_docs | Traceback (most recent call last):
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/sphinx/config.py", line 327, in eval_config_file
water_conservation_docs |     execfile_(filename, namespace)
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
water_conservation_docs |     exec(code, _globals)
water_conservation_docs |   File "/docs/conf.py", line 27, in <module>
water_conservation_docs |     django.setup()
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
water_conservation_docs |     apps.populate(settings.INSTALLED_APPS)
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
water_conservation_docs |     app_config.ready()
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/apps.py", line 24, in ready
water_conservation_docs |     self.module.autodiscover()
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
water_conservation_docs |     autodiscover_modules('admin', register_to=site)
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
water_conservation_docs |     import_module('%s.%s' % (app_config.name, module_to_search))
water_conservation_docs |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
water_conservation_docs |     return _bootstrap._gcd_import(name[level:], package, level)
water_conservation_docs |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
water_conservation_docs |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
water_conservation_docs |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
water_conservation_docs |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
water_conservation_docs |   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
water_conservation_docs |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
water_conservation_docs |   File "/app/water_conservation_api/core/admin.py", line 16, in <module>
water_conservation_docs |     from water_conservation_api.core.services import OrganizationService
water_conservation_docs |   File "/app/water_conservation_api/core/services.py", line 27, in <module>
water_conservation_docs |     from water_conservation_api.core.tasks import (
water_conservation_docs |   File "/app/water_conservation_api/core/tasks.py", line 17, in <module>
water_conservation_docs |     from water_conservation_api.utils.helpers import generate_pdf, send_job_notification
water_conservation_docs |   File "/app/water_conservation_api/utils/helpers.py", line 9, in <module>
water_conservation_docs |     from weasyprint import HTML
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/weasyprint/__init__.py", line 322, in <module>
water_conservation_docs |     from .css import preprocess_stylesheet  # noqa isort:skip
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/weasyprint/css/__init__.py", line 27, in <module>
water_conservation_docs |     from . import computed_values, counters, media_queries
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/weasyprint/css/computed_values.py", line 16, in <module>
water_conservation_docs |     from ..text.ffi import ffi, pango, units_to_double
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/weasyprint/text/ffi.py", line 383, in <module>
water_conservation_docs |     pango = _dlopen(
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/weasyprint/text/ffi.py", line 377, in _dlopen
water_conservation_docs |     return ffi.dlopen(names[0])  # pragma: no cover
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen
water_conservation_docs |     lib, function_cache = _make_ffi_library(self, name, flags)
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library
water_conservation_docs |     backendlib = _load_backend_lib(backend, libname, flags)
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib
water_conservation_docs |     raise OSError(msg)
water_conservation_docs | OSError: cannot load library 'pango-1.0-0': pango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'

```

**Comment by liZe** [comment]
Hello!

This backtrace is a bit strange. It looks like you use Sphinx, that calls Django setup, that tries to autodiscover modules, that fails to import WeasyPrint. Just to be sure that the problem doesn’t come from one of these steps, could you please try to launch the WeasyPrint executable and see if you get the same error?

**Comment by aabanaag** [comment]
I'll try

**Comment by aabanaag** [comment]
Tried running it on my docker container but got this instead.

```
(water-conservation-api-3.8.9) ➜  water-conservation-api git:(feat/AQM-76) ✗ docker-compose -f local.yml run --rm django weasyprint http://weasyprint.org /tmp/weasyprint-website.pdf
Creating water-conservation-api_django_run ... done
PostgreSQL is available
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px)' the whole @media rule was ignored at 1:1686.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px)' the whole @media rule was ignored at 1:1863.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px)' the whole @media rule was ignored at 1:2040.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px)' the whole @media rule was ignored at 1:2141.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px)' the whole @media rule was ignored at 1:2242.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px)' the whole @media rule was ignored at 1:2304.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px)' the whole @media rule was ignored at 1:2367.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px)' the whole @media rule was ignored at 1:2574.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px)' the whole @media rule was ignored at 1:2782.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px)' the whole @media rule was ignored at 1:2843.
WARNING: Ignored `width:100vw` at 1:3795, invalid value.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px)' the whole @media rule was ignored at 1:4335.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px)' the whole @media rule was ignored at 1:5559.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px)' the whole @media rule was ignored at 1:6585.
WARNING: Ignored `overflow-x:hidden` at 1:6712, unknown property.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px)' the whole @media rule was ignored at 1:7421.
WARNING: Ignored `width:-moz-min-content` at 1:7652, invalid value.
WARNING: Ignored `width:-webkit-min-content` at 1:7675, invalid value.
WARNING: Ignored `width:min-content` at 1:7701, invalid value.
WARNING: Ignored `min-height:60vh` at 1:8072, invalid value.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px)' the whole @media rule was ignored at 1:8441.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px)' the whole @media rule was ignored at 1:9331.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px)' the whole @media rule was ignored at 1:9528.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px)' the whole @media rule was ignored at 1:9713.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px)' the whole @media rule was ignored at 1:10036.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px)' the whole @media rule was ignored at 1:10393.
WARNING: Ignored `box-shadow:0 0 0 .01em #1ee494` at 1:10702, unknown property.
WARNING: Ignored `box-shadow:0 0 0 .65em #19d489` at 1:11162, unknown property.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px)' the whole @media rule was ignored at 1:11297.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px)' the whole @media rule was ignored at 1:11400.
WARNING: Ignored `background-position-y:0` at 1:11986, unknown property.
WARNING: Ignored `left:calc(-.8em - .35em / 2)` at 1:12201, invalid value.

```

**Comment by aabanaag** [comment]
I'm using [cookiecutter-django](https://cookiecutter-django.readthedocs.io/en/latest/document.html) for my project which I found out was using Sphinx for the docs

**Comment by liZe** [comment]
You only have warnings now, meaning that everything is fine. WeasyPrint used alone finds Pango without a problem.

It means that there’s something wrong with the other tools. Maybe there’s something wrong with environment variables set by cookiecutter, or Sphinx, or Django…

**Comment by aabanaag** [comment]
hmm.. I know this is not part of the docs, but there is no need for weasyprint to be added to the installed_apps right?

**Comment by liZe** [comment]
> I know this is not part of the docs, but there is no need for weasyprint to be added to the installed_apps right?

What’s `installed_apps`?

**Comment by aabanaag** [comment]
I tried downgrading the version to 52.5 but instead of pango-1.0-0 the error is about libcairo now but I reverted my dockerfile so it contains 

```
  libcairo2 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libgdk-pixbuf2.0-0 \
  libffi-dev \
  shared-mime-info
```

**Comment by aabanaag** [comment]
The error 

```
water_conservation_docs | OSError: no library called "cairo" was found
water_conservation_docs | no library called "libcairo-2" was found
water_conservation_docs | cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object file: No such file or directory
water_conservation_docs | cannot load library 'libcairo.2.dylib': libcairo.2.dylib: cannot open shared object file: No such file or directory
water_conservation_docs | cannot load library 'libcairo-2.dll': libcairo-2.dll: cannot open shared object file: No such file or directory

```

**Comment by liZe** [comment]
As explained earlier, this error is probably caused by environment variables removed or modified by cookiecutter, or Sphinx, or Django. Your Docker instance works when you call WeasyPrint, but it doesn’t when you use these tools, so…

You can try to use WeasyPrint with only Django, and see if it works. You can then try with Sphinx, and then with cookiecutter until you get the error. When you know which tool changes the environment variables, it will be easier to find a solution.

**Comment by aabanaag** [comment]
Thank you for pointing it to a better path. I'll close this one since this is not really an issue for WeasyPrint
