### ISSUE TITLE
cannot load library 'gobject-2.0-0'

### ISSUE THREAD

**Issue by LanceMeister** [Kozea/WeasyPrint#1483]
### Hello, I've tried every troubleshooting option for this. I use a mac M1 and My project is in a pip wrapper environment. I've installed all required packages with homebrew. and I still get this error. is there a way to fix this that I am missing?

```
Watching for file changes with StatReloader
INFO 2021-11-02 07:24:18,683 autoreload 2663 8642752000 Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/lancemeister/PycharmProjects/music_meister_shop/musicmeister/config/urls.py", line 21, in <module>
    path("orders/", include("musicmeister.orders.urls", namespace="orders")),
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/lancemeister/PycharmProjects/music_meister_shop/musicmeister/musicmeister/orders/urls.py", line 3, in <module>
    from musicmeister.orders import views
  File "/Users/lancemeister/PycharmProjects/music_meister_shop/musicmeister/musicmeister/orders/views.py", line 13, in <module>
    from weasyprint import HTML, CSS
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/weasyprint/__init__.py", line 322, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/weasyprint/css/computed_values.py", line 16, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/weasyprint/text/ffi.py", line 380, in <module>
    gobject = _dlopen(
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/weasyprint/text/ffi.py", line 377, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Users/lancemeister/.virtualenvs/music_meister_shop/lib/python3.9/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 2): image not found.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```

**Comment by liZe** [comment]
Hello!

Your trace shows that Django launches threads using a version of Python that’s not installed by homebrew (`/Library/Frameworks/Python.framework/Versions/3.9/`). Did you create your virtual environment with Homebrew’s Python, and not macOS’ one?

**Comment by LanceMeister** [comment]
This is how my virtual env is setup

`export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3.9`
`export VIRTUALENVWRAPPER_VIRTUALENV=/opt/homebrew/anaconda3/bin/virtualenv`
`source /Library/Frameworks/Python.framework/Versions/3.9/bin/virtualenvwrapper.sh`


could this be the problem?

**Comment by liZe** [comment]
Wow, using virtrualenvwrapper on top of virtualenv on top of venv, installed by Anaconda on top of Homebrew… Python virtual environments are definitely a mess!

Here’s what I’d do, and what you should do if it’s possible:
- Remove Anaconda from Homebrew. Having one unofficial package manager on top of macOS is already a mess, having a package manager in a package manager is a crazy idea 😉.
- Unset VIRTUALENVWRAPPER_PYTHON and VIRTUALENVWRAPPER_VIRTUALENV, as they’re handled by Hombrew’s virtualenvwrapper.
- Install WeasyPrint’s dependencies in Homebrew.
- Install Homebrew’s virtualenvwrapper (if you really want to use virtualenvwrapper).
- Check that `virtualenvwrapper.sh` is the one installed by Homebrew (using `which virtualenvwrapper.sh`).
- Launch `source virtualenvwrapper.sh`.
- Remove any virtualenv related to your project from `$HOME/.virtualenvs`, and recreate them.

Don’t hesitate to ask if there’s anything you don’t fully understand, or if you can’t do this for some reason.

**Comment by LanceMeister** [comment]
hi, @liZe followed your instructions exactly and I'm happy to say problem solved. Thank you for helping me clear up that mess of virtualenv's that I had. Thank You, Thank You 🙌.  everything is now working.

**Comment by liZe** [comment]
Hello!

> OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: '/opt/homebrew/Cellar/spatialindex/1.9.3/lib/gobject-2.0-0' (no such file), '/gobject-2.0-0' (no such file), 'gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file), '/opt/homebrew/Cellar/spatialindex/1.9.3/lib/gobject-2.0-0' (no such file), '/gobject-2.0-0' (no such file), '/Users/jpala/Documents/company/applicationpath_appgobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

That’s strange to have `/opt/homebrew/Cellar/spatialindex/1.9.3/lib/gobject-2.0-0` in the list of tested files. Did you do something special with the `spatialindex` package? I suppose that the `gobject-2.0-0` file should be in `/opt/homebrew/Cellar/lib` instead, shouldn’t it?

**Comment by varsha-ram03** [comment]
Python version 3.12.3 - /Users/varuapple/Desktop/dj/in/InvenTree/src/backend/new/bin/python3

-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting 

-----

OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
You may require some further system packages to be installed.

**Comment by GoodOldBatman** [comment]
I faced this problem when setting up a pipenv on an M1. I had to use the brew python version to make it work `pipenv install --python=/opt/homebrew/bin/python3.9`

**Comment by sdancer75** [comment]
I faced the same problem posted by @varsha-ram03. Do you have any solution for this?

Win64 pro
python 3.12.11


```
WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

-----

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "D:\prj\myapp\backend\.venv\Lib\site-packages\weasyprint\__init__.py", line 440, in <module>
    from .css import preprocess_stylesheet  # noqa: I001, E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\prj\myapp\backend\.venv\Lib\site-packages\weasyprint\css\__init__.py", line 30, in <module>
    from ..text.fonts import FontConfiguration
  File "D:\prj\myapp\backend\.venv\Lib\site-packages\weasyprint\text\fonts.py", line 17, in <module>
    from .constants import (  # isort:skip
  File "D:\prj\myapp\backend\.venv\Lib\site-packages\weasyprint\text\constants.py", line 5, in <module>
    from .ffi import pango
  File "D:\prj\myapp\backend\.venv\Lib\site-packages\weasyprint\text\ffi.py", line 476, in <module>
    gobject = _dlopen(
              ^^^^^^^^
  File "D:\prj\myapp\backend\.venv\Lib\site-packages\weasyprint\text\ffi.py", line 464, in _dlopen
    return ffi.dlopen(names[0], flags)  # pragma: no cover
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\prj\myapp\backend\.venv\Lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\prj\myapp\backend\.venv\Lib\site-packages\cffi\api.py", line 834, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\prj\myapp\backend\.venv\Lib\site-packages\cffi\api.py", line 830, in _load_backend_lib
    return backend.load_library(path, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: cannot load library 'D:\Program Files\Meld\libgobject-2.0-0.dll': error 0x7e
```

**Comment by liZe** [comment]
Hi @sdancer75,

This is a case of [DLL hell](https://en.wikipedia.org/wiki/DLL_hell). You have installed another software, Meld, that has probably added its DLLs (including libgobject) in `PATH`. WeasyPrint uses these DLLs instead of the ones you installed wth MSYS2, causing the problem.

You can try to uninstall Meld and see if it fixes the problem.

**Comment by liZe** [comment]
@sdancer75 see Meld’s issue: https://gitlab.gnome.org/GNOME/meld/-/issues/940.

**Comment by sdancer75** [comment]
> [@sdancer75](https://github.com/sdancer75) see Meld’s issue: https://gitlab.gnome.org/GNOME/meld/-/issues/940.

Ok, I uninstalled the Meld app.

The error now is this

```
WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

-----

[WARNING] WeasyPrint not available: cannot load library 'libgobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libgobject-2.0-0'
[I

```

I removed WeasyPrint with `uv remove weasyprint` and reinstalled it with `uv add weasyprint`. No luck.

**Comment by liZe** [comment]
> The error now is this

@sdancer75 Did you install Pango with MSYS2? In case you didn’t use the default installation path for MSYS2, you can set the `WEASYPRINT_DLL_DIRECTORIES=C:\path\to\mingw64\bin` environment variable.

**Comment by sdancer75** [comment]
> > The error now is this
> 
> [@sdancer75](https://github.com/sdancer75) Did you install Pango with MSYS2? In case you didn’t use the default installation path for MSYS2, you can set the `WEASYPRINT_DLL_DIRECTORIES=C:\path\to\mingw64\bin` environment variable.

I am not using MSSYS2. Just clean windows powershell.


```
PS D:\prj\app\backend> uv remove weasyprint
Resolved 240 packages in 191ms
Uninstalled 7 packages in 108ms
 - brotli==1.2.0
 - fonttools==4.61.1
 - pydyf==0.12.1
 - pyphen==0.17.2
 - tinyhtml5==2.0.0
 - weasyprint==67.0
 - zopfli==0.4.0
```


and then

```
PS D:\prj\app\backend> uv add weasyprint
Resolved 248 packages in 767ms
░░░░░░░░░░░░░░░░░░░░ [0/7] Installing wheels...                                                                                                                                                                                                                                         warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 7 packages in 410ms
 + brotli==1.2.0
 + fonttools==4.61.1
 + pydyf==0.12.1
 + pyphen==0.17.2
 + tinyhtml5==2.0.0
 + weasyprint==67.0
 + zopfli==0.4.0

```

weasyprint 67.0
https://pypi.org/project/weasyprint/

I suspect that weasyprint needs external libraries from the OS itself. Am I correct? So what's the point if it has dependencies that require user intervention and the installation of 3rd-party libraries? I mean, a web app should be fully autonomous without such interventions.

**Comment by liZe** [comment]
> I am not using MSSYS2.

WeasyPrint has non-Python dependencies that you can install with MSYS2, that’s explained in the [installation steps for Windows](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows).

You can also use the executable if you don’t want to take care of these dependencies.

**Comment by sdancer75** [comment]
> > I am not using MSSYS2.
> 
> WeasyPrint has non-Python dependencies that you can install with MSYS2, that’s explained in the [installation steps for Windows](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows).
> 
> You can also use the executable if you don’t want to take care of these dependencies.

Yes I thought so...  Thanks
