### ISSUE TITLE
heise.de can’t be transformed into a PDF

### ISSUE THREAD

**Issue by JensKapitza** [Kozea/WeasyPrint#1531]
weasyprint http://heise.de heise.pdf

```
ERROR: No anchor # for internal URI reference
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/__main__.py", line 214, in main
    html.write_pdf(output, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/__init__.py", line 180, in write_pdf
    self.render(
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/document.py", line 1160, in write_pdf
    page.paint(stream, scale=scale)
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/document.py", line 769, in paint
    draw_page(self._page_box, stream)
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/draw.py", line 69, in draw_page
    draw_stacking_context(stream, stacking_context)
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/draw.py", line 182, in draw_stacking_context
    draw_stacking_context(stream, child_context)
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/draw.py", line 182, in draw_stacking_context
    draw_stacking_context(stream, child_context)
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/draw.py", line 173, in draw_stacking_context
    draw_replacedbox(stream, block)
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/draw.py", line 927, in draw_replacedbox
    box.replacement.draw(
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/images.py", line 89, in draw
    self._svg.draw(
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/svg/__init__.py", line 356, in draw
    self.draw_node(self.tree, size('12pt'))
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/svg/__init__.py", line 423, in draw_node
    self.draw_node(child, font_size, fill_stroke)
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/svg/__init__.py", line 416, in draw_node
    TAGS[node.tag](self, node, font_size)
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/svg/defs.py", line 37, in use
    bytestring_svg = svg.url_fetcher(url)
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/urls.py", line 238, in default_url_fetcher
    raise ValueError('Not an absolute URI: %r' % url)
ValueError: Not an absolute URI: '/icons/common-icons.svg#heiseplus-logo'
```

**Comment by liZe** [comment]
Thanks for the bug report! It should be fixed now.
