### ISSUE TITLE
AttributeError: 'BlockBox' object has no attribute 'index'

### ISSUE THREAD

**Issue by takesson** [Kozea/WeasyPrint#1560]
Regression btw 53.4 and 54.x.

```
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/weasyprint/__main__.py", line 188, in main
    html.write_pdf(output, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/weasyprint/__init__.py", line 183, in write_pdf
    self.render(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/__init__.py", line 134, in render
    return Document._render(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/document.py", line 930, in _render
    [Page(page_box) for page_box in page_boxes],
  File "/usr/local/lib/python3.9/site-packages/weasyprint/document.py", line 930, in <listcomp>
    [Page(page_box) for page_box in page_boxes],
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/__init__.py", line 133, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/page.py", line 855, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/page.py", line 792, in remake_page
    page, resume_at, next_page = make_page(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/page.py", line 590, in make_page
    root_box, resume_at, next_page, _, _ = block_level_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 70, in block_level_layout_switch
    return block_box_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 112, in block_box_layout
    result = block_container_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 641, in block_container_layout
    next_page, new_children) = _in_flow_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 448, in _in_flow_layout
    collapsing_through) = block_level_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 70, in block_level_layout_switch
    return block_box_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 112, in block_box_layout
    result = block_container_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 641, in block_container_layout
    next_page, new_children) = _in_flow_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 448, in _in_flow_layout
    collapsing_through) = block_level_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 70, in block_level_layout_switch
    return block_box_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 112, in block_box_layout
    result = block_container_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 641, in block_container_layout
    next_page, new_children) = _in_flow_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 448, in _in_flow_layout
    collapsing_through) = block_level_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 70, in block_level_layout_switch
    return block_box_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 112, in block_box_layout
    result = block_container_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 641, in block_container_layout
    next_page, new_children) = _in_flow_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 448, in _in_flow_layout
    collapsing_through) = block_level_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 70, in block_level_layout_switch
    return block_box_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 112, in block_box_layout
    result = block_container_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 641, in block_container_layout
    next_page, new_children) = _in_flow_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 448, in _in_flow_layout
    collapsing_through) = block_level_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 70, in block_level_layout_switch
    return block_box_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 112, in block_box_layout
    result = block_container_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 641, in block_container_layout
    next_page, new_children) = _in_flow_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 448, in _in_flow_layout
    collapsing_through) = block_level_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 70, in block_level_layout_switch
    return block_box_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 112, in block_box_layout
    result = block_container_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 641, in block_container_layout
    next_page, new_children) = _in_flow_layout(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 510, in _in_flow_layout
    result = find_earlier_page_break(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/block.py", line 889, in find_earlier_page_break
    resume_at = {children[index].index: None}
AttributeError: 'BlockBox' object has no attribute 'index'
```

**Comment by liZe** [comment]
Thanks for the report, it’s fixed in the `54.x` branch.
