### ISSUE TITLE
The 54.1 cannot print the example of the ticket

### ISSUE THREAD

**Issue by FrancoisCapon** [Kozea/WeasyPrint#1575]
Hi,

The 54.1 cannot print the example of the ticket unlike the 53.4 version:

```bash
root@4d1c5a356b98:/ticket# weasyprint ticket.html test.pdf :-(
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/weasyprint/__main__.py", line 188, in main
    html.write_pdf(output, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/weasyprint/__init__.py", line 183, in write_pdf
    self.render(
  File "/usr/local/lib/python3.9/dist-packages/weasyprint/__init__.py", line 134, in render
    return Document._render(
  File "/usr/local/lib/python3.9/dist-packages/weasyprint/document.py", line 930, in _render
    [Page(page_box) for page_box in page_boxes],
  File "/usr/local/lib/python3.9/dist-packages/weasyprint/document.py", line 930, in <listcomp>
    [Page(page_box) for page_box in page_boxes],
  File "/usr/local/lib/python3.9/dist-packages/weasyprint/layout/__init__.py", line 133, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
  File "/usr/local/lib/python3.9/dist-packages/weasyprint/layout/page.py", line 855, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)
  File "/usr/local/lib/python3.9/dist-packages/weasyprint/layout/page.py", line 792, in remake_page
    page, resume_at, next_page = make_page(
  File "/usr/local/lib/python3.9/dist-packages/weasyprint/layout/page.py", line 595, in make_page
    root_box.children = tuple(out_of_flow_boxes) + root_box.children
TypeError: can only concatenate tuple (not "list") to tuple
root@4d1c5a356b98:/ticket# pip uninstall weasyprint
Found existing installation: weasyprint 54.1
Uninstalling weasyprint-54.1:
  Would remove:
    /usr/local/bin/weasyprint
    /usr/local/lib/python3.9/dist-packages/weasyprint-54.1.dist-info/*
    /usr/local/lib/python3.9/dist-packages/weasyprint/*
Proceed (y/n)? y
  Successfully uninstalled weasyprint-54.1
root@4d1c5a356b98:/ticket# pip install weasyprint==53.4
Collecting weasyprint==53.4
  Downloading weasyprint-53.4-py3-none-any.whl (242 kB)
     |████████████████████████████████| 242 kB 2.0 MB/s 
Requirement already satisfied: Pillow>=4.0.0 in /usr/local/lib/python3.9/dist-packages (from weasyprint==53.4) (9.0.1)
...
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.9/dist-packages (from html5lib>=1.0.1->weasyprint==53.4) (1.16.0)
Installing collected packages: weasyprint
Successfully installed weasyprint-53.4
root@4d1c5a356b98:/ticket# weasyprint ticket.html test.pdf :-)
```

**Comment by liZe** [comment]
Thanks for the report, and sorry for the shameful bug…
