### ISSUE TITLE
Weasyprint 0.21 on Ubuntu 12.04 LTS 64 bit

### ISSUE THREAD

**Issue by acidjunk** [Kozea/WeasyPrint#160]
Hi,

I'm running Weasyprint on OSX and Ubuntu12.04 32 bit without any problems and I have to say I think it's the best PDF lib out there.

I tried to install it on a 64 bit Ubuntu 12.04 production server also:

Deps:
apt-get install python-dev python-pip python-lxml libcairo2 libpango1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info

Then:
pip install WeasyPrint

No errors where reported and pip installed some stuff

When I try to run weasy print

```
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 9, in <module>
    load_entry_point('WeasyPrint==0.21', 'console_scripts', 'weasyprint')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__init__.py", line 312, in <module>
    from .css import PARSER, preprocess_stylesheet
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/css/__init__.py", line 30, in <module>
    from . import computed_values
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/css/computed_values.py", line 18, in <module>
    from .. import text
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/text.py", line 204, in <module>
    pango = dlopen(ffi, 'pango-1.0', 'libpango-1.0-0')
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/text.py", line 200, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 117, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 399, in _make_ffi_library
    backendlib = backend.load_library(name, flags)
OSError: cannot load library pango-1.0: pango-1.0: cannot open shared object file: No such file or directory
```
## 

The pango lib is installed correctly and located in /usr/lib/x86_64-linux-gnu

Any help is appreciated.

**Comment by mhabashy** [comment]
I have this problem how did you fix it?

**Comment by stefankoegl** [comment]
Same here

**Comment by lorenzopiquer** [comment]
I fixed it in ubuntu 14.04: 
`apt-get install pango1.0-tests`

**Comment by hildogjr** [comment]
> I fixed it in ubuntu 14.04:
> `apt-get install pango1.0-tests`

It also solve Ubuntu 20.04 server.

**Comment by SimonSapin** [comment]
It’s likely not the `tests` package that helps but its dependency `libpango-1.0-0` or `libpangocairo-1.0-0`

**Comment by hildogjr** [comment]
Yes, thanks @SimonSapin . I just could not find that the package correct name was `libpango-1.0-0` instead `libpango1` like `libcairo2` that I installed (solving the first part of the issue).
