### ISSUE TITLE
Homebrew install gives an error "cannot load library 'gobject-2.0-0'"

### ISSUE THREAD

**Issue by beatrixwillius** [Kozea/WeasyPrint#1600]
I tried to install weasyprint with Homebrew on macOS 12.3. When doing the "weasyprint -info" I get an error:

easyprint-54.2 zopfli-0.2.1
(venv) beatrixwillius@MacBook-Air-von-Beatrix ~ % weasyprint --info
Traceback (most recent call last):
  File "/Users/beatrixwillius/venv/bin/weasyprint", line 5, in <module>
    from weasyprint.__main__ import main
  File "/Users/beatrixwillius/venv/lib/python3.8/site-packages/weasyprint/__init__.py", line 325, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/Users/beatrixwillius/venv/lib/python3.8/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "/Users/beatrixwillius/venv/lib/python3.8/site-packages/weasyprint/css/computed_values.py", line 16, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "/Users/beatrixwillius/venv/lib/python3.8/site-packages/weasyprint/text/ffi.py", line 404, in <module>
    gobject = _dlopen(
  File "/Users/beatrixwillius/venv/lib/python3.8/site-packages/weasyprint/text/ffi.py", line 391, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/Users/beatrixwillius/venv/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Users/beatrixwillius/venv/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Users/beatrixwillius/venv/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/usr/local/lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file), '/Users/beatrixwillius/gobject-2.0-0' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

After doing a lot of goggling I found this topic on StackOverflow: https://stackoverflow.com/questions/69067530/how-to-solve-weasyprint-error-message-gobject-2-0-0-error-0x7e-message 

There is a link to the docs page which gives a 404 error. I haven't a clue what to do for macOS.

**Comment by liZe** [comment]
This problem generally happens when you use macOS’ version of Python instead of Homebrew’s one to build the virtual environment. Before following the [installation guide](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#macos), you can type `which python3` and check that it’s Homebrew’s Python.

**Comment by beatrixwillius** [comment]
I'm using macOS 12.3 which doesn't include any Python. "which python" gives me 

/Users/beatrixwillius/venv/bin/python

**Comment by liZe** [comment]
> "which python" gives me
> 
> /Users/beatrixwillius/venv/bin/python

You have to launch the command before creating and activating the virtual enviromnent :).

Moreover, you have to use `python3`, not `python`.

**Comment by beatrixwillius** [comment]
Like that?

beatrixwillius@MacBook-Air-von-Beatrix ~ % source venv/bin/activate 
(venv) beatrixwillius@MacBook-Air-von-Beatrix ~ % which python             
/Users/beatrixwillius/venv/bin/python

However, "/Users/beatrixwillius/venv/bin/python" is just a symlink to "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8".

**Comment by liZe** [comment]
> beatrixwillius@MacBook-Air-von-Beatrix ~ % source venv/bin/activate
> (venv) beatrixwillius@MacBook-Air-von-Beatrix ~ % which python
> /Users/beatrixwillius/venv/bin/python

The idea is to launch `which python3` **with the 3 at the end** and **before** activating the environment.

> However, "/Users/beatrixwillius/venv/bin/python" is just a symlink to "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8".

OK, that’s an answer to the previous question: it means that it’s macOS’ Python, not Homebrew’s one.

You can:
- delete the virtual environment in `/Users/beatrixwillius/venv/` (because it doesn’t use the right version of Python)
- exactly follow what’s in the [installation guide](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#macos)
