### ISSUE TITLE
ImportError: cannot import name 'can_break_text'

### ISSUE THREAD

**Issue by cjthorley** [Kozea/WeasyPrint#1627]
Hi,
I wonder if anyone can help.  I am running a python 3.6 flask app and wanted to import weasyprint 52.5 but I get the following error:-

```
[Mon Apr 25 10:18:06.204581 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]   File "/apps/env36/project/fl_stars/wsgi.py", line 19, in <module>
[Mon Apr 25 10:18:06.204583 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]     application = create_app(os.getenv('FLASK_CONFIG') or 'default')
[Mon Apr 25 10:18:06.204586 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]   File "/apps/env36/project/fl_stars/main/__init__.py", line 55, in create_app
[Mon Apr 25 10:18:06.204588 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]     configure_application(app, config_name)
[Mon Apr 25 10:18:06.204590 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]   File "/apps/env36/project/fl_stars/main/__init__.py", line 77, in configure_application
[Mon Apr 25 10:18:06.204601 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]     from main.resource import api
[Mon Apr 25 10:18:06.204604 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]   File "/apps/env36/project/fl_stars/main/resource/__init__.py", line 2, in <module>
[Mon Apr 25 10:18:06.204606 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]     from main.resource.study import DoseAssignmentList, DoseAssignmentEntity, StudyEntity, StudyList, StudyProperty, \\
[Mon Apr 25 10:18:06.204609 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]   File "/apps/env36/project/fl_stars/main/resource/study.py", line 29, in <module>
[Mon Apr 25 10:18:06.204610 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]     from main.util import study as study_util
[Mon Apr 25 10:18:06.204613 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]   File "/apps/env36/project/fl_stars/main/util/study.py", line 19, in <module>
[Mon Apr 25 10:18:06.204614 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]     from weasyprint import HTML, CSS
[Mon Apr 25 10:18:06.204617 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]   File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/__init__.py", line 473, in <module>
[Mon Apr 25 10:18:06.204619 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]     from .document import Document, Page  # noqa isort:skip
[Mon Apr 25 10:18:06.204621 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]   File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/document.py", line 17, in <module>
[Mon Apr 25 10:18:06.204623 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]     from weasyprint.layout import LayoutContext
[Mon Apr 25 10:18:06.204625 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]   File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/layout/__init__.py", line 24, in <module>
[Mon Apr 25 10:18:06.204627 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]     from .pages import make_all_pages, make_margin_boxes
[Mon Apr 25 10:18:06.204630 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]   File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/layout/pages.py", line 15, in <module>
[Mon Apr 25 10:18:06.204631 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]     from .blocks import block_container_layout, block_level_layout
[Mon Apr 25 10:18:06.204634 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]   File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 14, in <module>
[Mon Apr 25 10:18:06.204635 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]     from .inlines import (
[Mon Apr 25 10:18:06.204638 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]   File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/layout/inlines.py", line 14, in <module>
[Mon Apr 25 10:18:06.204639 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143]     from ..text import can_break_text, create_layout, split_first_line
[Mon Apr 25 10:18:06.204649 2022] [wsgi:error] [pid 3747] [remote 192.168.237.2:61143] ImportError: cannot import name 'can_break_text'
```

I am running on centosOS linux 7 with limited to pango-view (pango) 1.42.3. hence using weasyprint 52.5 (https://doc.courtbouillon.org/weasyprint/stable/first_steps.html).

Any help much appreciated.

**Comment by liZe** [comment]
Hello!

Could you please activate your virtual environment, launch `python -m weasyprint` and give your error message?

**Comment by cjthorley** [comment]
![image](https://user-images.githubusercontent.com/34962209/165291049-40e539ff-0acb-49f3-91d9-c9d74804314a.png)

**Comment by liZe** [comment]
Can you try `python -m weasyprint https://weasyprint.org test.pdf`? There’s no `-i` nor `-o`.

**Comment by cjthorley** [comment]
I did a quick PDF test generation from HTML and it did not error
![image](https://user-images.githubusercontent.com/34962209/165293101-52c73632-2116-46a0-b3c8-efaa40201c13.png)

**Comment by cjthorley** [comment]
This is the result of executing "python -m weasyprint https://weasyprint.org test.pdf":


**(fl_stars) [pydev@vxpydev36 fl_stars]$ python -m weasyprint https://weasyprint.org test.pdf
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/urls.py", line 252, in fetch
    result = url_fetcher(url)
  File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/urls.py", line 219, in default_url_fetcher
    context=ssl_context)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/__main__.py", line 218, in <module>
    main()
  File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/__main__.py", line 213, in main
    media_type=args.media_type)
  File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/__init__.py", line 109, in __init__
    with result as (source_type, source, base_url, protocol_encoding):
  File "/usr/local/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/__init__.py", line 430, in _select_source
    with result as result:
  File "/usr/local/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/__init__.py", line 440, in _select_source
    with fetch(url_fetcher, url) as result:
  File "/usr/local/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/apps/env36/virtualenv/fl_stars/lib/python3.6/site-packages/weasyprint/urls.py", line 254, in fetch
    raise URLFetchingError('%s: %s' % (type(exc).__name__, str(exc)))
weasyprint.urls.URLFetchingError: URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
(fl_stars) [pydev@vxpydev36 fl_stars]$**

**Comment by cjthorley** [comment]
Hi,
I removed some older pip packages from my requirements.txt (see screen shot below) which I think related to an older version of weasyprint which supported py27.

![image](https://user-images.githubusercontent.com/34962209/165485417-bb04c04b-ff8e-4b8c-b082-33643aba9924.png)

Since removing these WeasyPrint==52.5 imports HTML and CSS without the error described at the top.

I think this is resolved and sorry to waste your time.  
Cheers
Chris
