### ISSUE TITLE
text-decoration-color does not accept var() values

### ISSUE THREAD

**Issue by palb91** [Kozea/WeasyPrint#1697]
Hello!

First, thanks for this amazing tool / library !

I use CSS variables to style some parts of a report, it works well for many css properties but I got an error with the `a` property `text-decoration-color`.

Here is a short example of how I use it:

```html
<html>
    <head>
        <style>
a {
    --light-red: #FF7777;
    text-decoration-color: var(--light-red);
}
        </style>
    </head>
    <body>
        <h1 id="title">Title</h1>
        <a href="#title">here</a>
    </body>
</html>
```

And running it raise the following error:

```console
$ .venv/bin/python3 --version
Python 3.10.5

$ .venv/bin/weasyprint --version
WeasyPrint version 56.1

$ .venv/bin/weasyprint test.html out.pdf
Traceback (most recent call last):
  File "/tmp/wztest/.venv/bin/weasyprint", line 8, in <module>
    sys.exit(main())
  File "/tmp/wztest/.venv/lib/python3.10/site-packages/weasyprint/__main__.py", line 218, in main
    html.write_pdf(output, **kwargs)
  File "/tmp/wztest/.venv/lib/python3.10/site-packages/weasyprint/__init__.py", line 201, in write_pdf
    .write_pdf(
  File "/tmp/wztest/.venv/lib/python3.10/site-packages/weasyprint/document.py", line 335, in write_pdf
    pdf = generate_pdf(
  File "/tmp/wztest/.venv/lib/python3.10/site-packages/weasyprint/pdf/__init__.py", line 316, in generate_pdf
    page.paint(stream, scale=scale)
  File "/tmp/wztest/.venv/lib/python3.10/site-packages/weasyprint/document.py", line 96, in paint
    draw_page(self._page_box, stream)
  File "/tmp/wztest/.venv/lib/python3.10/site-packages/weasyprint/draw.py", line 68, in draw_page
    draw_stacking_context(stream, stacking_context)
  File "/tmp/wztest/.venv/lib/python3.10/site-packages/weasyprint/draw.py", line 169, in draw_stacking_context
    draw_stacking_context(stream, child_context)
  File "/tmp/wztest/.venv/lib/python3.10/site-packages/weasyprint/draw.py", line 164, in draw_stacking_context
    draw_inline_level(
  File "/tmp/wztest/.venv/lib/python3.10/site-packages/weasyprint/draw.py", line 956, in draw_inline_level
    draw_inline_level(
  File "/tmp/wztest/.venv/lib/python3.10/site-packages/weasyprint/draw.py", line 953, in draw_inline_level
    draw_text(
  File "/tmp/wztest/.venv/lib/python3.10/site-packages/weasyprint/draw.py", line 1003, in draw_text
    draw_text_decoration(
  File "/tmp/wztest/.venv/lib/python3.10/site-packages/weasyprint/draw.py", line 1237, in draw_text_decoration
    stream.set_color_rgb(*color[:3], stroke=True)
TypeError: Stream.set_color_rgb() missing 1 required positional argument: 'b'
```

For now, I locked the version to `54.3`, the bug exists since Weasyprint 55+.

**Comment by liZe** [comment]
Thanks for the bug report! It’s fixed and tested in the current master branch, real life tests are welcome!

**Comment by palb91** [comment]
And thanks for you fix. I confirm it works with my project.
