### ISSUE TITLE
Do not fail pdf generation if one image is broken

### ISSUE THREAD

**Issue by cocorossello** [Kozea/WeasyPrint#1715]
Hi,

We are rendering external images in PDF. In a very few cases image is broken for some reason (although is not apparently if you render it on the browser). Weasyprint fails the whole document. It would be great if it logs an error instead of throwing an error or the user can plug a custom "image_renderer" (something like that).

This example: 

```
<!DOCTYPE html>
<html >
<head>
</head>

<body >
<img src="https://cdn4.travelconline.com/unsafe/fit-in/800x0/filters:quality(75):format(jpg)/https%3A%2F%2Fi.travelapi.com%2Fhotels%2F22000000%2F21540000%2F21537500%2F21537420%2F8a95c8cf_z.jpg"/>
</body>
</html>

```

Throws an error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/src/app/wsgi.py", line 21, in checkauth
    return f(*args, **kwargs)
  File "/usr/src/app/wsgi.py", line 101, in generate
    pdf = html.write_pdf()
  File "/usr/local/lib/python3.10/site-packages/weasyprint/__init__.py", line 201, in write_pdf
    .write_pdf(
  File "/usr/local/lib/python3.10/site-packages/weasyprint/document.py", line 335, in write_pdf
    pdf = generate_pdf(
  File "/usr/local/lib/python3.10/site-packages/weasyprint/pdf/__init__.py", line 316, in generate_pdf
    page.paint(stream, scale=scale)
  File "/usr/local/lib/python3.10/site-packages/weasyprint/document.py", line 96, in paint
    draw_page(self._page_box, stream)
  File "/usr/local/lib/python3.10/site-packages/weasyprint/draw.py", line 68, in draw_page
    draw_stacking_context(stream, stacking_context)
  File "/usr/local/lib/python3.10/site-packages/weasyprint/draw.py", line 169, in draw_stacking_context
    draw_stacking_context(stream, child_context)
  File "/usr/local/lib/python3.10/site-packages/weasyprint/draw.py", line 164, in draw_stacking_context
    draw_inline_level(
  File "/usr/local/lib/python3.10/site-packages/weasyprint/draw.py", line 956, in draw_inline_level
    draw_inline_level(
  File "/usr/local/lib/python3.10/site-packages/weasyprint/draw.py", line 960, in draw_inline_level
    draw_replacedbox(stream, box)
  File "/usr/local/lib/python3.10/site-packages/weasyprint/draw.py", line 923, in draw_replacedbox
    box.replacement.draw(
  File "/usr/local/lib/python3.10/site-packages/weasyprint/images.py", line 53, in draw
    image_name = stream.add_image(
  File "/usr/local/lib/python3.10/site-packages/weasyprint/pdf/stream.py", line 363, in add_image
    pillow_image.save(image_file, format='JPEG', optimize=optimize)
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 2284, in save
    self._ensure_mutable()
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 599, in _ensure_mutable
    self._copy()
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 592, in _copy
    self.load()
  File "/usr/local/lib/python3.10/site-packages/PIL/ImageFile.py", line 251, in load
    raise OSError(
OSError: image file is truncated (0 bytes not processed)

```

**Comment by liZe** [comment]
Hi! Thanks for the bug report.

> Weasyprint fails the whole document. It would be great if it logs an error instead of throwing an error or the user can plug a custom "image_renderer" (something like that).

Broken images are supposed to be handled when they’re first read, not when they’re saved. It seems that this can happen … when images are truncated 😁. Let’s hope that it’s the only case. At least, that’s the one we have here, and that’s the one that can be prevented in Pillow with an option. So let’s enable this feature!

**Comment by cocorossello** [comment]
Tested, works fine. 
Thanks

**Comment by GKNewsrooms** [comment]
Sorry to necro this but setting a global flag on import is insanity. Do you guys think you could move this to a gated place wherever it actually throws (OR the saner idea: document it for end users?), as of now I need to wrap the library import in an extra file that resets the flag afterwards. You are making a decision for all users of your library SILENTLY. I am really confused how no one else noticed this.

I dont currently understand why this library needs to do this, this is like globally changing debug logging on import. isnt it on the user to give correct images? They can set the flag themself if they need it.

**Comment by liZe** [comment]
@GKNewsrooms I think that you’re on the wrong issue. I also think that you shouldn’t start your comments by telling someone that their choices are insane.
