### ISSUE TITLE
HTML().write_pdf broken by pydyf 0.4.0 (list indices must be integers or slices, not bytes)

### ISSUE THREAD

**Issue by flodolo** [Kozea/WeasyPrint#1737]
I have an action generating PDF from Markdown files, luckily enough it ran fine yesterday and broke today, so it was easy to pin point the issue.

The code is straightforward

```
from weasyprint import HTML

HTML(string=html_content).write_pdf(some_file)
```

This breaks with this stack trace, with the latest version of [pydyf](https://pypi.org/project/pydyf/) (0.4.0). Installing that explicitly via requirements with version 0.3.0 works around the issue

```
Traceback (most recent call last):
  File "/Users/repo/.github/scripts/convert_to_pdf.py", line 84, in <module>
    main()
  File "/Users/repo/.github/scripts/convert_to_pdf.py", line 80, in main
    HTML(string=html_content).write_pdf(dest_file)
  File "/Users/repo/venv/lib/python3.9/site-packages/weasyprint/__init__.py", line 198, in write_pdf
    self.render(
  File "/Users/repo/venv/lib/python3.9/site-packages/weasyprint/document.py", line 335, in write_pdf
    pdf = generate_pdf(
  File "/Users/repo/venv/lib/python3.9/site-packages/weasyprint/pdf/__init__.py", line 388, in generate_pdf
    outlines, count = _create_bookmarks(root, pdf)
  File "/Users/repo/venv/lib/python3.9/site-packages/weasyprint/pdf/__init__.py", line 211, in _create_bookmarks
    pdf.objects[pdf.pages['Kids'][page*3]].reference, '/XYZ', x, y, 0))
TypeError: list indices must be integers or slices, not bytes
```

**Comment by grewn0uille** [comment]
Thanks for reporting the issue! We just released pydyf v0.5.0 to not break the API.
Sorry for the inconvenience.
