### ISSUE TITLE
PDF export fails on Windows: ctypes.util.find_library() did not manage to locate a library called 'fontconfig-1'

### ISSUE THREAD

**Issue by clstaudt** [Kozea/WeasyPrint#1745]
Here is the full stack trace:

```shell
2022-10-18 20:27:49.651 | ERROR    | tuttle.controller:billing:310 - ctypes.util.find_library() did not manage to locate a library called 'fontconfig-1'
Traceback (most recent call last):

  File "C:\Users\Admin\anaconda3\lib\threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000027AC30BDEE0>
    └ <Thread(Thread-29, started daemon 9384)>

  File "C:\Users\Admin\anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000027AC30BDC10>
    └ <Thread(Thread-29, started daemon 9384)>

  File "C:\Users\Admin\anaconda3\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-29, started daemon 9384)>
    │    │        │    └ (<flet.control_event.ControlEvent object at 0x0000027ACD237CA0>,)
    │    │        └ <Thread(Thread-29, started daemon 9384)>
    │    └ <bound method InvoicingPage.on_click_generate_invoices of <__main__.InvoicingPage object at 0x0000027ACD17ED30>>
    └ <Thread(Thread-29, started daemon 9384)>

  File "C:\Users\Admin\Dev\tuttle\app\Tuttle.py", line 337, in on_click_generate_invoices
    self.app.con.billing(
    │    │   │   └ <function Controller.billing at 0x0000027ACCD388B0>
    │    │   └ <tuttle.controller.Controller object at 0x0000027ACD0F3F40>
    │    └ <__main__.App object at 0x0000027ACD139280>
    └ <__main__.InvoicingPage object at 0x0000027ACD17ED30>

> File "c:\users\admin\dev\tuttle\tuttle\controller.py", line 300, in billing
    rendering.render_invoice(
    │         └ <function render_invoice at 0x0000027ACCCB6F70>
    └ <module 'tuttle.rendering' from 'c:\\users\\admin\\dev\\tuttle\\tuttle\\rendering.py'>

  File "c:\users\admin\dev\tuttle\tuttle\rendering.py", line 187, in render_invoice
    convert_html_to_pdf(
    └ <function convert_html_to_pdf at 0x0000027ACCCB63A0>

  File "c:\users\admin\dev\tuttle\tuttle\rendering.py", line 39, in convert_html_to_pdf
    _convert_html_to_pdf_with_weasyprint(
    └ <function _convert_html_to_pdf_with_weasyprint at 0x0000027ACCCB6E50>

  File "c:\users\admin\dev\tuttle\tuttle\rendering.py", line 75, in _convert_html_to_pdf_with_weasyprint
    import weasyprint

  File "C:\Users\Admin\anaconda3\lib\site-packages\weasyprint\__init__.py", line 336, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip

  File "C:\Users\Admin\anaconda3\lib\site-packages\weasyprint\css\__init__.py", line 25, in <module>
    from . import computed_values, counters, media_queries

  File "C:\Users\Admin\anaconda3\lib\site-packages\weasyprint\css\computed_values.py", line 9, in <module>
    from ..text.ffi import ffi, pango, units_to_double

  File "C:\Users\Admin\anaconda3\lib\site-packages\weasyprint\text\ffi.py", line 408, in <module>
    fontconfig = _dlopen(
                 └ <function _dlopen at 0x0000027ACEDE6040>

  File "C:\Users\Admin\anaconda3\lib\site-packages\weasyprint\text\ffi.py", line 385, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
           │   │      └ ('fontconfig-1', 'fontconfig', 'libfontconfig', 'libfontconfig.so.1', 'libfontconfig-1.dylib', 'libfontconfig-1.dll')
           │   └ <function FFI.dlopen at 0x0000027ACD9448B0>
           └ <cffi.api.FFI object at 0x0000027ACED76A00>

  File "C:\Users\Admin\anaconda3\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          │                 │     │     └ 0
                          │                 │     └ 'fontconfig-1'
                          │                 └ <cffi.api.FFI object at 0x0000027ACED76A00>
                          └ <function _make_ffi_library at 0x0000027ACD946160>

  File "C:\Users\Admin\anaconda3\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 │                 │        │        └ 0
                 │                 │        └ 'fontconfig-1'
                 │                 └ <module '_cffi_backend' from 'C:\\Users\\Admin\\anaconda3\\lib\\site-packages\\_cffi_backend.cp39-win_amd64.pyd'>
                 └ <function _load_backend_lib at 0x0000027ACD918D30>

  File "C:\Users\Admin\anaconda3\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
                  └ "ctypes.util.find_library() did not manage to locate a library called 'fontconfig-1'"

OSError: ctypes.util.find_library() did not manage to locate a library called 'fontconfig-1'
```

**Comment by FelixSchwarz** [comment]
Most likely this is a problem in your install. Did you [install GTK3 as mentioned in the documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows)? If that does not help [try searching for 'fontconfig-1' issues](https://github.com/Kozea/WeasyPrint/issues?q=is%3Aissue+%27fontconfig-1%27) in the issue tracker.

**Comment by liZe** [comment]
Closing, as the problem doesn’t seem to be in WeasyPrint.
