### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by ArnoRx** [Kozea/WeasyPrint#1806]
Hi, 
I get this exception when I try to generate a PDF from an HTML page. 
Some minor changes to the HTML source file (deleting some tags, some words) result in the PDF being generated successfully.

I got the bug with Weasyprint 57.2 with the following dependencies info: 

```
System: Linux
Machine: x86_64
Version: #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023
Release: 5.15.0-58-generic

WeasyPrint version: 57.2
Python version: 3.8.16
Pydyf version: 0.5.0
Pango version: 14602
```

Complete exception trace: 

```
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/weasyprint/__main__.py", line 218, in main
    html.write_pdf(output, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/weasyprint/__init__.py", line 198, in write_pdf
    self.render(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/__init__.py", line 143, in render
    return Document._render(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/document.py", line 219, in _render
    [Page(page_box) for page_box in page_boxes],
  File "/usr/local/lib/python3.8/site-packages/weasyprint/document.py", line 219, in <listcomp>
    [Page(page_box) for page_box in page_boxes],
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/__init__.py", line 128, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/page.py", line 852, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/page.py", line 788, in remake_page
    page, resume_at, next_page = make_page(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/page.py", line 586, in make_page
    root_box, resume_at, next_page, _, _, _ = block_level_layout(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 59, in block_level_layout
    return block_level_layout_switch(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 75, in block_level_layout_switch
    return block_box_layout(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 120, in block_box_layout
    result = block_container_layout(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 686, in block_container_layout
    next_page, new_children, new_max_lines) = _in_flow_layout(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 482, in _in_flow_layout
    collapsing_through, max_lines) = block_level_layout(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 59, in block_level_layout
    return block_level_layout_switch(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 75, in block_level_layout_switch
    return block_box_layout(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 120, in block_box_layout
    result = block_container_layout(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 686, in block_container_layout
    next_page, new_children, new_max_lines) = _in_flow_layout(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 482, in _in_flow_layout
    collapsing_through, max_lines) = block_level_layout(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 59, in block_level_layout
    return block_level_layout_switch(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 75, in block_level_layout_switch
    return block_box_layout(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 120, in block_box_layout
    result = block_container_layout(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 713, in block_container_layout
    remove_placeholders(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 1032, in remove_placeholders
    remove_placeholders(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/layout/block.py", line 1038, in remove_placeholders
    fixed_boxes.remove(box)
ValueError: list.remove(x): x not in list
```

I cannot completely anonymize the HTML source file (tiny modifications result in a 0 return code) so I sent you this file on private message. Bellow a Dockerfile to allow you to easily reproduce on the same conditions.

```console
tee -a Dockerfile << END
FROM python:3.8-slim-bullseye
WORKDIR /opt/code
RUN apt-get update && apt -y upgrade
RUN apt-get install -y --no-install-recommends graphviz graphviz-dev iputils-ping build-essential python3-dev git && pip install weasyprint==57.2
RUN apt-get install -y python3-pip python3-cffi python3-brotli libpango-1.0-0 libpangoft2-1.0-0
END

docker build -t bullseye-weasyprint .

docker run -v .:/opt/code -it bullseye-weasyprint weasyprint error_input.html output.pdf 
```

BR

**Comment by liZe** [comment]
Thanks a lot for the detailed issue! The bug is fixed and tested to avoid regressions.
