### ISSUE TITLE
Dictionary changed size during iteration

### ISSUE THREAD

**Issue by grewn0uille** [Kozea/WeasyPrint#1807]
When running:
`python -m weasyprint https://www.nintendo.co.uk/News/2022/March/Ask-the-Developer-Vol-4-Kirby-and-the-Forgotten-Land-2187039.html article.pdf`

Version: v58.0b1

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lucie/Projets/WeasyPrint/weasyprint/__main__.py", line 225, in <module>
    main()
  File "/home/lucie/Projets/WeasyPrint/weasyprint/__main__.py", line 221, in main
    html.write_pdf(output, **kwargs)
  File "/home/lucie/Projets/WeasyPrint/weasyprint/__init__.py", line 203, in write_pdf
    self.render(
  File "/home/lucie/Projets/WeasyPrint/weasyprint/__init__.py", line 146, in render
    return Document._render(
  File "/home/lucie/Projets/WeasyPrint/weasyprint/document.py", line 223, in _render
    [Page(page_box) for page_box in page_boxes],
  File "/home/lucie/Projets/WeasyPrint/weasyprint/document.py", line 223, in <listcomp>
    [Page(page_box) for page_box in page_boxes],
  File "/home/lucie/Projets/WeasyPrint/weasyprint/layout/__init__.py", line 128, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
  File "/home/lucie/Projets/WeasyPrint/weasyprint/layout/page.py", line 852, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)
  File "/home/lucie/Projets/WeasyPrint/weasyprint/layout/page.py", line 788, in remake_page
    page, resume_at, next_page = make_page(
  File "/home/lucie/Projets/WeasyPrint/weasyprint/layout/page.py", line 570, in make_page
    for box, containing_block, skip_stack in context_out_of_flow:
RuntimeError: dictionary changed size during iteration
```

**Comment by liZe** [comment]
Note that the crash is fixed, but the rendering is buggy. See commit 16cf66c for details.
