### ISSUE TITLE
no anchor & unboundlocal error

### ISSUE THREAD

**Issue by Michelle951** [Kozea/WeasyPrint#1834]
Hi there,

I have python 3.8.9 and weasyprint 58.1. When running mkdocs build, I have the following error. I'm a technical writer who needs to export docsite to a single document with this excellent tool. Cloud you please help out? Thanks a lot!

docsite repo: https://github.com/DaoCloud/DaoCloud-docs

```
ERROR:weasyprint:No anchor #reference/troubleshooting/ghippo02/:__codelineno-0-13 for internal URI reference
ERROR:weasyprint:No anchor #reference/troubleshooting/ghippo02/:__codelineno-0-14 for internal URI reference
INFO:weasyprint.progress:Step 7 - Adding PDF metadata
WARNING:fontTools.ttLib.tables.O_S_2f_2:fsSelection bit 5 (bold) and head table macStyle bit 0 (bold) should match
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 250, in build_command
    build.build(cfg, dirty=not clean)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 332, in build
    config.plugins.run_event('post_build', config=config)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 522, in run_event
    result = method(**kwargs)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs_with_pdf/plugin.py", line 135, in on_post_build
    self.generator.on_post_build(config, self.config['output_path'])
  File "/usr/local/lib/python3.11/site-packages/mkdocs_with_pdf/generator.py", line 157, in on_post_build
    render.write_pdf(abs_pdf_path)
  File "/usr/local/lib/python3.11/site-packages/weasyprint/document.py", line 360, in write_pdf
    pdf = generate_pdf(
          ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weasyprint/pdf/__init__.py", line 256, in generate_pdf
    pdf_fonts = build_fonts_dictionary(pdf, document.fonts, optimize_size)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weasyprint/pdf/fonts.py", line 27, in build_fonts_dictionary
    font.clean(cmap)
  File "/usr/local/lib/python3.11/site-packages/weasyprint/pdf/stream.py", line 120, in clean
    self.ttfont.save(optimized_font)
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 201, in save
    writer_reordersTables = self._save(tmp)
                            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 248, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 699, in _writeTable
    tabledata = self.getTableData(tag)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 721, in getTableData
    return self.tables[tag].compile(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/tables/_s_b_i_x.py", line 80, in compile
    current_strike.compile(ttFont)
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/tables/sbixStrike.py", line 105, in compile
    current_glyph.compile(ttFont)
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/tables/sbixGlyph.py", line 100, in compile
    rawdata += self.imageData
    ^^^^^^^
UnboundLocalError: cannot access local variable 'rawdata' where it is not associated with a value
```

**Comment by cavanierc** [comment]
I have the same issue, I have lock fonttools==4.38.0 for a temporary fix.

**Comment by liZe** [comment]
There’s an obvious bug here:

https://github.com/fonttools/fonttools/blob/1a202ab1bebe9a70f77300586905351033538806/Lib/fontTools/ttLib/tables/sbixGlyph.py#L93-L101

I’ll open a PR for fonttools and close this issue.

**Comment by liZe** [comment]
https://github.com/fonttools/fonttools/pull/3031

**Comment by Michelle951** [comment]
I used fonttools v 4.38.0 and it works as expected. Thank you both very much.
