### ISSUE TITLE
Failed to split text with non ASCII Character

### ISSUE THREAD

**Issue by slimane-deb** [Kozea/WeasyPrint#1852]
I have an html element in my document  which contains the following:

`<h3 style="display: inline-block;"> Some title    </h3>`

the special character at the end of the title is **LS**, a Line separator character (~ \u2028)

I got the stack trace of the error that you find right bellow.

And after digging inside `inlines.py`  the function `split_text_box` is not able to get the right text from the element. At a point it is able to encode it to UTF-8 which result in this string: `  b' Some title\xe2\x80\xa8 '`, but not to complete the parsing.

I was able to overcome the issue by setting ` style="display: block;"`. So somehow the line break from the display block is preventing that character from being rendered. But I have many element with inline style.
Is there a way to fix this without changing the styling of my entire HTML document? something like escaping Unicode non printable characters?

the WeasyPrint version that I have is **52.5**. I tried with v**57.1** and I got the same issue.

**Comment by slimane-deb** [comment]
```
Traceback (most recent call last):

  File "path\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "path\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "path\Programs\Python\Python38\Scripts\weasyprint.exe\__main__.py", line 7, in <module>

  File "path\programs\python\python38\lib\site-packages\weasyprint\__main__.py", line 214, in main
    getattr(html, 'write_' + format_)(output, **kwargs)

  File "path\programs\python\python38\lib\site-packages\weasyprint\__init__.py", line 222, in write_pdf
    self.render(

  File "path\programs\python\python38\lib\site-packages\weasyprint\__init__.py", line 172, in render
    return Document._render(

  File "path\programs\python\python38\lib\site-packages\weasyprint\document.py", line 406, in _render
    [Page(page_box, enable_hinting) for page_box in page_boxes],

  File "path\programs\python\python38\lib\site-packages\weasyprint\document.py", line 406, in <listcomp>
    [Page(page_box, enable_hinting) for page_box in page_boxes],

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\__init__.py", line 123, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\pages.py", line 801, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\pages.py", line 738, in remake_page
    page, resume_at, next_page = make_page(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\pages.py", line 548, in make_page
    root_box, resume_at, next_page, _, _ = block_level_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 58, in block_level_layout
    return block_level_layout_switch(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 72, in block_level_layout_switch
    return block_box_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 126, in block_box_layout
    block_container_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 517, in block_container_layout
    collapsing_through) = block_level_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 58, in block_level_layout
    return block_level_layout_switch(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 72, in block_level_layout_switch
    return block_box_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 126, in block_box_layout
    block_container_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 517, in block_container_layout
    collapsing_through) = block_level_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 58, in block_level_layout
    return block_level_layout_switch(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 72, in block_level_layout_switch
    return block_box_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 126, in block_box_layout
    block_container_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 517, in block_container_layout
    collapsing_through) = block_level_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 58, in block_level_layout
    return block_level_layout_switch(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 72, in block_level_layout_switch
    return block_box_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 126, in block_box_layout
    block_container_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 517, in block_container_layout
    collapsing_through) = block_level_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 58, in block_level_layout
    return block_level_layout_switch(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 72, in block_level_layout_switch
    return block_box_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 126, in block_box_layout
    block_container_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 517, in block_container_layout
    collapsing_through) = block_level_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 58, in block_level_layout
    return block_level_layout_switch(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 72, in block_level_layout_switch
    return block_box_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 126, in block_box_layout
    block_container_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 517, in block_container_layout
    collapsing_through) = block_level_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 58, in block_level_layout
    return block_level_layout_switch(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 72, in block_level_layout_switch
    return block_box_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 126, in block_box_layout
    block_container_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 517, in block_container_layout
    collapsing_through) = block_level_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 58, in block_level_layout
    return block_level_layout_switch(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 72, in block_level_layout_switch
    return block_box_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 126, in block_box_layout
    block_container_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\blocks.py", line 379, in block_container_layout
    for i, (line, resume_at) in enumerate(lines_iterator):

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\inlines.py", line 48, in iter_line_boxes
    line, resume_at = get_next_linebox(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\inlines.py", line 103, in get_next_linebox
    last_letter, float_width) = split_inline_box(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\inlines.py", line 760, in split_inline_box
    split_inline_level(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\inlines.py", line 623, in split_inline_level
    new_box = atomic_box(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\inlines.py", line 505, in atomic_box
    box = inline_block_box_layout(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\inlines.py", line 531, in inline_block_box_layout
    inline_block_width(box, context, containing_block)

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\min_max.py", line 17, in wrapper
    result = function(box, *args)

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\inlines.py", line 568, in inline_block_width
    box.width = shrink_to_fit(context, box, containing_block.width)

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\preferred.py", line 31, in shrink_to_fit
    min_content_width(context, box, outer=False),

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\preferred.py", line 48, in min_content_width
    return block_min_content_width(context, box, outer)

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\preferred.py", line 169, in block_min_content_width
    return _block_content_width(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\preferred.py", line 98, in _block_content_width
    children_widths = [

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\preferred.py", line 99, in <listcomp>
    function(context, child, outer=True) for child in box.children

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\preferred.py", line 52, in min_content_width
    return inline_min_content_width(

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\preferred.py", line 195, in inline_min_content_width
    widths[-1] -= trailing_whitespace_size(context, box)

  File "path\programs\python\python38\lib\site-packages\weasyprint\layout\preferred.py", line 742, in trailing_whitespace_size
    assert stripped_box is not None
AssertionError


```

**Comment by slimane-deb** [comment]
Could be relevant
https://github.com/Kozea/WeasyPrint/issues/610

**Comment by slimane-deb** [comment]
Other precision, only when the character is at the end.

**Comment by liZe** [comment]
Hi!

Thanks for this bug report.

I’ve tried to render the HTML sample you’ve given, but I can’t reproduce this bug. Here’s some Python code that should correspond to your issue:

```python
from weasyprint import HTML
HTML(string='<h3 style="display: inline-block;"> Some title\u2028</h3>').write_pdf()
```

Does it crash for you?

**Comment by liZe** [comment]
It’s now fixed and tested!
