### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file

### ISSUE THREAD

**Issue by braggpeaks** [Kozea/WeasyPrint#1901]
Once I use the `--dpi` parameter, I get this error. Is there a simple way to see which image is affected so that I can check?

System: Windows
Machine: AMD64
Version: 10.0.19044
Release: 10

WeasyPrint version: 59.0
Python version: 3.8.10
Pydyf version: 0.6.0
Pango version: 15003

```
INFO: Step 6 - Creating PDF
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\__main__.py", line 214, in <module>
    main()
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\__main__.py", line 207, in main
    html.write_pdf(output, **options)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\__init__.py", line 252, in write_pdf
    self.render(font_config, counter_style, **options)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\document.py", line 399, in write_pdf
    pdf = generate_pdf(self, target, zoom, **options)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\pdf\__init__.py", line 185, in generate_pdf
    page.paint(stream, scale=scale)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\document.py", line 103, in paint
    draw_page(self._page_box, stream)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\draw.py", line 68, in draw_page
    draw_stacking_context(stream, stacking_context)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\draw.py", line 176, in draw_stacking_context
    draw_stacking_context(stream, child_context)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\draw.py", line 148, in draw_stacking_context
    draw_box_background_and_border(
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\draw.py", line 75, in draw_box_background_and_border
    draw_background(stream, box.background)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\draw.py", line 337, in draw_background
    draw_background_image(stream, layer, bg.image_rendering)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\draw.py", line 397, in draw_background_image
    layer.image.draw(group, image_width, image_height, image_rendering)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\images.py", line 106, in draw
    image_name = stream.add_image(self, width, height, interpolate, ratio)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\weasyprint\pdf\stream.py", line 373, in add_image
    thumbnail = Image.open(io.BytesIO(image.image_data.data))
  File "C:\Program Files\Python38\lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000025682754A90>
```

**Comment by liZe** [comment]
Hi!

Thanks for your bug report. I think that it’s a duplicate of #1877. The [images branch](https://github.com/Kozea/WeasyPrint/tree/images) includes a fix for this problem, as long as you don’t use different `image-rendering` values. Could you try it and check that it fixes your problem?

**Comment by braggpeaks** [comment]
Hi. I am sorry for not checking properly for duplicates. I can confirm it is a duplicate and the images branch fixes the problem. Now I also know what to look for.

**Comment by liZe** [comment]
> Hi. I am sorry for not checking properly for duplicates.

No problem!

We’ll fix the `image-rendering` problem and merge the branch as soon as we can. Stay tuned!
