### ISSUE TITLE
Weird bug with WeasyPrint 60.0

### ISSUE THREAD

**Issue by kesara** [Kozea/WeasyPrint#1973]
This is a weird bug because this happens when certain conditions are met.
This is the bare minimum, that I could construct to replicate the bug.
Sample HTML:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>WeasyPrint test</title>
    <style>
      p {float: left;}
    </style>
  </head>
  <body>
    <p>foobar</p>
    <pre>€
    </pre>
  </body>
</html>
```

Error:
```
$ weasyprint --version
WeasyPrint version 60.0

$ weasyprint -d -v test-wp.html test-wp.pdf
INFO: Step 1 - Fetching and parsing HTML - test-wp.html
INFO: Step 2 - Fetching and parsing CSS - CSS string
INFO: Step 3 - Applying CSS
INFO: Step 4 - Creating formatting structure
INFO: Step 5 - Creating layout - Page 1
Traceback (most recent call last):
  File "/Users/kesara/lab/xml2rfc/venv/bin/weasyprint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/__main__.py", line 216, in main
    html.write_pdf(output, **options)
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/__init__.py", line 252, in write_pdf
    self.render(font_config, counter_style, **options)
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/__init__.py", line 209, in render
    return Document._render(self, font_config, counter_style, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/document.py", line 270, in _render
    [Page(page_box) for page_box in page_boxes],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/document.py", line 270, in <listcomp>
    [Page(page_box) for page_box in page_boxes],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/__init__.py", line 130, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/page.py", line 912, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/page.py", line 848, in remake_page
    page, resume_at, next_page = make_page(
                                 ^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/page.py", line 646, in make_page
    root_box, resume_at, next_page, _, _, _ = block_level_layout(
                                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 59, in block_level_layout
    return block_level_layout_switch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 75, in block_level_layout_switch
    return block_box_layout(
           ^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 120, in block_box_layout
    result = block_container_layout(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 693, in block_container_layout
    next_page, new_children, new_max_lines) = _in_flow_layout(
                                              ^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 486, in _in_flow_layout
    collapsing_through, max_lines) = block_level_layout(
                                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 59, in block_level_layout
    return block_level_layout_switch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 75, in block_level_layout_switch
    return block_box_layout(
           ^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 120, in block_box_layout
    result = block_container_layout(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 693, in block_container_layout
    next_page, new_children, new_max_lines) = _in_flow_layout(
                                              ^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 486, in _in_flow_layout
    collapsing_through, max_lines) = block_level_layout(
                                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 59, in block_level_layout
    return block_level_layout_switch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 75, in block_level_layout_switch
    return block_box_layout(
           ^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 120, in block_box_layout
    result = block_container_layout(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 682, in block_container_layout
    new_footnotes, max_lines) = _linebox_layout(
                                ^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/block.py", line 323, in _linebox_layout
    for i, (line, resume_at) in enumerate(lines_iterator):
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/inline.py", line 38, in iter_line_boxes
    line, resume_at = get_next_linebox(
                      ^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/inline.py", line 68, in get_next_linebox
    linebox.width = inline_min_content_width(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/preferred.py", line 200, in inline_min_content_width
    width = next(widths) if first_line else max(widths)
            ^^^^^^^^^^^^
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.11/site-packages/weasyprint/layout/preferred.py", line 312, in inline_line_widths
    child_text[resume_index:].decode(), child.style,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 0: invalid start byte
```

This seemed to be caused by https://github.com/Kozea/WeasyPrint/commit/0a03e3d1cf557541a7937f8603821a868c5302fe

**Comment by Stanislasss** [comment]
Same here with:
```
chemocompile-documentation-wiki-1  | INFO:weasyprint.progress:Step 5 - Creating layout - Page 4
chemocompile-documentation-wiki-1  | Traceback (most recent call last):
chemocompile-documentation-wiki-1  |   File "/usr/local/bin/mkdocs", line 8, in <module>
chemocompile-documentation-wiki-1  |     sys.exit(cli())
chemocompile-documentation-wiki-1  |              ^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
chemocompile-documentation-wiki-1  |     return self.main(*args, **kwargs)
chemocompile-documentation-wiki-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
chemocompile-documentation-wiki-1  |     rv = self.invoke(ctx)
chemocompile-documentation-wiki-1  |          ^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
chemocompile-documentation-wiki-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
chemocompile-documentation-wiki-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
chemocompile-documentation-wiki-1  |     return ctx.invoke(self.callback, **ctx.params)
chemocompile-documentation-wiki-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
chemocompile-documentation-wiki-1  |     return __callback(*args, **kwargs)
chemocompile-documentation-wiki-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 270, in serve_command
chemocompile-documentation-wiki-1  |     serve.serve(**kwargs)
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 86, in serve
chemocompile-documentation-wiki-1  |     builder(config)
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
chemocompile-documentation-wiki-1  |     build(config, live_server=None if is_clean else server, dirty=is_dirty)
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 354, in build
chemocompile-documentation-wiki-1  |     config.plugins.on_post_build(config=config)
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 542, in on_post_build
chemocompile-documentation-wiki-1  |     return self.run_event('post_build', config=config)
chemocompile-documentation-wiki-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 509, in run_event
chemocompile-documentation-wiki-1  |     result = method(**kwargs)
chemocompile-documentation-wiki-1  |              ^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/mkdocs_with_pdf/plugin.py", line 135, in on_post_build
chemocompile-documentation-wiki-1  |     self.generator.on_post_build(config, self.config['output_path'])
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/mkdocs_with_pdf/generator.py", line 151, in on_post_build
chemocompile-documentation-wiki-1  |     render = html.render()
chemocompile-documentation-wiki-1  |              ^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/__init__.py", line 209, in render
chemocompile-documentation-wiki-1  |     return Document._render(self, font_config, counter_style, options)
chemocompile-documentation-wiki-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/document.py", line 270, in _render
chemocompile-documentation-wiki-1  |     [Page(page_box) for page_box in page_boxes],
chemocompile-documentation-wiki-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/document.py", line 270, in <listcomp>
chemocompile-documentation-wiki-1  |     [Page(page_box) for page_box in page_boxes],
chemocompile-documentation-wiki-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/__init__.py", line 130, in layout_document
chemocompile-documentation-wiki-1  |     pages = list(make_all_pages(context, root_box, html, pages))
chemocompile-documentation-wiki-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/page.py", line 912, in make_all_pages
chemocompile-documentation-wiki-1  |     page, resume_at = remake_page(i, context, root_box, html)
chemocompile-documentation-wiki-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/page.py", line 848, in remake_page
chemocompile-documentation-wiki-1  |     page, resume_at, next_page = make_page(
chemocompile-documentation-wiki-1  |                                  ^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/page.py", line 646, in make_page
chemocompile-documentation-wiki-1  |     root_box, resume_at, next_page, _, _, _ = block_level_layout(
chemocompile-documentation-wiki-1  |                                               ^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 59, in block_level_layout
chemocompile-documentation-wiki-1  |     return block_level_layout_switch(
chemocompile-documentation-wiki-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 75, in block_level_layout_switch
chemocompile-documentation-wiki-1  |     return block_box_layout(
chemocompile-documentation-wiki-1  |            ^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 120, in block_box_layout
chemocompile-documentation-wiki-1  |     result = block_container_layout(
chemocompile-documentation-wiki-1  |              ^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 693, in block_container_layout
chemocompile-documentation-wiki-1  |     next_page, new_children, new_max_lines) = _in_flow_layout(
chemocompile-documentation-wiki-1  |                                               ^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 486, in _in_flow_layout
chemocompile-documentation-wiki-1  |     collapsing_through, max_lines) = block_level_layout(
chemocompile-documentation-wiki-1  |                                      ^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 59, in block_level_layout
chemocompile-documentation-wiki-1  |     return block_level_layout_switch(
chemocompile-documentation-wiki-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 75, in block_level_layout_switch
chemocompile-documentation-wiki-1  |     return block_box_layout(
chemocompile-documentation-wiki-1  |            ^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 120, in block_box_layout
chemocompile-documentation-wiki-1  |     result = block_container_layout(
chemocompile-documentation-wiki-1  |              ^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 693, in block_container_layout
chemocompile-documentation-wiki-1  |     next_page, new_children, new_max_lines) = _in_flow_layout(
chemocompile-documentation-wiki-1  |                                               ^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 486, in _in_flow_layout
chemocompile-documentation-wiki-1  |     collapsing_through, max_lines) = block_level_layout(
chemocompile-documentation-wiki-1  |                                      ^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 59, in block_level_layout
chemocompile-documentation-wiki-1  |     return block_level_layout_switch(
chemocompile-documentation-wiki-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 75, in block_level_layout_switch
chemocompile-documentation-wiki-1  |     return block_box_layout(
chemocompile-documentation-wiki-1  |            ^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 120, in block_box_layout
chemocompile-documentation-wiki-1  |     result = block_container_layout(
chemocompile-documentation-wiki-1  |              ^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 693, in block_container_layout
chemocompile-documentation-wiki-1  |     next_page, new_children, new_max_lines) = _in_flow_layout(
chemocompile-documentation-wiki-1  |                                               ^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 486, in _in_flow_layout
chemocompile-documentation-wiki-1  |     collapsing_through, max_lines) = block_level_layout(
chemocompile-documentation-wiki-1  |                                      ^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 59, in block_level_layout
chemocompile-documentation-wiki-1  |     return block_level_layout_switch(
chemocompile-documentation-wiki-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 75, in block_level_layout_switch
chemocompile-documentation-wiki-1  |     return block_box_layout(
chemocompile-documentation-wiki-1  |            ^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 120, in block_box_layout
chemocompile-documentation-wiki-1  |     result = block_container_layout(
chemocompile-documentation-wiki-1  |              ^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 682, in block_container_layout
chemocompile-documentation-wiki-1  |     new_footnotes, max_lines) = _linebox_layout(
chemocompile-documentation-wiki-1  |                                 ^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/block.py", line 323, in _linebox_layout
chemocompile-documentation-wiki-1  |     for i, (line, resume_at) in enumerate(lines_iterator):
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/inline.py", line 38, in iter_line_boxes
chemocompile-documentation-wiki-1  |     line, resume_at = get_next_linebox(
chemocompile-documentation-wiki-1  |                       ^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/inline.py", line 68, in get_next_linebox
chemocompile-documentation-wiki-1  |     linebox.width = inline_min_content_width(
chemocompile-documentation-wiki-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/preferred.py", line 200, in inline_min_content_width
chemocompile-documentation-wiki-1  |     width = next(widths) if first_line else max(widths)
chemocompile-documentation-wiki-1  |             ^^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/preferred.py", line 283, in inline_line_widths
chemocompile-documentation-wiki-1  |     lines = [next(lines)]
chemocompile-documentation-wiki-1  |              ^^^^^^^^^^^
chemocompile-documentation-wiki-1  |   File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/preferred.py", line 312, in inline_line_widths
chemocompile-documentation-wiki-1  |     child_text[resume_index:].decode(), child.style,
chemocompile-documentation-wiki-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chemocompile-documentation-wiki-1  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
```
Up to 59 we had no issue.

**Comment by liZe** [comment]
Thanks a lot for the stacktraces and the small snippet, it really helped!

@kesara @Stanislasss Does the fix work for you?

**Comment by kesara** [comment]
@liZe that fix is working. Thank you for the quick response.

**Comment by Stanislasss** [comment]
Thank you for the support.
Then we will wait until integration in the next version before upgrading :wink:

**Comment by liZe** [comment]
Version 60.1 has been fixed, thanks a lot for the detailed report!
