### ISSUE TITLE
Crash with IndexError: list index out of range

### ISSUE THREAD

**Issue by j123b567** [Kozea/WeasyPrint#1992]
I'm experiencing this strange error with version 60.1 and python 3.11.5

I'm not able to create a more minimal example, because every time I delete a single character from the html, the build does not crash.
It seems that `skip_first_whitespace` has a long history of similar bugs.

fail.html
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <style>
        table.docutils td, table.docutils th {
            padding: .75rem;
        }
        .sd-tab-set {
            display: flex;
        }
        .sd-tab-set > input:checked + label + .sd-tab-content {
            display: block
        }
        .sd-tab-content {
            order: 99;
        }
    </style>
</head>
<body>
<div class="sd-tab-set docutils">
    <input checked="checked" id="sd-tab-item-5" name="sd-tab-set-3" type="radio"/>
    <label class="sd-tab-label" for="sd-tab-item-5">aaaaa</label>
    <div class="sd-tab-content docutils">
        <div class="sd-tab-set docutils">
            <div class="sd-tab-content docutils">
                <table class="docutils align-default">
                    <thead>
                    <tr class="row-odd">
                        <th class="head"><p>a</p></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr class="row-even">
                        <td><p>a</p></td>
                    </tr>
                    <tr class="row-odd">
                        <td><p>a</p></td>
                    </tr>
                    <tr class="row-even">
                        <td><p>a</p></td>
                    </tr>
                    <tr class="row-odd">
                        <td><p>a</p></td>
                    </tr>
                    <tr class="row-even">
                        <td><p>a</p></td>
                    </tr>
                    <tr class="row-odd">
                        <td><p>a</p></td>
                    </tr>
                    <tr class="row-even">
                        <td><p>a</p></td>
                    </tr>
                    </tbody>
                </table>
                <table class="docutils">
                    <thead>
                    <tr class="row-odd">
                        <th class="head"><p>aaaaaaaaaaaaaaaa</p></th>
                        <th class="head"></th>
                        <th class="head"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr class="row-even">
                        <td></td>
                        <td><p> aaaaaaaaaaaaaaaaaaa </p></td>
                        <td><p> aaaaaaaaaaaa aa </p></td>
                    </tr>
                    <tr class="row-odd">
                        <td></td>
                        <td><p> aaaaaaaaaaaa aa </p></td>
                        <td><p> aaaaaaaaaaaa aa </p></td>
                    </tr>
                    <tr class="row-even">
                        <td></td>
                        <td><p> aaaaaaaaaaaa aa </p></td>
                        <td><p> aaaaaaaaaaaa aa </p></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <input id="sd-tab-item-6" name="sd-tab-set-3" type="radio"/>
    <label class="sd-tab-label" for="sd-tab-item-6"></label>
</div>
</body>
</html>
```

Stack trace:
```python
$ weasyprint fail.html fail.pdf
Traceback (most recent call last):
  File "bin/weasyprint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "lib/python3.11/site-packages/weasyprint/__main__.py", line 216, in main
    html.write_pdf(output, **options)
  File "lib/python3.11/site-packages/weasyprint/__init__.py", line 252, in write_pdf
    self.render(font_config, counter_style, **options)
  File "lib/python3.11/site-packages/weasyprint/__init__.py", line 209, in render
    return Document._render(self, font_config, counter_style, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/document.py", line 270, in _render
    [Page(page_box) for page_box in page_boxes],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/document.py", line 270, in <listcomp>
    [Page(page_box) for page_box in page_boxes],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/__init__.py", line 130, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/page.py", line 912, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/page.py", line 848, in remake_page
    page, resume_at, next_page = make_page(
                                 ^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/page.py", line 646, in make_page
    root_box, resume_at, next_page, _, _, _ = block_level_layout(
                                              ^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 59, in block_level_layout
    return block_level_layout_switch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 75, in block_level_layout_switch
    return block_box_layout(
           ^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 120, in block_box_layout
    result = block_container_layout(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 693, in block_container_layout
    next_page, new_children, new_max_lines) = _in_flow_layout(
                                              ^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 486, in _in_flow_layout
    collapsing_through, max_lines) = block_level_layout(
                                     ^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 59, in block_level_layout
    return block_level_layout_switch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 75, in block_level_layout_switch
    return block_box_layout(
           ^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 120, in block_box_layout
    result = block_container_layout(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 693, in block_container_layout
    next_page, new_children, new_max_lines) = _in_flow_layout(
                                              ^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 486, in _in_flow_layout
    collapsing_through, max_lines) = block_level_layout(
                                     ^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 59, in block_level_layout
    return block_level_layout_switch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 82, in block_level_layout_switch
    result = flex_layout(
             ^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/flex.py", line 454, in flex_layout
    block.block_level_layout_switch(
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 75, in block_level_layout_switch
    return block_box_layout(
           ^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 120, in block_box_layout
    result = block_container_layout(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 682, in block_container_layout
    new_footnotes, max_lines) = _linebox_layout(
                                ^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/block.py", line 323, in _linebox_layout
    for i, (line, resume_at) in enumerate(lines_iterator):
  File "lib/python3.11/site-packages/weasyprint/layout/inline.py", line 38, in iter_line_boxes
    line, resume_at = get_next_linebox(
                      ^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/inline.py", line 58, in get_next_linebox
    skip_stack = skip_first_whitespace(linebox, skip_stack)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/inline.py", line 209, in skip_first_whitespace
    result = skip_first_whitespace(box.children[index], next_skip_stack)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/weasyprint/layout/inline.py", line 209, in skip_first_whitespace
    result = skip_first_whitespace(box.children[index], next_skip_stack)
                                   ~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
```

**Comment by j123b567** [comment]
So fast fix! Thank you.
