### ISSUE TITLE
Crash 'NoneType' object has no attribute 'getBestCmap'

### ISSUE THREAD

**Issue by pothos** [Kozea/WeasyPrint#2065]
I ran into this on a Fedora 39 - not sure if this is due to fonts changing or due to a library update.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.12/site-packages/weasyprint/__init__.py", line 252, in write_pdf
    self.render(font_config, counter_style, **options)
  File "/usr/lib/python3.12/site-packages/weasyprint/document.py", line 399, in write_pdf
    pdf = generate_pdf(self, target, zoom, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/weasyprint/pdf/__init__.py", line 268, in generate_pdf
    pdf_fonts = build_fonts_dictionary(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/weasyprint/pdf/fonts.py", line 47, in build_fonts_dictionary
    for letter, key in font.ttfont.getBestCmap().items():
                       ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'getBestCmap'
```

My workaround is to add this in `weasyprint/pdf/fonts.py` but I'm sure it's not the correct thing to do:
```
        else:
            # Store width and Unicode map for all glyphs
            font_widths, cmap = {}, {}
            if font.ttfont is None: # ←
                continue # ←
```

**Comment by liZe** [comment]
Hi!

Thanks for this report.

This bug can happen when Fonttools can’t read the font. I’m curious about the PDF you get. Could you please share your PDF (with your "fix") and the font causing the problem?

(You can also try to update Fonttools and see if it fixes the problem.)

**Comment by pothos** [comment]
I updated fontconfig and can't reproduce anymore
