### ISSUE TITLE
Weasyprint (61.2) broken on Mac (12.7.4), Python 3.12, Homebrew

### ISSUE THREAD

**Issue by minthemiddle** [Kozea/WeasyPrint#2112]
Out of the blue, Weasyprint (61.2) does not work any longer on Mac (12.7.4), Python 3.12, Homebrew.
 I tried with Homebrew, pip, rye. 
 I tried to run Weasyprint from multiple folders.
All break.
 (Pango 1.52 is installed)
 
 ``` 
 weasyprint --info

-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

-----

Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 5, in <module>
    from weasyprint.__main__ import main
  File "/usr/local/Cellar/weasyprint/61.2/libexec/lib/python3.12/site-packages/weasyprint/__init__.py", line 419, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/weasyprint/61.2/libexec/lib/python3.12/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from .computed_values import COMPUTER_FUNCTIONS
  File "/usr/local/Cellar/weasyprint/61.2/libexec/lib/python3.12/site-packages/weasyprint/css/computed_values.py", line 9, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "/usr/local/Cellar/weasyprint/61.2/libexec/lib/python3.12/site-packages/weasyprint/text/ffi.py", line 428, in <module>
    gobject = _dlopen(
              ^^^^^^^^
  File "/usr/local/Cellar/weasyprint/61.2/libexec/lib/python3.12/site-packages/weasyprint/text/ffi.py", line 417, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/weasyprint/61.2/libexec/lib/python3.12/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/weasyprint/61.2/libexec/lib/python3.12/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/weasyprint/61.2/libexec/lib/python3.12/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: '/usr/local/lib/gobject-2.0-0' (no such file), 'gobject-2.0-0' (no such file), '/usr/local/lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file), '/Users/XXX/Desktop/gobject-2.0-0' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```

```
which weasyprint
/usr/local/bin/weasyprint
 ~ brew info weasyprint
==> weasyprint: stable 61.2 (bottled)
Convert HTML to PDF
https://www.courtbouillon.org/weasyprint
/usr/local/Cellar/weasyprint/61.2 (677 files, 15.1MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-03-30 at 13:10:26
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/w/weasyprint.rb
License: BSD-3-Clause
==> Dependencies
Required: pango ✔, pillow ✔, python@3.12 ✔
```

**Comment by minthemiddle** [comment]
Likely to the new version of Weasyprint that Homebrew uses.
On another machine, weasyprint works still (60.2).

```
 weasyprint --info
System: Darwin
Machine: arm64
Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112
Release: 23.3.0

WeasyPrint version: 60.2
Python version: 3.11.6
Pydyf version: 0.8.0
Pango version: 15014
 ~  ↱ main ±✚  brew info weasyprint
==> weasyprint: stable 60.1 (bottled)
Convert HTML to PDF
https://www.courtbouillon.org/weasyprint
/opt/homebrew/Cellar/weasyprint/60.1_1 (258 files, 8MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-01-08 at 12:09:27
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/w/weasyprint.rb
License: BSD-3-Clause
==> Dependencies
Required: cffi ✔, fonttools ✔, pango ✔, pillow ✔, python@3.12 ✔, six ✘
```

**Comment by minthemiddle** [comment]
Or not, I tried with a virtualenv on the original machine:

- `python3 -m venv venv`
- `source venv/bin/activate`
- `pip install WeasyPrint==60.2`
- `which weasyprint` > /Users/XXX/venv/bin/weasyprint
- Run script
- Get same error as before

```
./scripts/script.sh
Traceback (most recent call last):
  File "/Users/martinbetz/Technical/venv/bin/weasyprint", line 5, in <module>
    from weasyprint.__main__ import main
  File "/Users/martinbetz/Technical/venv/lib/python3.12/site-packages/weasyprint/__init__.py", line 387, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinbetz/Technical/venv/lib/python3.12/site-packages/weasyprint/css/__init__.py", line 25, in <module>
    from . import computed_values, counters, media_queries
  File "/Users/martinbetz/Technical/venv/lib/python3.12/site-packages/weasyprint/css/computed_values.py", line 11, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "/Users/martinbetz/Technical/venv/lib/python3.12/site-packages/weasyprint/text/ffi.py", line 428, in <module>
    gobject = _dlopen(
              ^^^^^^^^
  File "/Users/martinbetz/Technical/venv/lib/python3.12/site-packages/weasyprint/text/ffi.py", line 417, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinbetz/Technical/venv/lib/python3.12/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinbetz/Technical/venv/lib/python3.12/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinbetz/Technical/venv/lib/python3.12/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/usr/local/lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file), '/Users/XXX/gobject-2.0-0' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
Error producing PDF.

-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

-----
```

**Comment by minthemiddle** [comment]
Possibly due to Python3.12 vs Python3.11, I'm investigating.

**Comment by minthemiddle** [comment]
Actually, it was `glib` that was installed but not properly linked:

```
brew install glib
Warning: glib 2.80.0_2 is already installed, it's just not linked.
To link this version, run:
  brew link glib
 ~   main ±  brew link glib
Linking /usr/local/Cellar/glib/2.80.0_2... 178 symlinks created.
 ~   main ±  weasyprint --info
System: Darwin
Machine: x86_64
Version: Darwin Kernel Version 21.6.0: Mon Feb 19 20:24:34 PST 2024; root:xnu-8020.240.18.707.4~1/RELEASE_X86_64
Release: 21.6.0

WeasyPrint version: 61.2
Python version: 3.12.2
Pydyf version: 0.9.0
Pango version: 15201
```

**Comment by roope-kvp** [comment]
minthemiddle's fix did not work for me.  glib was already linked.

I first pip-installed weasyprint and got the same error "OSError: cannot load library 'gobject-2.0-0'" etc
Then I pip-unistalled weasyprint and installed with homebrew -> same error

Then:
brew link glib
Warning: Already linked: /opt/homebrew/Cellar/glib/2.80.0_2
To relink, run:
  brew unlink glib && brew link glib

Then:
brew unlink glib && brew link glib
Unlinking /opt/homebrew/Cellar/glib/2.80.0_2... 174 symlinks removed.
Linking /opt/homebrew/Cellar/glib/2.80.0_2... 174 symlinks created.

Then again:
weasyprint --info                 
WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:

**Comment by stephane** [comment]
With Rye, the extract of my call trace is similar:

```
.../.venv/lib/python3.12/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file), '/usr/local/lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```

Until now I was using weasyprint in a virtualenv managed by Poetry and using a Python package provided by my system (via brew). The problem occured since I switched the concerned project to Rye <https://rye-up.com/>.

To understand how Python searches the system libraries I read the source code of `find_library`, the interesting part is how it calls <https://github.com/python/cpython/blob/main/Lib/ctypes/macholib/dyld.py#L99>, so I was able to workaround the issue by creating a symlink `ln -s /Users/<user>/lib /opt/homebrew/lib`.

Not really a clean solution BTW so I also tried an alternative solution by setting `export DYLD_FALLBACK_LIBRARY_PATH="/opt/homebrew/lib"` in the `.venv/bin/activate` script of my venv but without success until now.

**Comment by Aximande** [comment]
does anyone has managed to make it work ?

i'm on python 3.11 in my virtual env, with mac M1 and macOS 14.1.1 (somona)

and i have this same issue as you guys....

**Comment by liZe** [comment]
> does anyone has managed to make it work ?

WeasyPrint is packaged with Homebrew, it should work if you create your virtual environment with Homebrew’s Python.

If it doesn’t solve your problem, could you please open a new issue?
