### ISSUE TITLE
Font rendered weirdly when using certain font

### ISSUE THREAD

**Issue by kimwonj77** [Kozea/WeasyPrint#2180]
Somehow, Certain font rendered weirdly, that makes 

```
from weasyprint import HTML

html_content = """
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Report</title>
    <style>
        @font-face {
          font-family: "Pretendard";
          src: local("PretendardVariable"), url("./fonts/PretendardVariable.ttf") format("truetype");
        }

        html {
            font-family: "Pretendard", sans-serif;
        }
    </style>
</head>
<body>

<div class="container">
    <p>Hello, World--!</p>
    <p>Test(1, 2, 3)</p>
</div>

</body>
</html>

"""

HTML(string=html_content, base_url=".").write_pdf("output.pdf", full_fonts=True, hinting=True, presentational_hints=True)
```

Adobe acrobat reader:
![image](https://github.com/Kozea/WeasyPrint/assets/95566897/e10c5967-8dce-4449-8028-30e5c4ae3d69)

Chrome viewer:
![image](https://github.com/Kozea/WeasyPrint/assets/95566897/f4699dda-f900-4819-9af0-01340bd49df7)

The font what i'm using is [`Pretendard`](https://github.com/orioncactus/pretendard/blob/main/packages/pretendard/docs/en/README.md).
I don't know this is issue of font or Weasyprint. Since it's rendered correctly on Web and other files, I'm repoting here.

**Comment by liZe** [comment]
Hi!

Here’s the PDF I get. It’s rendered correctly in all PDF readers I tested, including Adobe Reader.

Maybe there’s a font mismatch between 2 different Pretendard fonts, one installed on your system and one configured by the `@font-face` rule?

**Comment by kimwonj77** [comment]
I removed local font and no luck. (using Pretendard 1.3.9)

Additionally, I'm using Windows, So maybe older GTK(pango) has a problem...

**Comment by kimwonj77** [comment]
Still no luck, I tried to use msys2's pango(`1.54.0` instead of Windows GTK Runtime's `1.50.4`)  and still got same issue.
Using font `Pretendard 1.3.9/static/variable/PretendardVariable.ttf` or each variant outs same result.

```
@font-face {
  font-family: "Pretendard";
  src: url("./fonts/PretendardVariable.ttf") format("truetype");
}
```
or
```
@font-face {
  font-family: "Pretendard";
  font-weight: 900;
  font-display: swap;
  src: url(./fonts/Pretendard/Pretendard-Black.woff2) format("woff2");
}

@font-face {
  font-family: "Pretendard";
  font-weight: 800;
  font-display: swap;
  src: url(./fonts/Pretendard/Pretendard-ExtraBold.woff2) format("woff2");
}

@font-face {
  font-family: "Pretendard";
  font-weight: 700;
  font-display: swap;
  src: url(./fonts/Pretendard/Pretendard-Bold.woff2) format("woff2");
}

@font-face {
  font-family: "Pretendard";
  font-weight: 600;
  font-display: swap;
  src: url(./fonts/Pretendard/Pretendard-SemiBold.woff2) format("woff2");
}

@font-face {
  font-family: "Pretendard";
  font-weight: 500;
  font-display: swap;
  src: url(./fonts/Pretendard/Pretendard-Medium.woff2) format("woff2");
}

@font-face {
  font-family: "Pretendard";
  font-weight: 400;
  font-display: swap;
  src: url(./fonts/Pretendard/Pretendard-Regular.woff2) format("woff2");
}

@font-face {
  font-family: "Pretendard";
  font-weight: 300;
  font-display: swap;
  src: url(./fonts/Pretendard/Pretendard-Light.woff2) format("woff2");
}

@font-face {
  font-family: "Pretendard";
  font-weight: 200;
  font-display: swap;
  src: url(./fonts/Pretendard/Pretendard-ExtraLight.woff2) format("woff2");
}

@font-face {
  font-family: "Pretendard";
  font-weight: 100;
  font-display: swap;
  src: url(./fonts/Pretendard/Pretendard-Thin.woff2) format("woff2");
}
```

**Comment by liZe** [comment]
Could you please share your PDF, and the result of `weasyprint --info`?

**Comment by kimwonj77** [comment]
[output.pdf](https://github.com/user-attachments/files/15802563/output.pdf)
```
System: Windows
Machine: AMD64
Version: 10.0.22631
Release: 11

WeasyPrint version: 62.2
Python version: 3.12.2
Pydyf version: 0.10.0
Pango version: 15003
```
Here is.

**Comment by liZe** [comment]
I don’t know why this problem appears for you, I can’t reproduce…

Could you please try using a totally different `font-family` (something like `aaaaaa`), so that we’re sure that it’s not using another font installed somewhere on your system?

**Comment by kimwonj77** [comment]
I uninstalled the locally installed Pretendard fonts, and it works fine now. It appears that the local font was being loaded incorrectly. I configured it not to use those fonts, but it seems to have been ignored.

```
        @font-face {
          font-family: "Pretendard";
          src: url("./fonts/PretendardVariable.ttf") format("truetype");
        }
```
This is my current configuration.

**Comment by kimwonj77** [comment]
Another issue is the incorrect rendering of character width with a hyphen between normal characters.
![image](https://github.com/Kozea/WeasyPrint/assets/95566897/82f2c760-9423-4cf9-8c19-c3a01b6c424e)
```
from weasyprint import HTML

html_content = """
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Report</title>
    <style>
        @font-face {
          font-family: "Pretendard";
          src: url("./fonts/PretendardVariable.ttf") format("truetype");
        }

        html {
            font-family: "Pretendard", sans-serif;
        }
    </style>
</head>
<body>

<div class="container">
    <p>Hello, World--!</p>
    <p>Test(1, 2, 3)</p>
    <p>01-001-0001-1234</p>
</div>

</body>
</html>

"""

HTML(string=html_content, base_url=".").write_pdf("output.pdf", full_fonts=True, hinting=True, presentational_hints=True)
```

This occurs regardless of the font type used.

**Comment by liZe** [comment]
The bug only appears with the "full_fonts" options, that shouldn’t be used in most cases (and is really slow in your case). Do you need it?

**Comment by kimwonj77** [comment]
1. We saw that sometime font is not loaded correctly without full font.
2. Just for testing, I got some weird bug: `AttributeError: function/symbol 'hb_set_add_sorted_array' not found in library 'C:\Program Files\GTK3-Runtime Win64\bin\libharfbuzz-0.dll': error 0x7f` during write out...
```
Traceback (most recent call last):
  File "C:\Users\dyko\git\weasy-graph-report\test.py", line 37, in <module>
    HTML(string=html_content, base_url=".").write_pdf("output.pdf")
  File "C:\Users\dyko\git\weasy-graph-report\.venv\Lib\site-packages\weasyprint\__init__.py", line 259, in write_pdf
    self.render(font_config, counter_style, **options)
  File "C:\Users\dyko\git\weasy-graph-report\.venv\Lib\site-packages\weasyprint\document.py", line 404, in write_pdf
    pdf = generate_pdf(self, target, zoom, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dyko\git\weasy-graph-report\.venv\Lib\site-packages\weasyprint\pdf\__init__.py", line 270, in generate_pdf
    pdf_fonts = build_fonts_dictionary(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dyko\git\weasy-graph-report\.venv\Lib\site-packages\weasyprint\pdf\fonts.py", line 286, in build_fonts_dictionary
    font.clean(cmap, options['hinting'])
  File "C:\Users\dyko\git\weasy-graph-report\.venv\Lib\site-packages\weasyprint\pdf\fonts.py", line 112, in clean
    self.subset(cmap, hinting)
  File "C:\Users\dyko\git\weasy-graph-report\.venv\Lib\site-packages\weasyprint\pdf\fonts.py", line 184, in subset
    self._harfbuzz_subset(cmap, hinting)
  File "C:\Users\dyko\git\weasy-graph-report\.venv\Lib\site-packages\weasyprint\pdf\fonts.py", line 195, in _harfbuzz_subset
    harfbuzz.hb_set_add_sorted_array(gid_set, gid_array, len(cmap))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dyko\git\weasy-graph-report\.venv\Lib\site-packages\cffi\api.py", line 912, in __getattr__
    make_accessor(name)
  File "C:\Users\dyko\git\weasy-graph-report\.venv\Lib\site-packages\cffi\api.py", line 908, in make_accessor
    accessors[name](name)
  File "C:\Users\dyko\git\weasy-graph-report\.venv\Lib\site-packages\cffi\api.py", line 838, in accessor_function
    value = backendlib.load_function(BType, name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: function/symbol 'hb_set_add_sorted_array' not found in library 'C:\Program Files\GTK3-Runtime Win64\bin\libharfbuzz-0.dll': error 0x7f
```

**Comment by kimwonj77** [comment]
We observed that sometimes the font does not load correctly without the full font.
For testing purposes, I encountered a weird bug: `AttributeError: function/symbol 'hb_set_add_sorted_array' not found in library 'C:\Program Files\GTK3-Runtime Win64\bin\libharfbuzz-0.dll': error 0x7f`
```
Traceback (most recent call last):
  File "[redacted]\test.py", line 37, in <module>
    HTML(string=html_content, base_url=".").write_pdf("output.pdf")
  File "[redacted]\.venv\Lib\site-packages\weasyprint\__init__.py", line 259, in write_pdf
    self.render(font_config, counter_style, **options)
  File "[redacted]\.venv\Lib\site-packages\weasyprint\document.py", line 404, in write_pdf
    pdf = generate_pdf(self, target, zoom, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]\.venv\Lib\site-packages\weasyprint\pdf\__init__.py", line 270, in generate_pdf
    pdf_fonts = build_fonts_dictionary(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]\.venv\Lib\site-packages\weasyprint\pdf\fonts.py", line 286, in build_fonts_dictionary
    font.clean(cmap, options['hinting'])
  File "[redacted]\.venv\Lib\site-packages\weasyprint\pdf\fonts.py", line 112, in clean
    self.subset(cmap, hinting)
  File "[redacted]\.venv\Lib\site-packages\weasyprint\pdf\fonts.py", line 184, in subset
    self._harfbuzz_subset(cmap, hinting)
  File "[redacted]\.venv\Lib\site-packages\weasyprint\pdf\fonts.py", line 195, in _harfbuzz_subset
    harfbuzz.hb_set_add_sorted_array(gid_set, gid_array, len(cmap))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]\.venv\Lib\site-packages\cffi\api.py", line 912, in __getattr__
    make_accessor(name)
  File "[redacted]\.venv\Lib\site-packages\cffi\api.py", line 908, in make_accessor
    accessors[name](name)
  File "[redacted]\.venv\Lib\site-packages\cffi\api.py", line 838, in accessor_function
    value = backendlib.load_function(BType, name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: function/symbol 'hb_set_add_sorted_array' not found in library 'C:\Program Files\GTK3-Runtime Win64\bin\libharfbuzz-0.dll': error 0x7f
```

P.S. I deleted the previous comment that contained sensitive information.

**Comment by liZe** [comment]
OK, let’s try to stay focus!

We can keep this issue to talk about the spacing problem with full fonts.

> 1\. We observed that sometimes the font does not load correctly without the full font. (At 59.x)

There shouldn’t be any problem without the full font option. If you have a problem without full fonts, with version 62.2, please share your example in a new issue.

> 2\. For testing purposes, I encountered a weird bug: `AttributeError: function/symbol 'hb_set_add_sorted_array' not found in library 'C:\Program Files\GTK3-Runtime Win64\bin\libharfbuzz-0.dll': error 0x7f`

Please open a new issue for this.
