### ISSUE TITLE
unknown locale: UTF-8

### ISSUE THREAD

**Issue by GusMonod** [Kozea/WeasyPrint#219]
Hi! First of all, great idea, I'd love to see it working!

I just had a small problem after installing. Apparently the locale isn't set correctly. Do you have an idea of how to solve this? I am on a MacBook Air with a brand new Mavericks with nothing installed (except `brew` and `Xcode` I installed for this purpose).

Here is the [installation output](https://gist.github.com/GusMonod/66deb7e08f680db46cc6).
Here is the stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 9, in <module>
    load_entry_point('WeasyPrint==0.23', 'console_scripts', 'weasyprint')()
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 356, in load_entry_point
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 2476, in load_entry_point
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 2190, in load
  File "/usr/local/lib/python2.7/site-packages/weasyprint/__init__.py", line 336, in <module>
    from .css import PARSER, preprocess_stylesheet
  File "/usr/local/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 31, in <module>
    from .validation import preprocess_declarations
  File "/usr/local/lib/python2.7/site-packages/weasyprint/css/validation.py", line 26, in <module>
    from ..images import LinearGradient, RadialGradient
  File "/usr/local/lib/python2.7/site-packages/weasyprint/images.py", line 22, in <module>
    import cairosvg.parser
  File "/usr/local/lib/python2.7/site-packages/cairosvg/__init__.py", line 27, in <module>
    from . import surface
  File "/usr/local/lib/python2.7/site-packages/cairosvg/surface/__init__.py", line 32, in <module>
    from ..parser import Tree
  File "/usr/local/lib/python2.7/site-packages/cairosvg/parser.py", line 53, in <module>
    from .features import match_features
  File "/usr/local/lib/python2.7/site-packages/cairosvg/features.py", line 27, in <module>
    LOCALE = locale.getdefaultlocale()[0] or ""
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

**Comment by michaeleekk** [comment]
https://github.com/python/cpython/commit/b0caf329815120acf50287e29858093d328b0e3c

This is fixed in Python finally !
