### ISSUE TITLE
CSS: 'column-rule': size unit unhandled

### ISSUE THREAD

**Issue by sphakka** [Kozea/WeasyPrint#2217]
(Possibly related to old issue #60.) With Weasyprint v62.3 (latest as of now) on Linux, using `column-rule` chokes on size unit.

MWE:
```HTML
<!doctype html>
<html>
	<head>
		<title>Test CSS3 column-rule</title>
		<meta charset="utf-8" />
	</head>
	<style>
	 .two-columns {
		 columns: 2;
		 column-rule: 1px dotted gray;
	 }
	</style>
	<body>
		<div class="two-columns">
			<p>Foo bar</p>
			<p>Bar quux</p>
		</div>
	</body>
</html>
```
Command:
```shell
$ weasyprint test-col.html test-col.pdf
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/weasyprint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/weasyprint/__main__.py", line 183, in main
    html.write_pdf(output, **options)
  File "/usr/lib/python3.12/site-packages/weasyprint/__init__.py", line 259, in write_pdf
    self.render(font_config, counter_style, **options)
  File "/usr/lib/python3.12/site-packages/weasyprint/document.py", line 400, in write_pdf
    pdf = generate_pdf(self, target, zoom, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/weasyprint/pdf/__init__.py", line 190, in generate_pdf
    page.paint(stream, scale)
  File "/usr/lib/python3.12/site-packages/weasyprint/document.py", line 99, in paint
    draw_page(self._page_box, stream)
  File "/usr/lib/python3.12/site-packages/weasyprint/draw.py", line 67, in draw_page
    draw_stacking_context(stream, stacking_context)
  File "/usr/lib/python3.12/site-packages/weasyprint/draw.py", line 170, in draw_stacking_context
    draw_stacking_context(stream, child_context)
  File "/usr/lib/python3.12/site-packages/weasyprint/draw.py", line 144, in draw_stacking_context
    draw_border(stream, block)
  File "/usr/lib/python3.12/site-packages/weasyprint/draw.py", line 426, in draw_border
    gap = percentage(box.style['column_gap'], box.width)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/weasyprint/layout/percent.py", line 17, in percentage
    elif value.unit == 'px':
         ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'unit'
```

**Comment by liZe** [comment]
Thanks for the report! It’s been introduced by the grid layout support, for which the `column-gap` property has been adapted to follow the new [Box Alignment Module](https://drafts.csswg.org/css-align-3/#column-row-gap).
