### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'Dimension' and 'float'

### ISSUE THREAD

**Issue by amarsahinovic** [Kozea/WeasyPrint#225]
I can reproduce this error by running: `weasyprint http://foundation.zurb.com/docs/ out.pdf`
It also crashes on my other website (which also uses foundation) with the same error. There is also a bunch of parse errors before the exception is raised.

~~~
Traceback (most recent call last):
  File "/home/amar/.virtualenvs/weasyprinttest/bin/weasyprint", line 9, in <module>
    load_entry_point('WeasyPrint==0.23', 'console_scripts', 'weasyprint')()
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/__main__.py", line 156, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/__init__.py", line 164, in write_pdf
    return self.render(stylesheets).write_pdf(target, zoom, attachments)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/__init__.py", line 132, in render
    return Document._render(self, stylesheets, enable_hinting)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/document.py", line 319, in _render
    return cls([Page(p, enable_hinting) for p in page_boxes],
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/document.py", line 319, in <listcomp>
    return cls([Page(p, enable_hinting) for p in page_boxes],
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/__init__.py", line 50, in layout_document
    pages = list(make_all_pages(context, root_box))
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/pages.py", line 541, in make_all_pages
    context, root_box, page_type, resume_at, content_empty)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/pages.py", line 503, in make_page
    positioned_boxes, positioned_boxes, adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/blocks.py", line 321, in block_container_layout
    for line, resume_at in lines_iterator:
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/inlines.py", line 48, in iter_line_boxes
    device_size, absolute_boxes, fixed_boxes)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/layout/inlines.py", line 78, in get_next_linebox
    linebox.height, _ = strut_layout(linebox.style, context.enable_hinting)
  File "/home/amar/.virtualenvs/weasyprinttest/lib/python3.4/site-packages/weasyprint/css/computed_values.py", line 536, in strut_layout
    return value, baseline + (value - pango_height) / 2
TypeError: unsupported operand type(s) for -: 'Dimension' and 'float'
~~~

**Comment by liZe** [comment]
Simple example:

```
<style>body{line-height: 1rem;}</style>
<body>1
```

Looks like the unknown units break the computed values.

**Comment by SimonSapin** [comment]
This is wrong, unknow units should be rejected at parse time. See the `get_length()` function.
https://github.com/Kozea/WeasyPrint/blob/9249f8d33af7cc95eaea455eabaf4b615099105f/weasyprint/css/validation.py#L885-L887

**Comment by SimonSapin** [comment]
And note that in "validator" functions, returning `None` means that the declaration’s value is invalid for this property. (And so the declaration should be ignored.)

**Comment by liZe** [comment]
Oh, maybe the solution was to implement the rem unit?

**Comment by SimonSapin** [comment]
Implementing `rem` would be good, but that doesn’t change that `line-height: 1bazinga` should be rejected too.

**Comment by liZe** [comment]
(That was both a joke AND a hint if you don't know how to spend you next 15 minutes :p)

**Comment by halfnibble** [comment]
I'm confused. This error still occurs, and weasyprint crashes when using zurb foundation. Are you saying weasyprint will not support `rem` units at all?

**Comment by liZe** [comment]
> This error still occurs, and weasyprint crashes when using zurb foundation.

It looks like it's another error, I've opened a new ticket (#260).

> Are you saying weasyprint will not support rem units at all?

We are just saying that we didn't find the time to read the spec, write the code and make tests pass ;).
