### ISSUE TITLE
Install problems on Mac OS X Yosemite

### ISSUE THREAD

**Issue by diethardsteiner** [Kozea/WeasyPrint#235]
Hi,

I followed the instructions on your website. These are my steps:

```
brew install Caskroom/cask/xquartz
brew install gettext
brew install python cairo pango gdk-pixbuf libxml2 libxslt libffi
```

I get following error with the last command:

```
pip install WeasyPrint
Collecting WeasyPrint
  Downloading WeasyPrint-0.23.tar.gz (343kB)
    100% |################################| 344kB 2.4MB/s 
Collecting lxml>=3.0 (from WeasyPrint)
  Downloading lxml-3.4.2.tar.gz (3.5MB)
    100% |################################| 3.5MB 1.8MB/s 
    /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.4.2.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
Collecting html5lib>=0.999 (from WeasyPrint)
  Downloading html5lib-0.999.tar.gz (885kB)
    100% |################################| 888kB 2.6MB/s 
Collecting tinycss==0.3 (from WeasyPrint)
  Downloading tinycss-0.3.tar.gz (72kB)
    100% |################################| 73kB 2.3MB/s 
    Building without Cython.
Collecting cssselect>=0.6 (from WeasyPrint)
  Downloading cssselect-0.9.1.tar.gz
Collecting CairoSVG>=0.4.1 (from WeasyPrint)
  Downloading CairoSVG-1.0.10.tar.gz
Collecting cffi>=0.6 (from WeasyPrint)
  Downloading cffi-0.8.6.tar.gz (196kB)
    100% |################################| 200kB 2.8MB/s 
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/k1/wjgfzcv57sv2jrrtxyv5df_00000gn/T/pip-build-jkwvwh/cffi/setup.py", line 85, in <module>
        use_pkg_config()
      File "/var/folders/k1/wjgfzcv57sv2jrrtxyv5df_00000gn/T/pip-build-jkwvwh/cffi/setup.py", line 57, in use_pkg_config
        _ask_pkg_config(include_dirs,       '--cflags-only-I', '-I', sysroot=True)
      File "/var/folders/k1/wjgfzcv57sv2jrrtxyv5df_00000gn/T/pip-build-jkwvwh/cffi/setup.py", line 20, in _ask_pkg_config
        stdout=subprocess.PIPE)
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 20] Not a directory
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/var/folders/k1/wjgfzcv57sv2jrrtxyv5df_00000gn/T/pip-build-jkwvwh/cffi/setup.py", line 85, in <module>
    
        use_pkg_config()
    
      File "/var/folders/k1/wjgfzcv57sv2jrrtxyv5df_00000gn/T/pip-build-jkwvwh/cffi/setup.py", line 57, in use_pkg_config
    
        _ask_pkg_config(include_dirs,       '--cflags-only-I', '-I', sysroot=True)
    
      File "/var/folders/k1/wjgfzcv57sv2jrrtxyv5df_00000gn/T/pip-build-jkwvwh/cffi/setup.py", line 20, in _ask_pkg_config
    
        stdout=subprocess.PIPE)
    
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    
        errread, errwrite)
    
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    
        raise child_exception
    
    OSError: [Errno 20] Not a directory
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /var/folders/k1/wjgfzcv57sv2jrrtxyv5df_00000gn/T/pip-build-jkwvwh/cffi
```

Any ideas on how to resolve this?

**Comment by SimonSapin** [comment]
The problem seems to be when installing CFFI http://cffi.readthedocs.org/ (which WeasyPrint depends on), but I don’t know more than that.

**Comment by diethardsteiner** [comment]
Thanks a lot ... I take a look at this.

**Comment by diethardsteiner** [comment]
If somebody has the same problem, run:

```
brew install pkg-config libffi
PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig pip install cffi
```
