### ISSUE TITLE
Installing Weasyprint

### ISSUE THREAD

**Issue by richardjames27** [Kozea/WeasyPrint#244]
I've been trying to install Weasyprint and it doesn't work! I hope someone can help me.

Followed these to a T: http://weasyprint.org/docs/install/ using the mac install.

It seams cairo and pango won't properly install and I always receive this error when trying to run weasyprint: 

```
(venv)RichardMB:~ Richard$ weasyprint --help
Traceback (most recent call last):
  File "/Users/Richard/venv/bin/weasyprint", line 9, in <module>
    load_entry_point('WeasyPrint==0.23', 'console_scripts', 'weasyprint')()
  File "/Users/Richard/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/Richard/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/Users/Richard/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/Users/Richard/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/Richard/venv/lib/python2.7/site-packages/weasyprint/__init__.py", line 336, in <module>
    from .css import PARSER, preprocess_stylesheet
  File "/Users/Richard/venv/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 30, in <module>
    from . import computed_values
  File "/Users/Richard/venv/lib/python2.7/site-packages/weasyprint/css/computed_values.py", line 18, in <module>
    from .. import text
  File "/Users/Richard/venv/lib/python2.7/site-packages/weasyprint/text.py", line 204, in <module>
    'libgobject-2.0.dylib')
  File "/Users/Richard/venv/lib/python2.7/site-packages/weasyprint/text.py", line 200, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/Library/Python/2.7/site-packages/cffi/api.py", line 121, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Library/Python/2.7/site-packages/cffi/api.py", line 493, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Library/Python/2.7/site-packages/cffi/api.py", line 482, in _load_backend_lib
    return backend.load_library(name, flags)
OSError: cannot load library gobject-2.0: dlopen(gobject-2.0, 2): image not found
```

**Comment by SimonSapin** [comment]
Are you using Macports, Homebrew, or something else? What exact steps did you take to install the dependencies? Did you get any error message then?

I don’t use OS X myself, and this doesn’t seem like a bug in WeasyPrint’s own code. I’m afraid there is not much I can do to help here.

**Comment by richardjames27** [comment]
I've tried both Macports and Brew. No errors on installing the dependencies except for Pango and Cairo.

**Comment by SimonSapin** [comment]
So… you *did* get an error message? What was it? What exact steps did you take to install the dependencies?

**Comment by SimonSapin** [comment]
Look, I’m trying to help you (although this is really not a help forum), but you’ve got to provide as much information as possible. Ideally, exact steps to allow someone else reproduce the problem. Just saying “It doesn’t work” won’t get you anywhere.

**Comment by richardjames27** [comment]
I'm not sure where else to go other than here were the developers are working on this project.

Installed per the link I supplied above in a virtual environment:

virtualenv --system-site-packages ./venv
. ./venv/bin/activate
pip install WeasyPrint

When I try to run weasyprint:

$ weasyprint --help

I get the error output I pasted above.

I installed the dependencies by trying both the macports and brew using the following command lines...no errors were flipped.

sudo port install py27-pip py27-lxml cairo pango gdk-pixbuf2 libffi
brew install python cairo pango gdk-pixbuf libxml2 libxslt libffi

**Comment by liZe** [comment]
A similar error was reported on Solaris: #144. It was solved "by installing gobject-2.0 library".

**Comment by liZe** [comment]
@richardjames27 is the bug fixed now?

**Comment by richardjames27** [comment]
Yes it is!

Your suggestion worked perfectly! Thank you!

**Comment by liZe** [comment]
:)

**Comment by stachlewski** [comment]
Sorry to open old thread. How does one install gobject-2.0 on mac os? Tried to install gtk+ but this has not helped.

**Comment by jernejkase** [comment]
I'm getting the same error. Tried installing gtk+, pygobject etc.. nothing works. 

This is either a documentation bug (clearly the documented install process doesn't work), or hardcoded lib names in text.py line 227

**Comment by liZe** [comment]
> I'm getting the same error.

Could you please open a separate issue with information about your system and the error you get?
