### ISSUE TITLE
Can not create PDF

### ISSUE THREAD

**Issue by clarkk** [Kozea/WeasyPrint#281]
Debian Jessie

```
# apt-get install python-dev python-pip python-lxml libcairo2 libpango1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
# pip install WeasyPrint
# weasyprint http://weasyprint.org ./weasyprint-website.pdf
```

Error
```
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (cffi 0.8.6 (/usr/lib/python2.7/dist-packages), Requirement.parse('cffi>=1.1.0'))

```

**Comment by liZe** [comment]
The version of cffi installed on your system is 0.8.6 (probably installed a looong time ago). Just update it with `pip install --upgrade cffi`, and it should work!

I'll fix the line in `setup.py`.

**Comment by clarkk** [comment]
Seems to work now :)

**Comment by liZe** [comment]
Well, the needed `cffi>=1.1.0` comes from cairocffi and not from weasyprint, see https://github.com/SimonSapin/cairocffi/blob/master/setup.py.

There's probably a bug in the `requires_cffi` definition, allowing the installed cffi version to be enough when installing cairocffi but relying on 1.1.0+ at runtime.
