### ISSUE TITLE
UnicodeDecodeError when running html.write_pdf()

### ISSUE THREAD

**Issue by acouette** [Kozea/WeasyPrint#285]
Hello and thank you for the tool.

We are running validation tests on different sets of data. 
With one specific HTML : [input.txt](https://github.com/Kozea/WeasyPrint/files/64207/input.txt)
The PDF generation fails with the following error : 

```
ERROR:root:'utf-8' codec can't decode byte 0xc2 in position 1: unexpected end of data
Traceback (most recent call last):
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/PdfServer-0.1-py3.3.egg/fluidtopics/app.py", line 16, in generate_pdf
    return render_pdf(html, stylesheets=[CSS(file_obj=resource_stream(__name__, 'pdf-base-styles.css'))])
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/PdfServer-0.1-py3.3.egg/fluidtopics/app.py", line 22, in render_pdf
    pdf = html.write_pdf(stylesheets=stylesheets)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/__init__.py", line 164, in write_pdf
    return self.render(stylesheets).write_pdf(target, zoom, attachments)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/__init__.py", line 132, in render
    return Document._render(self, stylesheets, enable_hinting)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/document.py", line 322, in _render
    return cls([Page(p, enable_hinting) for p in page_boxes],
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/document.py", line 322, in <listcomp>
    return cls([Page(p, enable_hinting) for p in page_boxes],
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/__init__.py", line 51, in layout_document
    pages = list(make_all_pages(context, root_box))
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/pages.py", line 553, in make_all_pages
    page_number)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/pages.py", line 505, in make_page
    positioned_boxes, positioned_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 435, in block_container_layout
    adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 88, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/blocks.py", line 321, in block_container_layout
    for line, resume_at in lines_iterator:
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/inlines.py", line 48, in iter_line_boxes
    device_size, absolute_boxes, fixed_boxes)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/inlines.py", line 100, in get_next_linebox
    line_fixed, line_placeholders, waiting_floats)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/inlines.py", line 605, in split_inline_box
    waiting_floats)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/inlines.py", line 516, in split_inline_level
    waiting_floats)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/inlines.py", line 605, in split_inline_box
    waiting_floats)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/inlines.py", line 502, in split_inline_level
    context, box, max_x - position_x, max_x, skip)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/layout/inlines.py", line 685, in split_text_box
    text, box.style, context.enable_hinting, available_width, line_width)
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/text.py", line 563, in split_first_line
    first_part = utf8_slice(text, slice(temp_second_line_index))
  File "/usr/local/afs7/contrib/v7.7/python/3.3/lib/python3.3/site-packages/weasyprint/text.py", line 249, in utf8_slice
    return string.encode('utf-8')[slice_].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 1: unexpected end of data
```
Apparently, string.encode('utf-8')[slice_] slices an utf-8 character in half.

This issue has also been raised on stackoverflow : http://stackoverflow.com/questions/32097104/unicode-decode-error-for-weasyprint

Also, "it works on my machine" (osx), but not in QA env (debian)

Any idea ?

Thanks

**Comment by liZe** [comment]
Thanks for reporting!

**Comment by acouette** [comment]
That was fast !

Merci !
