### ISSUE TITLE
Percent-encoded Unicode in internal links

### ISSUE THREAD

**Issue by Kodiologist** [Kozea/WeasyPrint#322]
With WeasyPrint 0.28, trying to render the valid HTML5 document

```html
<!DOCTYPE html><html><head><meta charset="UTF-8"/><title>x</title></head><body>

<p style="margin-bottom: 20in">
the
<a href="#x%CF%80">link</a>
</p>

<p id="xπ">the target</p>

</body></html>
```

causes a fatal error while WeasyPrint is trying to print a warning:

    Traceback (most recent call last):
      File "/usr/local/bin/weasyprint", line 9, in <module>
        load_entry_point('WeasyPrint==0.28', 'console_scripts', 'weasyprint')()
      File "/usr/local/lib/python2.7/dist-packages/weasyprint/__main__.py", line 156, in main
        getattr(html, 'write_' + format_)(output, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/weasyprint/__init__.py", line 165, in write_pdf
        return self.render(stylesheets).write_pdf(target, zoom, attachments)
      File "/usr/local/lib/python2.7/dist-packages/weasyprint/document.py", line 492, in write_pdf
        self.url_fetcher)
      File "/usr/local/lib/python2.7/dist-packages/weasyprint/pdf.py", line 597, in write_pdf_metadata
        document, bookmark_root_id, scale)
      File "/usr/local/lib/python2.7/dist-packages/weasyprint/pdf.py", line 336, in prepare_metadata
        for page_links, matrix in izip(document.resolve_links(), matrices):
      File "/usr/local/lib/python2.7/dist-packages/weasyprint/document.py", line 398, in resolve_links
        'at line %s' % (anchor_name, link.sourceline))
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 1: ordinal not in range(128

The warning is that no target was found for the link, so I think there are two separate bugs here:

1. WeasyPrint can't find the target of a percent-encoded link.
2. WeasyPrint crashes when trying to include Unicode in a warning.

**Comment by liZe** [comment]
The problem only happens with Python 2.
