### ISSUE TITLE
a bytes-like object is required, not 'str' while importing HTML from weasyprint

### ISSUE THREAD

**Issue by jainmehul** [Kozea/WeasyPrint#332]
Traceback (most recent call last):
```
    from weasyprint import HTML
  File "Anaconda3\lib\site-packages\weasyprint\__init__.py", line 337, in <module>
    from .html import find_base_url, HTML5_UA_STYLESHEET, get_html_metadata  # noqa
  File "Anaconda3\lib\site-packages\weasyprint\html.py", line 41, in <module>
    HTML5_UA_STYLESHEET = CSS(filename=os.path.join(root, 'css', 'html5_ua.css'))
  File "Anaconda3\lib\site-packages\weasyprint\__init__.py", line 224, in __init__
    with result as (source_type, source, base_url, protocol_encoding):
  File "Anaconda3\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "Anaconda3\lib\site-packages\weasyprint\__init__.py", line 294, in _select_source
    base_url = path2url(filename)
  File "Anaconda3\lib\site-packages\weasyprint\urls.py", line 87, in path2url
    path = pathname2url(path)
  File "Anaconda3\lib\nturl2path.py", line 48, in pathname2url
    if not ':' in p:
TypeError: a bytes-like object is required, not 'str

```
I am working with Anaconda distribution of Python3.5 on windows 10. I have installed the necessary libraries of GTK and PYGObject.
Can someone tell me if this issue is of the setup or a bug?

**Comment by liZe** [comment]
Duplicates #261.
