### ISSUE TITLE
Crash when generating PDF of site with relative font sizing

### ISSUE THREAD

**Issue by rcarmo** [Kozea/WeasyPrint#349]
When trying to do:
```
weasyprint http://taoofmac.com test.pdf
```

I get:

```
Parse error at 1:19962, unknown at-rule in stylesheet context: @-ms-keyframes
Parse error at 1:20119, unknown at-rule in stylesheet context: @keyframes
Ignored `columns: 2` at 1:1, unknown property.
Traceback (most recent call last):
  File "/Users/rcarmo/.pyenv/versions/2.7.10/bin/weasyprint", line 11, in <module>
    sys.exit(main())
  File "/Users/rcarmo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/weasyprint/__main__.py", line 156, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/Users/rcarmo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/weasyprint/__init__.py", line 167, in write_pdf
    return self.render(stylesheets).write_pdf(target, zoom, attachments)
  File "/Users/rcarmo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/weasyprint/__init__.py", line 135, in render
    return Document._render(self, stylesheets, enable_hinting)
  File "/Users/rcarmo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/weasyprint/document.py", line 315, in _render
    for css in stylesheets or []])
  File "/Users/rcarmo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 508, in get_all_computed_styles
    root=element_tree, parent=element.getparent())
  File "/Users/rcarmo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 285, in set_computed_styles
    element, cascaded, parent_style, pseudo_type, root_style
  File "/Users/rcarmo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 336, in computed_from_cascaded
    element, pseudo_type, specified, computed, parent_style, root_style
  File "/Users/rcarmo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/weasyprint/css/computed_values.py", line 200, in compute
    value = function(computer, name, value)
  File "/Users/rcarmo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/weasyprint/css/computed_values.py", line 417, in font_size
    font_size=parent_font_size)
  File "/Users/rcarmo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/weasyprint/css/computed_values.py", line 305, in length
    result = value.value * computer.root_style.font_size
AttributeError: 'dict' object has no attribute 'font_size'
```

...which I suppose is due to the site using `rem` instead of `px` or `em` for font sizing.

I've reproduced the above in Mac OS X and Ubuntu Xenial 16.04.

**Comment by rcarmo** [comment]
Incidentally, this appears to have been fixed (or at least worked on) by @fdemmer [in his fork](https://github.com/fdemmer/WeasyPrint).
