### ISSUE TITLE
multiple columns with page break in between render content invisible

### ISSUE THREAD

**Issue by dominikschreiber** [Kozea/WeasyPrint#367]
The content of html elements with css columns applied is invisible if a page break appears inside. It looks like it occupies the space it takes (like a `visibility:hidden`), but is not visible any more.

Examples:

```html
<!-- this will render wonderfully as it takes only one page -->
<style>@page { size: A5 }</style>
<div style="columns: auto 2; column-gap: 1em">
  <p>Lo-fi DIY et, locavore you probably haven't heard of them kogi XOXO marfa ugh. Affogato eu neutra shoreditch. Leggings tumeric listicle, retro venmo voluptate viral excepteur pitchfork ea elit cupidatat aliqua. Selfies exercitation cardigan pour-over, ullamco placeat ugh air plant disrupt delectus irure vero. Jianbing vaporware food truck mlkshk. Odio affogato pickled, chartreuse incididunt raclette freegan etsy sustainable authentic excepteur est. Officia yr bicycle rights non enim, wayfarers selvage kickstarter copper mug ugh.</p>
  <p>Enim helvetica shabby chic, anim tumeric actually etsy cliche cold-pressed normcore ad. Keffiyeh fingerstache lumbersexual iPhone, nisi vaporware pok pok austin dreamcatcher pitchfork franzen meggings heirloom viral. Before they sold out everyday carry hot chicken, 3 wolf moon gastropub glossier labore post-ironic et brooklyn ramps pickled single-origin coffee cold-pressed kickstarter. Mollit duis fap ramps, 90's forage et bicycle rights austin swag cornhole ennui deserunt hammock. Kitsch dolor pug, cardigan sunt direct trade iceland taxidermy microdosing. Literally banjo stumptown yr, gastropub ea four loko officia enamel pin man braid nulla retro locavore pop-up.</p> 
</div>
```

```html
<!-- this will create two "empty" pages -->
<style>@page { size: A5 }</style>
<div style="columns: auto 2; column-gap: 1em">
  <p>Lo-fi DIY et, locavore you probably haven't heard of them kogi XOXO marfa ugh. Affogato eu neutra shoreditch. Leggings tumeric listicle, retro venmo voluptate viral excepteur pitchfork ea elit cupidatat aliqua. Selfies exercitation cardigan pour-over, ullamco placeat ugh air plant disrupt delectus irure vero. Jianbing vaporware food truck mlkshk. Odio affogato pickled, chartreuse incididunt raclette freegan etsy sustainable authentic excepteur est. Officia yr bicycle rights non enim, wayfarers selvage kickstarter copper mug ugh.</p>
  <p>Enim helvetica shabby chic, anim tumeric actually etsy cliche cold-pressed normcore ad. Keffiyeh fingerstache lumbersexual iPhone, nisi vaporware pok pok austin dreamcatcher pitchfork franzen meggings heirloom viral. Before they sold out everyday carry hot chicken, 3 wolf moon gastropub glossier labore post-ironic et brooklyn ramps pickled single-origin coffee cold-pressed kickstarter. Mollit duis fap ramps, 90's forage et bicycle rights austin swag cornhole ennui deserunt hammock. Kitsch dolor pug, cardigan sunt direct trade iceland taxidermy microdosing. Literally banjo stumptown yr, gastropub ea four loko officia enamel pin man braid nulla retro locavore pop-up.</p> 
  <p>This makes the content too large for one page and weasyprint prints an empty page.</p>
</div>
```

I'm fairly new to the CSS Paged Media Module, hence my question: *Does this work as expected?* I'd consider it a bug, but maybe `columns` is not supposed to work across line breaks and everything works perfect.

---

Another observation: if I add "non-columned" content (e.g. `<h1>hello weasyprint</h1>`) before the `<div>`, it is shown if the content fits on a single page. If a page-break would occur, WeasyPrint breaks with an error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__main__.py", line 156, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__init__.py", line 167, in write_pdf
    return self.render(stylesheets).write_pdf(target, zoom, attachments)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__init__.py", line 135, in render
    return Document._render(self, stylesheets, enable_hinting)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/document.py", line 327, in _render
    return cls([Page(p, enable_hinting) for p in page_boxes],
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/__init__.py", line 51, in layout_document
    pages = list(make_all_pages(context, root_box))
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/pages.py", line 562, in make_all_pages
    page_number)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/pages.py", line 514, in make_page
    positioned_boxes, positioned_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 582, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 582, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 64, in block_level_layout
    device_size, page_is_empty, absolute_boxes, fixed_boxes)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 189, in columns_layout
    device_size, page_is_empty, absolute_boxes, fixed_boxes, [])
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 582, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 582, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 458, in block_container_layout
    'line box with siblings before layout')
AssertionError: line box with siblings before layout
```

I'm using the weasyprint CLI (with weasyprint in an ubuntu 16.04 docker container, on an OSX host), if that's of any help.

Thanks in advance.

**Comment by liZe** [comment]
Thanks for reporting! That's definitely an example that can be included in #365.
