### ISSUE TITLE
win10 installation error

### ISSUE THREAD

**Issue by sander76** [Kozea/WeasyPrint#385]
Tried to install on win10, but I get an error loading gobject-2.0
Anyone a clue ?

I saw 
https://github.com/Kozea/WeasyPrint/issues/372
and placed my path to the front, but that didn't seem to do the trick...

```bash
Traceback (most recent call last):
  File "c:\users\steun\appdata\local\programs\python\python35-32\Lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\steun\appdata\local\programs\python\python35-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\virtualenvs\weasy\Scripts\weasyprint.exe\__main__.py", line 5, in <module>
  File "c:\virtualenvs\weasy\lib\site-packages\weasyprint\__init__.py", line 338, in <module>
    from .css import PARSER, preprocess_stylesheet  # noqa
  File "c:\virtualenvs\weasy\lib\site-packages\weasyprint\css\__init__.py", line 30, in <module>
    from . import computed_values
  File "c:\virtualenvs\weasy\lib\site-packages\weasyprint\css\computed_values.py", line 18, in <module>
    from .. import text
  File "c:\virtualenvs\weasy\lib\site-packages\weasyprint\text.py", line 216, in <module>
    'libgobject-2.0.dylib')
  File "c:\virtualenvs\weasy\lib\site-packages\weasyprint\text.py", line 212, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "c:\virtualenvs\weasy\lib\site-packages\cffi\api.py", line 139, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "c:\virtualenvs\weasy\lib\site-packages\cffi\api.py", line 769, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "c:\virtualenvs\weasy\lib\site-packages\cffi\api.py", line 758, in _load_backend_lib
    return backend.load_library(name, flags)
OSError: cannot load library gobject-2.0: error 0x7e
```

**Comment by liZe** [comment]
You have a 32-bit Python (the folder is `python35-32`), Is your Windows 32-bit too?

**Comment by sander76** [comment]
I do have win64. 
The strange thing is it worked previously running python 32 bit. My guess is that after I installed another version of python (3.5.2) 64 bit things broke.
But I am running weasyprint from a virtualenv so that shouldn't matter. But I could be completely wrong..

**Comment by liZe** [comment]
> I feel the installation just broke somehow and I have no clue where to look for an answer.

I'm not a Windows user but I've seen looooots of issues with various Python projects depending on external DLLs, and there's only one simple rule: **don't install 32-bit versions of Python or DLLs on a 64-bit Windows**. That's all.

If you don't follow this rule, you'll probably end up playing for hours with `PATH` and endless debugs with esoteric errors about `thisrandomlibraryidontcareabout.dll`, and I won't help you :wink:.

**Comment by sander76** [comment]
You're right. I am switching to a docker container doing the weasy stuff
for me...

Thanks for this great project!

**Comment by liZe** [comment]
You're welcome!
