### ISSUE TITLE
AssertionError: Got ' /' between two lines. Expected nothing or a preserved line break

### ISSUE THREAD

**Issue by jstohner** [Kozea/WeasyPrint#389]
This issue is similar, to #313, however I hope that I can provide enough information to reproduce the problem.

I get this error on the following HTML file (had to change the suffix to txt in order to embed in inside this issue):

[crash-demo.html.txt](https://github.com/Kozea/WeasyPrint/files/597523/crash-demo.html.txt)

The crash is dependent on the selected font, i.e. WeasyPrint crashes if the font is DejaVu, but may not crash on other fonts. I am using WeasyPrint 0.31 on a CentOS 6.8 system with the standard DejaVu fonts:

```
shell$ weasyprint --version
WeasyPrint version 0.31
shell$ cat /etc/redhat-release 
CentOS release 6.8 (Final)
shell$ yum list installed | grep -i dejavu
dejavu-fonts-common.noarch          2.33-1.el6                         @base    
dejavu-sans-fonts.noarch            2.33-1.el6                         @base    
shell$
```

I think the problem is that WeasyPrint it trying to break the line after the `/` and not before it, which should be ok because it is a Unix file path. However I am afraid that this contradicts to "LB13" in the Unicode TR14 which is cited in line 716 of `inlines.py`. So you have to decide if it is a bug or a feature... :-)

Here is the Python 3 traceback:

```
shell$ weasyprint crash-demo.html crash-demo.html.pdf

Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 11, in <module>
    load_entry_point('WeasyPrint==0.31', 'console_scripts', 'weasyprint')()
  File "/usr/local/lib/python3.5/site-packages/weasyprint/__main__.py", line 156, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/__init__.py", line 167, in write_pdf
    return self.render(stylesheets).write_pdf(target, zoom, attachments)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/__init__.py", line 135, in render
    return Document._render(self, stylesheets, enable_hinting)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/document.py", line 327, in _render
    return cls([Page(p, enable_hinting) for p in page_boxes],
  File "/usr/local/lib/python3.5/site-packages/weasyprint/document.py", line 327, in <listcomp>
    return cls([Page(p, enable_hinting) for p in page_boxes],
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/__init__.py", line 51, in layout_document
    pages = list(make_all_pages(context, root_box))
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/pages.py", line 562, in make_all_pages
    page_number)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/pages.py", line 514, in make_page
    positioned_boxes, positioned_boxes, adjoining_margins)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/blocks.py", line 582, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/blocks.py", line 582, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/blocks.py", line 467, in block_container_layout
    for line, resume_at in lines_iterator:
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/inlines.py", line 48, in iter_line_boxes
    device_size, absolute_boxes, fixed_boxes)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/inlines.py", line 100, in get_next_linebox
    line_fixed, line_placeholders, waiting_floats)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/inlines.py", line 595, in split_inline_box
    waiting_floats)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/inlines.py", line 492, in split_inline_level
    context, box, max_x - position_x, max_x, skip)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/layout/inlines.py", line 720, in split_text_box
    'Expected nothing or a preserved line break' % (between,))
AssertionError: Got ' /' between two lines. Expected nothing or a preserved line break
shell$ 
```

Thank you for providing WeasyPrint!

**Comment by liZe** [comment]
Thanks for reporting this bug once again, **I can now reproduce it** :tada:.

I work on this as soon as 0.32 is released (in 1 hour or so I hope).
