### ISSUE TITLE
Fatal error with Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by sander76** [Kozea/WeasyPrint#391]
After failing installing a weasyprint on windows I tried my luck with a linux machine (running python 2.7.12). But a test doing:

```
weasyprint http://weasyprint.org ./weasyprint-website.pdf
```

resulted in 

```bash
Fatal Python error: deallocating None
Aborted (core dumped)
```

anyone an idea how to solve this ?

UPDATE:
Did the same but now running python 3.5. Got the same error but with more info included:

```
Fatal Python error: deallocating None

Current thread 0x00007fdc8ee42700 (most recent call first):
  File "/usr/lib/python3.5/logging/__init__.py", line 1291 in warning
  File "/home/sander/wprint/lib/python3.5/site-packages/weasyprint/fonts.py", line 205 in add_font_face
  File "/home/sander/wprint/lib/python3.5/site-packages/weasyprint/css/__init__.py", line 691 in preprocess_stylesheet
  File "/home/sander/wprint/lib/python3.5/site-packages/weasyprint/__init__.py", line 261 in __init__
  File "/home/sander/wprint/lib/python3.5/site-packages/weasyprint/css/__init__.py", line 637 in preprocess_stylesheet
  File "/home/sander/wprint/lib/python3.5/site-packages/weasyprint/__init__.py", line 261 in __init__
  File "/home/sander/wprint/lib/python3.5/site-packages/weasyprint/css/__init__.py", line 162 in find_stylesheets
  File "/home/sander/wprint/lib/python3.5/site-packages/weasyprint/css/__init__.py", line 711 in get_all_computed_styles
  File "/home/sander/wprint/lib/python3.5/site-packages/weasyprint/document.py", line 325 in _render
  File "/home/sander/wprint/lib/python3.5/site-packages/weasyprint/__init__.py", line 143 in render
  File "/home/sander/wprint/lib/python3.5/site-packages/weasyprint/__init__.py", line 178 in write_pdf
  File "/home/sander/wprint/lib/python3.5/site-packages/weasyprint/__main__.py", line 164 in main
  File "/home/sander/wprint/bin/weasyprint", line 11 in <module>
Aborted (core dumped)
```

ANOTHER UPDATE:
Did an install of an older version of weasyprint (0.30).
Now generation of a pdf works. Something wrong with the latest version (0.32) ?

**Comment by liZe** [comment]
Thank you for reporting this issue.

I can reproduce with Ubuntu 16.04 LTS, I supose that it's your distribution too.

**Comment by liZe** [comment]
No idea why it was working both for me on Gentoo and on Travis-CI. Please try the current master branch and tell me if it fixes the bug for you too.

**Comment by sander76** [comment]
Not sure whether it solved this. I now run into another issue using the current master..

running:
```
weasyprint http://weasyprint.org ./weasyprint-website.pdf
```
now results in:

```
WARNING: Failed to load local font "Oswald Regular"
WARNING: Failed to load local font "Oswald-Regular"
WARNING: Failed to load local font "Alegreya Sans"
WARNING: Failed to load local font "AlegreyaSans-Regular"

WARNING: Failed to load local font "Alegreya Sans Bold"
WARNING: Failed to load local font "AlegreyaSans-Bold"
WARNING: Failed to load local font "Alegreya Sans Italic"
WARNING: Failed to load local font "AlegreyaSans-Italic"
Traceback (most recent call last):
  File "/home/sander/envs/weasy_head/bin/weasyprint", line 11, in <module>
    load_entry_point('WeasyPrint==0.32', 'console_scripts', 'weasyprint')()
  File "/home/sander/envs/weasy_head/lib/python2.7/site-packages/WeasyPrint-0.32-py2.7.egg/weasyprint/__main__.py", line 164, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/home/sander/envs/weasy_head/lib/python2.7/site-packages/WeasyPrint-0.32-py2.7.egg/weasyprint/__init__.py", line 178, in write_pdf
    return self.render(stylesheets, presentational_hints).write_pdf(
  File "/home/sander/envs/weasy_head/lib/python2.7/site-packages/WeasyPrint-0.32-py2.7.egg/weasyprint/__init__.py", line 143, in render
    self, stylesheets, enable_hinting, presentational_hints)
  File "/home/sander/envs/weasy_head/lib/python2.7/site-packages/WeasyPrint-0.32-py2.7.egg/weasyprint/document.py", line 325, in _render
    font_config=font_config)
  File "/home/sander/envs/weasy_head/lib/python2.7/site-packages/WeasyPrint-0.32-py2.7.egg/weasyprint/css/__init__.py", line 712, in get_all_computed_styles
    element_tree, device_media_type, url_fetcher, font_config))
  File "/home/sander/envs/weasy_head/lib/python2.7/site-packages/WeasyPrint-0.32-py2.7.egg/weasyprint/css/__init__.py", line 162, in find_stylesheets
    font_config=font_config)
  File "/home/sander/envs/weasy_head/lib/python2.7/site-packages/WeasyPrint-0.32-py2.7.egg/weasyprint/__init__.py", line 261, in __init__
    self.fonts, font_config)
  File "/home/sander/envs/weasy_head/lib/python2.7/site-packages/WeasyPrint-0.32-py2.7.egg/weasyprint/css/__init__.py", line 637, in preprocess_stylesheet
    media_type=device_media_type, font_config=font_config)
  File "/home/sander/envs/weasy_head/lib/python2.7/site-packages/WeasyPrint-0.32-py2.7.egg/weasyprint/__init__.py", line 261, in __init__
    self.fonts, font_config)
  File "/home/sander/envs/weasy_head/lib/python2.7/site-packages/WeasyPrint-0.32-py2.7.egg/weasyprint/css/__init__.py", line 692, in preprocess_stylesheet
    rule_descriptors, url_fetcher)
  File "/home/sander/envs/weasy_head/lib/python2.7/site-packages/WeasyPrint-0.32-py2.7.egg/weasyprint/fonts.py", line 198, in add_font_face
    config, pattern)
TypeError: 'FcPattern *(*)(FcConfig *, FcPattern *, FcResult *)' expects 3 arguments, got 2
```

**Comment by liZe** [comment]
@sander76 Sorry, it should be *really fixed* now.
