### ISSUE TITLE
Crashing with TypeError: range() integer end argument expected, got float

### ISSUE THREAD

**Issue by ndubbaka** [Kozea/WeasyPrint#403]
When I run this command ```weasyprint https://en.wikipedia.org/wiki/Gravity Gravity.pdf``` I don't get a pdf file & I see the below Traceback
```
WARNING: Ignored `-webkit-column-width: 30em` at 1:26, unknown property.
/usr/local/lib/python2.7/site-packages/cairocffi/surfaces.py:447: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  *keep_alive.closure))
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/weasyprint/__main__.py", line 164, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/__init__.py", line 178, in write_pdf
    return self.render(stylesheets, presentational_hints).write_pdf(
  File "/usr/local/lib/python2.7/site-packages/weasyprint/__init__.py", line 143, in render
    self, stylesheets, enable_hinting, presentational_hints)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/document.py", line 334, in _render
    [Page(p, enable_hinting) for p in page_boxes],
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/__init__.py", line 53, in layout_document
    pages = list(make_all_pages(context, root_box))
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/pages.py", line 567, in make_all_pages
    page_number)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/pages.py", line 513, in make_page
    positioned_boxes, positioned_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 70, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 98, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 603, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 70, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 98, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 603, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 70, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 98, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 603, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 70, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 98, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 603, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 70, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 98, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 603, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 70, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 98, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 603, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 70, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 98, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 603, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 70, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 98, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 603, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 65, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 224, in columns_layout
    for i in range(count):
TypeError: range() integer end argument expected, got float.
```

**Comment by liZe** [comment]
I think that this problem is fixed in cf0efe6. I have to add some tests about columns to avoid this in the future.

**Comment by liZe** [comment]
Reopening: the footnotes are broken (because of columns), it's time to fix this for real.

**Comment by ndubbaka** [comment]
Thanks for the quick response. I will check it out.

**Comment by liZe** [comment]
Multi-page algorithm is now much better, and the rendering of the Gravity page seems to be perfect (in a CSS way, it doesn't mean that Wikipedia's CSS for print is beautiful). I really have to add some tests before closing this issue.
