### ISSUE TITLE
WeasyPrint Navigator fails to launch

### ISSUE THREAD

**Issue by fried-sausage** [Kozea/WeasyPrint#430]
The OS is Debian jessie.
```
(ENV) rob@Rob:~/projects/ENV/bin$ python3 -m weasyprint.navigator
WARNING: @font-face support needs Pango >= 1.38
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
WARNING: @font-face support needs Pango >= 1.38
Traceback (most recent call last):
  File "/home/rob/projects/ENV/lib/python3.4/site-packages/weasyprint/navigator.py", line 171, in <module>
    run()
  File "/home/rob/projects/ENV/lib/python3.4/site-packages/weasyprint/navigator.py", line 156, in run
    from werkzeug.serving import run_simple
  File "/home/rob/projects/ENV/lib/python3.4/site-packages/werkzeug/__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "/home/rob/projects/ENV/lib/python3.4/site-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/home/rob/projects/ENV/lib/python3.4/site-packages/werkzeug/wrappers.py", line 36, in <module>
    from werkzeug.utils import cached_property, environ_property, \
  File "/home/rob/projects/ENV/lib/python3.4/site-packages/werkzeug/utils.py", line 18, in <module>
    from html.entities import name2codepoint
  File "/home/rob/projects/ENV/lib/python3.4/site-packages/weasyprint/html.py", line 24, in <module>
    from .css import get_child_text
SystemError: Parent module '' not loaded, cannot perform relative import
(ENV) rob@Rob:~/projects/ENV/bin$ 

```

**Comment by fried-sausage** [comment]
Just cloned repo and moved navigator.py to top-level directory (along with weasyprint.py script).
`python3 navigator.py` works as expected.

**Comment by liZe** [comment]
Thanks for reporting your issue!

It's bug we already know (#133), we should use the new Flask CLI.
