### ISSUE TITLE
'weasyprint' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by 1beb** [Kozea/WeasyPrint#439]
I'm getting the following error and I'm not sure how to debug any thoughts on where to start? 

```
/usr/bin/python: cannot import name viewkeys; 'weasyprint' is a package and cannot be directly executed
```

**Comment by liZe** [comment]
How did you get this error?

**Comment by 1beb** [comment]
I use WeasyPrint to print HTML rerports generated in R, to PDF, because I think latex is a horrible waste of time. I have a dockerized setup that was working before but suddenly stopped. Here's a basic overview of the dockerfile: 

```
FROM rocker/hadleyverse # Essentially Debian Jessie with some packages for R

RUN apt-get update && apt-get install -y \ # Prereqs for Weasy
  libxml2-dev libxslt1-dev libffi-dev \ 
  build-essential \
  python-dev \
  python-pip \
  libssl-dev \
  zlib1g-dev \
  python-lxml \
  python-cffi \
  libcairo2 \
  libpango1.0-0 \
  libgdk-pixbuf2.0-0 \
  shared-mime-info

# Stripped things here like adding a font and chmod R lib folder because I think it's irrelevant.

# Some bugs made me do this 
#RUN python -m pip install -U pip
#RUN python -m pip install --upgrade cffi
#RUN python -m pip install --upgrade six
RUN python -m pip install Cython
RUN python -m pip install WeasyPrint
```

From within my docker container, I call: 

```
python -m weasyprint some.html some.pdf
```

**Comment by liZe** [comment]
For some reason, you may have an old version of html5lib installed, you can try to update it.

Probably related issue: xhtml2pdf/xhtml2pdf#318.

**Comment by 1beb** [comment]
Thanks Guillaume, I will try it out and get back to you here.

**Comment by 1beb** [comment]
I added 

```
RUN python -m pip install html5lib==1.0b8
```

```
+ python -m weasyprint some.html some.pdf
WARNING: There are known rendering problems with Cairo <= 1.14.0
WARNING: @font-face support needs Pango >= 1.38
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__main__.py", line 168, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__main__.py", line 163, in main
    media_type=args.media_type)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__init__.py", line 94, in __init__
    namespaceHTMLElements=False)
TypeError: parse() got an unexpected keyword argument 'override_encoding'
```

**Comment by liZe** [comment]
You need at least 1.0b9 :wink:, use `pip install --upgrade html5lib` to get the latest version.

**Comment by liZe** [comment]
@1beb does it work for you now?

**Comment by 1beb** [comment]
It did not. So I switched to another docker instance that runs this as a
service.

Brandon Erik Bertelsen
647 287 1009
brandon@bertelsen.ca
Linkedin <http://www.linkedin.com/in/bbertelsen>

**Comment by liZe** [comment]
Thanks. I close the issue now, as I think that it's more a problem with your installation than with WeasyPrint itself.

If anyone meets this issue again, feel free to reopen!

**Comment by 1beb** [comment]
Agreed. Thanks for your help here!
