### ISSUE TITLE
AssertionError: Got u'al ' between two lines. Expected nothing or a preserved line break

### ISSUE THREAD

**Issue by vivekc** [Kozea/WeasyPrint#444]
Found out non-ascii characters in html. Any way we can handle this issue? Cleaning data during rendering the view is time consuming and delays operation. 

```
Traceback (most recent call last):
  File "/home/vivekc/workspace/venv/bin/weasyprint", line 9, in <module>
    load_entry_point('WeasyPrint==0.36', 'console_scripts', 'weasyprint')()
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/__main__.py", line 164, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/__init__.py", line 180, in write_pdf
    presentational_hints=presentational_hints).write_pdf(
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/__init__.py", line 143, in render
    self, stylesheets, enable_hinting, presentational_hints)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/document.py", line 334, in _render
    [Page(p, enable_hinting) for p in page_boxes],
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/__init__.py", line 53, in layout_document
    pages = list(make_all_pages(context, root_box))
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/pages.py", line 567, in make_all_pages
    page_number)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/pages.py", line 513, in make_page
    positioned_boxes, positioned_boxes, adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 604, in block_container_layout
    adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 604, in block_container_layout
    adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 604, in block_container_layout
    adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 42, in block_level_layout
    device_size, page_is_empty, absolute_boxes, fixed_boxes)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/tables.py", line 364, in table_layout
    all_groups_layout()
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/tables.py", line 351, in all_groups_layout
    skip_stack, position_y, max_position_y, page_is_empty)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/tables.py", line 258, in body_groups_layout
    group, position_y, max_position_y, page_is_empty, skip_stack)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/tables.py", line 129, in group_layout
    fixed_boxes=fixed_boxes)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 604, in block_container_layout
    adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 604, in block_container_layout
    adjoining_margins)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 42, in block_level_layout
    device_size, page_is_empty, absolute_boxes, fixed_boxes)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/tables.py", line 364, in table_layout
    all_groups_layout()
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/tables.py", line 351, in all_groups_layout
    skip_stack, position_y, max_position_y, page_is_empty)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/tables.py", line 258, in body_groups_layout
    group, position_y, max_position_y, page_is_empty, skip_stack)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/tables.py", line 129, in group_layout
    fixed_boxes=fixed_boxes)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 481, in block_container_layout
    for line, resume_at in lines_iterator:
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/inlines.py", line 51, in iter_line_boxes
    device_size, absolute_boxes, fixed_boxes, first_letter_style)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/inlines.py", line 107, in get_next_linebox
    line_fixed, line_placeholders, waiting_floats)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/inlines.py", line 676, in split_inline_box
    waiting_floats)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/inlines.py", line 573, in split_inline_level
    context, box, max_x - position_x, max_x, skip)
  File "/home/vivekc/workspace/venv/local/lib/python2.7/site-packages/weasyprint/layout/inlines.py", line 800, in split_text_box
    'Expected nothing or a preserved line break' % (between,))
AssertionError: Got u'al ' between two lines. Expected nothing or a preserved line break
```
Python version - 2.7
Weasyprint version
```
$ weasyprint --version      
WARNING: There are known rendering problems with Cairo <= 1.14.0
WARNING: @font-face support needs Pango >= 1.38
WeasyPrint version 0.36
```

**Comment by liZe** [comment]
Could you please provide your document?

**Comment by vivekc** [comment]
Am afraid that cannot be done. I cleaned the column values which were having \x00  as one of the characters in the database after which pdf conversion was successful.

**Comment by liZe** [comment]
> I cleaned the column values which were having \x00 as one of the characters in the database after which pdf conversion was successful.

Well… Let's say it's because of the null character, it's not really an issue we want to solve right now.

Thanks for the report!
