### ISSUE TITLE
Encoding issue.

### ISSUE THREAD

**Issue by migrome** [Kozea/WeasyPrint#46]
python 2.7
I have weasyprint library stored inside the project. Path to the project has russian letters.
```
Traceback (most recent call last):
  File "D:\\_IDE\eclipse\workspace\test\src - копия\src\main.py", line 6, in <module>
    from weasyprint import HTML
  File "D:\\_IDE\eclipse\workspace\test\src - копия\src\weasyprint\__init__.py", line 304, in <module>
    from .css import PARSER, preprocess_stylesheet
  File "D:\\_IDE\eclipse\workspace\test\src - копия\src\weasyprint\css\__init__.py", line 30, in <module>
    from . import computed_values
  File "D:\\_IDE\eclipse\workspace\test\src - копия\src\weasyprint\css\computed_values.py", line 20, in <module>
    from .. import text
  File "D:\\_IDE\eclipse\workspace\test\src - копия\src\weasyprint\text.py", line 18, in <module>
    import pyphen
  File "D:\\_IDE\eclipse\workspace\test\src - копия\src\pyphen\__init__.py", line 44, in <module>
    dictionaries_root = os.path.join(os.path.dirname(__file__), 'dictionaries')
  File "C:\dev\Python27\lib\ntpath.py", line 108, in join
    path += "\\" + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xea in position 70: ordinal not in range(128)
```

Should be something like:
```
encoding = sys.getfilesystemencoding()
__file__.decode(encoding)
```

**Comment by liZe** [comment]
@migrome is this bug fixed with the new versions of Python 2.7 and/or WeasyPrint?
