### ISSUE TITLE
'module' object has no attribute 'Inbox' when use ::first-letter pseudo-element

### ISSUE THREAD

**Issue by CorentinBrule** [Kozea/WeasyPrint#462]
If there is :
```
p::first-letter{
    margin-left:1em;
}
```

It return : 
```
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 11, in <module>
    load_entry_point('WeasyPrint==0.36', 'console_scripts', 'weasyprint')()
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__main__.py", line 164, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__init__.py", line 180, in write_pdf
    presentational_hints=presentational_hints).write_pdf(
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__init__.py", line 143, in render
    self, stylesheets, enable_hinting, presentational_hints)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/document.py", line 334, in _render
    [Page(p, enable_hinting) for p in page_boxes],
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/__init__.py", line 53, in layout_document
    pages = list(make_all_pages(context, root_box))
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/pages.py", line 567, in make_all_pages
    page_number)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/pages.py", line 513, in make_page
    positioned_boxes, positioned_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 604, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 604, in block_container_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 69, in block_level_layout
    adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 97, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/blocks.py", line 481, in block_container_layout
    for line, resume_at in lines_iterator:
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/inlines.py", line 51, in iter_line_boxes
    device_size, absolute_boxes, fixed_boxes, first_letter_style)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/inlines.py", line 80, in get_next_linebox
    skip_stack = first_letter_to_box(linebox, skip_stack, first_letter_style)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/inlines.py", line 321, in first_letter_to_box
    child, child_skip_stack, first_letter_style)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/layout/inlines.py", line 259, in first_letter_to_box
    letter_box = boxes.Inbox(
AttributeError: 'module' object has no attribute 'Inbox'
```

**Comment by liZe** [comment]
I've fixed the obvious typo, but I've been unable to reproduce. Could you please provide a full example for the record?
