### ISSUE TITLE
weazyprint 0.37 fails with google font stylesheets

### ISSUE THREAD

**Issue by johndagostino** [Kozea/WeasyPrint#477]
Example below works as expected on 0.36 but fails with the recently released 0.37

Backtrace from WeazyPrint

```bash
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 11, in <module>
    load_entry_point('WeasyPrint==0.37', 'console_scripts', 'weasyprint')()
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__main__.py", line 172, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__init__.py", line 181, in write_pdf
    presentational_hints=presentational_hints).write_pdf(
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__init__.py", line 146, in render
    self, stylesheets, enable_hinting, presentational_hints)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/document.py", line 317, in _render
    font_config=font_config)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/css/__init__.py", line 770, in get_all_computed_styles
    element_tree, device_media_type, url_fetcher, font_config))
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/css/__init__.py", line 160, in find_stylesheets
    font_config=font_config)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/__init__.py", line 268, in __init__
    self.fonts, font_config)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/css/__init__.py", line 722, in preprocess_stylesheet
    base_url, content))
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/css/descriptors.py", line 165, in preprocess_descriptors
    result = list(validate(base_url, descriptor.name, tokens))
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/css/descriptors.py", line 143, in validate
    value = function(tokens, base_url)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/css/validation.py", line 172, in wrapper
    result = function(remove_whitespace(part), *args)
  File "/usr/local/lib/python2.7/dist-packages/weasyprint/css/descriptors.py", line 76, in src
    return 'local', font_family(token.content, allow_spaces=True)
AttributeError: 'FunctionBlock' object has no attribute 'content'
```

Example test html file

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Test</title>
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
</head>
<body>
  <div class="book">
  </div>
</body>
</html>
```

**Comment by liZe** [comment]
Thanks for reporting this issue, sorry for this problem…
