### ISSUE TITLE
AttributeError: 'FunctionBlock' object has no attribute 'content'

### ISSUE THREAD

**Issue by ali-bahjati** [Kozea/WeasyPrint#479]
When I want to run weasyprint, I get the following error (I tested on both python3 and python2, same error)
I also installed all required packages mentioned in installation documentation

```
(pdf-venv) $  weasyprint http://weasyprint.org ./weasyprint-website.pdf

Traceback (most recent call last):
  File "/home/ali/venvs/pdf/bin/weasyprint", line 11, in <module>
    sys.exit(main())
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/__main__.py", line 172, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/__init__.py", line 181, in write_pdf
    presentational_hints=presentational_hints).write_pdf(
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/__init__.py", line 146, in render
    self, stylesheets, enable_hinting, presentational_hints)
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/document.py", line 317, in _render
    font_config=font_config)
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 770, in get_all_computed_styles
    element_tree, device_media_type, url_fetcher, font_config))
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 160, in find_stylesheets
    font_config=font_config)
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/__init__.py", line 268, in __init__
    self.fonts, font_config)
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 646, in preprocess_stylesheet
    media_type=device_media_type, font_config=font_config)
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/__init__.py", line 268, in __init__
    self.fonts, font_config)
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 722, in preprocess_stylesheet
    base_url, content))
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/css/descriptors.py", line 165, in preprocess_descriptors
    result = list(validate(base_url, descriptor.name, tokens))
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/css/descriptors.py", line 143, in validate
    value = function(tokens, base_url)
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/css/validation.py", line 172, in wrapper
    result = function(remove_whitespace(part), *args)
  File "/home/ali/venvs/pdf/local/lib/python2.7/site-packages/weasyprint/css/descriptors.py", line 76, in src
    return 'local', font_family(token.content, allow_spaces=True)
AttributeError: 'FunctionBlock' object has no attribute 'content'

```

**Comment by liZe** [comment]
Duplicates #477, I'll release a new version soon.
