### ISSUE TITLE
ImportError: cannot import name viewkeys

### ISSUE THREAD

**Issue by clarkk** [Kozea/WeasyPrint#491]
Installing Python and pip
```
# apt-get install python-dev
# cd /var/bin && wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py
```

Installing WeasyPrint
```
# apt-get install python-lxml libcairo2 libpango1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
# pip install --upgrade cffi
# pip install WeasyPrint
```

Debian 8

```
# pip install --upgrade cffi
/usr/local/lib/python2.7/dist-packages/cffi/model.py:525: UserWarning: 'point_conversion_form_t' has no values explicitly defined; guessing that it is equivalent to 'unsigned int'
  % self._get_c_name())
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/subversion.py", line 4, in <module>
    from pip.index import Link
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 17, in <module>
    import html5lib, requests, pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/html5lib/__init__.py", line 16, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/usr/local/lib/python2.7/dist-packages/html5lib/html5parser.py", line 2, in <module>
    from six import with_metaclass, viewkeys, PY3
ImportError: cannot import name viewkeys
```

Installing WeasyPring
```
# pip install WeasyPrint
/usr/local/lib/python2.7/dist-packages/cffi/model.py:525: UserWarning: 'point_conversion_form_t' has no values explicitly defined; guessing that it is equivalent to 'unsigned int'
  % self._get_c_name())
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/subversion.py", line 4, in <module>
    from pip.index import Link
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 17, in <module>
    import html5lib, requests, pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/html5lib/__init__.py", line 16, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/usr/local/lib/python2.7/dist-packages/html5lib/html5parser.py", line 2, in <module>
    from six import with_metaclass, viewkeys, PY3
ImportError: cannot import name viewkeys
```

**Comment by liZe** [comment]
Thanks for your report.

Your version of html5lib and/or six is outdated, you should update them. See #439 and #338 for more information.

Manually installing python packages system-wide on a distribution that installs its own python packages can be a bit dangerous. You should use a virtualenv as recommanded in the documentation and upgrade html5lib and/or six in this virtualenv.

**Comment by clarkk** [comment]
Have tried to upgrade both but get errors?

```
# pip install --upgrade html5lib
/usr/local/lib/python2.7/dist-packages/cffi/model.py:525: UserWarning: 'point_conversion_form_t' has no values explicitly defined; guessing that it is equivalent to 'unsigned int'
  % self._get_c_name())
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/subversion.py", line 4, in <module>
    from pip.index import Link
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 17, in <module>
    import html5lib, requests, pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/html5lib/__init__.py", line 16, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/usr/local/lib/python2.7/dist-packages/html5lib/html5parser.py", line 2, in <module>
    from six import with_metaclass, viewkeys, PY3
ImportError: cannot import name viewkeys


# pip install --upgrade six
/usr/local/lib/python2.7/dist-packages/cffi/model.py:525: UserWarning: 'point_conversion_form_t' has no values explicitly defined; guessing that it is equivalent to 'unsigned int'
  % self._get_c_name())
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/subversion.py", line 4, in <module>
    from pip.index import Link
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 17, in <module>
    import html5lib, requests, pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/html5lib/__init__.py", line 16, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/usr/local/lib/python2.7/dist-packages/html5lib/html5parser.py", line 2, in <module>
    from six import with_metaclass, viewkeys, PY3
ImportError: cannot import name viewkeys
```

**Comment by clarkk** [comment]
I can't install pip by doing `apt-get install python-pip` because its an very old version of pip 1.5

**Comment by liZe** [comment]
You have modules installed in both `/usr/lib` and `/usr/local/lib` and you don't use a virtual environment, it's generally a really bad situation.

**Manually installing python packages system-wide on a distribution that installs its own python packages can be a bit dangerous.** You should remove what's in `/usr/local/lib/python2.7` and use virtual environment for your Python projects, or you'll spend hours fixing problems that I don't want to fix with you :wink:.

Here's [a page](https://review.openstack.org/gitweb?p=openstack/swift.git;a=commitdiff;h=c6ef2ab015a2c3bf0349f4b63f261f29dbfb75a5) explaining exactly your problem. You have an old version of `six` installed, probably by Debian. If you really don't want to use a virtual environment, uninstall this package (`sudo  apt-get  purge  python-six`), reinstall it with pip (`sudo  pip  install  -U  six`) and hope that you didn't break anything on your system (**it can be dangerous**).

There's also a [request for package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844046) and a [PPA with WeasyPrint](https://launchpad.net/~stoq-dev/+archive/ubuntu/lancamentos/+index?batch=75&memo=75&start=75).

**Comment by clarkk** [comment]
how can you then install and use weasyprint with virtual env?

**Comment by liZe** [comment]
You can check the [installation guide](http://weasyprint.readthedocs.io/en/latest/install.html) and a [good introduction to virtual enviromnent in the hitchhikers' guide to Python](http://docs.python-guide.org/en/latest/dev/virtualenvs/).

**Comment by clarkk** [comment]
ok.. I got it to work my removing `python-six` and installing it again with `pip`

But now I get this warning

```
 WARNING: There are known rendering problems with Cairo <= 1.14.0 WARNING: @font-face support needs Pango >= 1.38
```

how to upgrade these libs? :) What are they called?

**Comment by clarkk** [comment]
```
# python -m pip install --upgrade cairo
Collecting cairo
  Could not find a version that satisfies the requirement cairo (from versions: )
No matching distribution found for cairo

# python -m pip install --upgrade pango
Collecting pango
  Could not find a version that satisfies the requirement pango (from versions: )
No matching distribution found for pango
```

**Comment by liZe** [comment]
Cairo and Pango are not Python modules, they're C libraries. Use Debian 9 if you want up-to-date libraries, it's got [Pango 1.40.5](https://packages.debian.org/fr/stretch/libpango1.0-0) and [Cairo 1.14.8](https://packages.debian.org/fr/stretch/libcairo2).

Closing, as it's not a problem with WeasyPrint.

**Comment by clarkk** [comment]
ok.. thanks :)
