### ISSUE TITLE
Weasyprint chokes on some HTML (layout bug?)

### ISSUE THREAD

**Issue by sjdv1982** [Kozea/WeasyPrint#580]
Minimal HTML attached: [bug.html.txt](https://github.com/Kozea/WeasyPrint/files/1759627/bug.html.txt)
Random changes to the text make the bug (dis)appear.

It happens in both the PyPI and the master branch of weasyprint. I am on Kubuntu with the following rendering libraries:
```
libcairo2/artful,now 1.14.10-1ubuntu1 amd64 [installed]
libgdk-pixbuf2.0-0/artful-updates,artful-security,now 2.36.11-1ubuntu0.1 amd64 [installed]
libpango-1.0-0/artful,now 1.40.12-1 amd64 [installed]
libpangocairo-1.0-0/artful,now 1.40.12-1 amd64 [installed]
```
Error message:
```
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 11, in <module>
    sys.exit(main())
  File "/home/sjoerd/github/PYTHON/weasyprint/__main__.py", line 173, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/home/sjoerd/github/PYTHON/weasyprint/__init__.py", line 185, in write_pdf
    font_config=font_config).write_pdf(
  File "/home/sjoerd/github/PYTHON/weasyprint/__init__.py", line 146, in render
    font_config)
  File "/home/sjoerd/github/PYTHON/weasyprint/document.py", line 316, in _render
    [Page(p, enable_hinting) for p in page_boxes],
  File "/home/sjoerd/github/PYTHON/weasyprint/document.py", line 316, in <listcomp>
    [Page(p, enable_hinting) for p in page_boxes],
  File "/home/sjoerd/github/PYTHON/weasyprint/layout/__init__.py", line 53, in layout_document
    context, root_box, html, cascaded_styles, computed_styles))
  File "/home/sjoerd/github/PYTHON/weasyprint/layout/pages.py", line 600, in make_all_pages
    context, root_box, page_type, resume_at, page_number)
  File "/home/sjoerd/github/PYTHON/weasyprint/layout/pages.py", line 519, in make_page
    positioned_boxes, positioned_boxes, adjoining_margins)
  File "/home/sjoerd/github/PYTHON/weasyprint/layout/blocks.py", line 79, in block_level_layout
    adjoining_margins)
  File "/home/sjoerd/github/PYTHON/weasyprint/layout/blocks.py", line 107, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/sjoerd/github/PYTHON/weasyprint/layout/blocks.py", line 640, in block_container_layout
    adjoining_margins)
  File "/home/sjoerd/github/PYTHON/weasyprint/layout/blocks.py", line 79, in block_level_layout
    adjoining_margins)
  File "/home/sjoerd/github/PYTHON/weasyprint/layout/blocks.py", line 107, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/sjoerd/github/PYTHON/weasyprint/layout/blocks.py", line 512, in block_container_layout
    for line, resume_at in lines_iterator:
  File "/home/sjoerd/github/PYTHON/weasyprint/layout/inlines.py", line 49, in iter_line_boxes
    device_size, absolute_boxes, fixed_boxes, first_letter_style)
  File "/home/sjoerd/github/PYTHON/weasyprint/layout/inlines.py", line 106, in get_next_linebox
    waiting_floats, line_children=[])
  File "/home/sjoerd/github/PYTHON/weasyprint/layout/inlines.py", line 839, in split_inline_box
    child_resume_at[0] + current_skip,
TypeError: 'NoneType' object is not subscriptable
```

**Comment by sjdv1982** [comment]
Works for me, thanks!
