### ISSUE TITLE
initial tests fail after install

### ISSUE THREAD

**Issue by wendallsan** [Kozea/WeasyPrint#623]
I have installed WeasyPrint on a Rasberry Pi 3 for testing purposes.  After setting up a Python 3.6 environment to run in, I used the pip approach to install WeasyPrint according to the documentation, which seemed to have completed successfully.  

Running the command provided in the documetation to run weasyprint:  
```
weasyprint http://weasyprint.org /tmp/weasyprint-website.pdf
```
I am getting an error:  
```
raise URLFetchingError('%s: %s' % (name, value) if value else name)
weasyprint.urls.URLFetchingError: URLError: <urlopen error [Errno -2] Name or service not known>
```

I have searched for references to this URLFectchingError, but was not able to find anything helpful.  

Please advise.  Here is the full output of the above command:  

```
pi@gitlab:~ $ sudo weasyprint http://weasyrint.org ~/test.pdf
/usr/local/lib/python3.4/dist-packages/weasyprint/text.py:28: UserWarning: There are known rendering problems with Cairo <= 1.14.0
  warnings.warn('There are known rendering problems with Cairo <= 1.14.0')
/usr/local/lib/python3.4/dist-packages/weasyprint/fonts.py:43: UserWarning: @font-face support needs Pango >= 1.38
  warnings.warn('@font-face support needs Pango >= 1.38')
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1174, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 491, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/weasyprint/urls.py", line 287, in fetch
    result = url_fetcher(url)
  File "/usr/local/lib/python3.4/dist-packages/weasyprint/urls.py", line 252, in default_url_fetcher
    response = urlopen(Request(url, headers=HTTP_HEADERS))
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 473, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1202, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1176, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/weasyprint/__main__.py", line 176, in main
    media_type=args.media_type)
  File "/usr/local/lib/python3.4/dist-packages/weasyprint/__init__.py", line 88, in __init__
    with result as (source_type, source, base_url, protocol_encoding):
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/weasyprint/__init__.py", line 333, in _select_source
    with result as result:
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/weasyprint/__init__.py", line 341, in _select_source
    with fetch(url_fetcher, url) as result:
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/weasyprint/urls.py", line 291, in fetch
    raise URLFetchingError('%s: %s' % (name, value) if value else name)
weasyprint.urls.URLFetchingError: URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by liZe** [comment]
> sudo weasyprint http://weasyrint.org ~/test.pdf

A "p" is missing in the URL :wink:.

**Comment by wendallsan** [comment]
D'oh!  Thanks.  I thought I had copy-pasted the command so no idea how I missed it.  The command is clearly provided correctly in your instructions.
