### ISSUE TITLE
URLError: SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by deepak-ace12** [Kozea/WeasyPrint#632]
Hi,
I am trying to download a pdf file using weasyprint but getting an error "ERROR:weasypring: failed to load stylesheet URLError: SSL: CERTIFICATE_VERIFY_FAILED.
Don't know what's wrong with it. Please help.

**Comment by liZe** [comment]
Hi,

This message means that you're trying to download an HTTPS resource with the wrong certificate (it's the same as a crossed out lock for a browser).

If you want more help, I need more information about what you're trying to do (your command line and the whole stacktrace for example).

**Comment by liZe** [comment]
@deepak-ace12 did you find a solution?

**Comment by deepak-ace12** [comment]
yeah...it was gunicorn issue...

**Comment by deepak-ace12** [comment]
@liZe sorry for the late reply...

**Comment by liZe** [comment]
No problem :wink:.

**Comment by ddahan** [comment]
Hi @liZe 
I just installed Weasyprint, and I got the same problem trying to run weasyprint from Python, with external CSS from a CDN.

```
In [2]: HTML('http://localhost:8000/t/pzps7h').write_pdf('receipt.pdf')
ERROR 2018-10-10 07:38:24,402 weasyprint   -> Failed to load stylesheet at https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css : URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
```

What special configuration I need to do? (not seen in doc). Thanks.

**Comment by liZe** [comment]
@ddahan Downloading this file works for me. There's probably a problem in the SSL certificates chain, you can read many StackOverflow pages like [this one](https://stackoverflow.com/questions/41691327/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c).

If you can't find a solution, please open a new issue, it's better than adding comments to a closed issue :wink:.

**Comment by nkonin** [comment]
I have the same issue.

OS: MacOS Mojave 10.14.3
Python: 3.7.0
WeasyPrint: 44

Step to reproduce:
```bash
❯❯❯ weasyprint --version
WeasyPrint version 44
❯❯❯ weasyprint http://weasyprint.org /tmp/weasyprint-website.pdf

weasyprint.urls.URLFetchingError: URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>
```
At the same time `requests` library works just fine, so I think it's issue with WeasyPrint:
```bash
❯❯❯ python -c "import requests; print(requests.get('http://weasyprint.org'))"
<Response [200]>
```

Full traceback:
```shell
weasyprint http://weasyprint.org /tmp/weasyprint-website.pdf

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nkonin/Documents/projects/broker.nosync/broker_core/venv/lib/python3.7/site-packages/weasyprint/urls.py", line 276, in fetch
    result = url_fetcher(url)
  File "/Users/nkonin/Documents/projects/broker.nosync/broker_core/venv/lib/python3.7/site-packages/weasyprint/urls.py", line 240, in default_url_fetcher
    response = urlopen(Request(url, headers=HTTP_HEADERS), timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nkonin/Documents/projects/broker.nosync/broker_core/venv/bin/weasyprint", line 10, in <module>
    sys.exit(main())
  File "/Users/nkonin/Documents/projects/broker.nosync/broker_core/venv/lib/python3.7/site-packages/weasyprint/__main__.py", line 172, in main
    media_type=args.media_type)
  File "/Users/nkonin/Documents/projects/broker.nosync/broker_core/venv/lib/python3.7/site-packages/weasyprint/__init__.py", line 105, in __init__
    with result as (source_type, source, base_url, protocol_encoding):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/nkonin/Documents/projects/broker.nosync/broker_core/venv/lib/python3.7/site-packages/weasyprint/__init__.py", line 350, in _select_source
    with result as result:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/nkonin/Documents/projects/broker.nosync/broker_core/venv/lib/python3.7/site-packages/weasyprint/__init__.py", line 360, in _select_source
    with fetch(url_fetcher, url) as result:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/nkonin/Documents/projects/broker.nosync/broker_core/venv/lib/python3.7/site-packages/weasyprint/urls.py", line 278, in fetch
    raise URLFetchingError('%s: %s' % (type(exc).__name__, str(exc)))
weasyprint.urls.URLFetchingError: URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>
```

**Comment by liZe** [comment]
@nkonin Launching this command works for me. There's probably a problem in the SSL certificates chain, you can read many StackOverflow pages like [this one](https://stackoverflow.com/questions/41691327/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c).

If you can't find a solution, please open a new issue, it's better than adding comments to a closed issue :wink:.

**Comment by bastien34** [comment]
I recently faced this issue with an autosigned certificate which was added to firefox and chrome but not in the ca-certificate root directory. So the system couldn't access it. The solution was to add it in **/usr/local/share/ca-certificates/** and run **sudo update-ca-certificates**. It worked then perfectly !

**Comment by l-kotzur** [comment]
> I recently faced this issue with an autosigned certificate which was added to firefox and chrome but not in the ca-certificate root directory. So the system couldn't access it. The solution was to add it in **/usr/local/share/ca-certificates/** and run **sudo update-ca-certificates**. It worked then perfectly !

This helped. Further, I needed to [set the environment variable REQUESTS_CA_BUNDLE](https://stackoverflow.com/a/42982144/3253411) to tell requests to use the own certificate bundle: 
`export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt`
