### ISSUE TITLE
Problem installing on shared server

### ISSUE THREAD

**Issue by cjshaw1976** [Kozea/WeasyPrint#690]
Good Day, I am trying to install on a shared hosting server, in a virtual enviroment with python 3.5.6, using `pip install WeasyPrint`. I get the following error:

Collecting WeasyPrint
  Using cached https://files.pythonhosted.org/packages/a5/3c/a7021bea33ef7515901d77b11cb0d356171068055591e9d813962a0092d8/WeasyPrint-0.42.3-py3-none-any.whl
Collecting Pyphen>=0.8 (from WeasyPrint)
  Using cached https://files.pythonhosted.org/packages/15/82/08a3629dce8d1f3d91db843bb36d4d7db6b6269d5067259613a0d5c8a9db/Pyphen-0.9.5-py2.py3-none-any.whl
Collecting cairocffi>=0.5 (from WeasyPrint)
  Using cached https://files.pythonhosted.org/packages/62/be/ad4d422b6f38d99b09ad6d046ab725e8ccac5fefd9ca256ca35a80dbf3c6/cairocffi-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    pycparser.ply.__pycache__.lex.cpython-35: module references __file__
    pycparser.ply.__pycache__.lex.cpython-35: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-35: module references __file__
    pycparser.ply.__pycache__.yacc.cpython-35: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-35: module MAY be using inspect.stack
    pycparser.ply.__pycache__.ygen.cpython-35: module references __file__
    
    Installed /tmp/pip-install-spgahi4e/cairocffi/.eggs/pycparser-2.18-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-spgahi4e/cairocffi/setup.py", line 51, in <module>
        'test': ['pytest-runner', 'pytest-cov'],
      File "/home/dbworksc/virtualenv/platinumaccounting__html/3.5/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/opt/alt/python35/lib64/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/dbworksc/virtualenv/platinumaccounting__html/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/opt/alt/python35/lib64/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/home/dbworksc/virtualenv/platinumaccounting__html/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-install-spgahi4e/cairocffi/.eggs/cffi-1.11.5-py3.5-linux-x86_64.egg/cffi/setuptools_ext.py", line 204, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-install-spgahi4e/cairocffi/.eggs/cffi-1.11.5-py3.5-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-install-spgahi4e/cairocffi/.eggs/cffi-1.11.5-py3.5-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "cairocffi/ffi_build.py", line 26, in <module>
        ffi = FFI()
      File "/tmp/pip-install-spgahi4e/cairocffi/.eggs/cffi-1.11.5-py3.5-linux-x86_64.egg/cffi/api.py", line 46, in __init__
        import _cffi_backend as backend
    ImportError: /tmp/pip-install-spgahi4e/cairocffi/.eggs/cffi-1.11.5-py3.5-linux-x86_64.egg/_cffi_backend.cpython-35m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

**Comment by Tontyna** [comment]
The `/tmp` folder probably lacks exec premission. 
You should ask your system administrator to make it so (at least temporarily). 
Or you could try setting TMP (temporarily) to another folder...

**Comment by liZe** [comment]
@cjshaw1976 Did you try @Tontyna's solution?

**Comment by liZe** [comment]
@cjshaw1976 Feel free to reopen if there's something new.
