### ISSUE TITLE
Error while producing the PDF file (TypeError: 'NoneType' object is not iterable) in split_inline_boxchild_resume_at

### ISSUE THREAD

**Issue by fabiobatalha** [Kozea/WeasyPrint#712]
HTML File producing the error: [sample.zip](https://github.com/Kozea/WeasyPrint/files/2497187/sample.zip)

Installed libraries:

```
  - weasyprint [required: >=0.42.3, installed: 0.42.3]
    - cairocffi [required: >=0.5, installed: 0.9.0]
      - cffi [required: >=1.1.0, installed: 1.11.5]
        - pycparser [required: Any, installed: 2.19]
    - CairoSVG [required: >=1.0.20, installed: 2.2.1]
      - cairocffi [required: Any, installed: 0.9.0]
        - cffi [required: >=1.1.0, installed: 1.11.5]
          - pycparser [required: Any, installed: 2.19]
      - cssselect2 [required: Any, installed: 0.2.1]
        - tinycss2 [required: Any, installed: 0.6.1]
          - webencodings [required: >=0.4, installed: 0.5.1]
      - defusedxml [required: Any, installed: 0.5.0]
      - pillow [required: Any, installed: 5.3.0]
      - tinycss2 [required: Any, installed: 0.6.1]
        - webencodings [required: >=0.4, installed: 0.5.1]
    - cffi [required: >=0.6, installed: 1.11.5]
      - pycparser [required: Any, installed: 2.19]
    - cssselect2 [required: >=0.1, installed: 0.2.1]
      - tinycss2 [required: Any, installed: 0.6.1]
        - webencodings [required: >=0.4, installed: 0.5.1]
    - html5lib [required: >=0.999999999, installed: 1.0.1]
      - six [required: >=1.9, installed: 1.11.0]
      - webencodings [required: Any, installed: 0.5.1]
    - pdfrw [required: >=0.4, installed: 0.4]
    - Pyphen [required: >=0.8, installed: 0.9.5]
    - tinycss2 [required: >=0.5, installed: 0.6.1]
      - webencodings [required: >=0.4, installed: 0.5.1]

```

Error message:

```
Traceback (most recent call last):
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/bin/converter", line 11, in <module>
    load_entry_point('converter', 'console_scripts', 'converter')()
  File "/home/fabiobatalha/Work/converter/converter/console_script.py", line 133, in main
    run(args.source, args.from_xml, args.to, args.suffix, args.custom_style)
  File "/home/fabiobatalha/Work/converter/converter/console_script.py", line 49, in run
    custom_style=custom_style
  File "/home/fabiobatalha/Work/converter/converter/engine.py", line 82, in convert
    conv = AVAILABLE_CONVERTERS[from_xml][to]['converter'](source)
  File "/home/fabiobatalha/Work/converter/converter/converters.py", line 67, in eruditarticle2pdf
    result = html.write_pdf(stylesheets=css)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/__init__.py", line 182, in write_pdf
    font_config=font_config).write_pdf(
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/__init__.py", line 143, in render
    font_config)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/document.py", line 326, in _render
    [Page(p, enable_hinting) for p in page_boxes],
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/document.py", line 326, in <listcomp>
    [Page(p, enable_hinting) for p in page_boxes],
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/__init__.py", line 55, in layout_document
    context, root_box, html, cascaded_styles, computed_styles))
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/pages.py", line 601, in make_all_pages
    context, root_box, page_type, resume_at, page_number)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/pages.py", line 520, in make_page
    positioned_boxes, positioned_boxes, adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 83, in block_level_layout
    adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 111, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 643, in block_container_layout
    adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 83, in block_level_layout
    adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 111, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 643, in block_container_layout
    adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 83, in block_level_layout
    adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 111, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 643, in block_container_layout
    adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 83, in block_level_layout
    adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 111, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 643, in block_container_layout
    adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 83, in block_level_layout
    adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 111, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 515, in block_container_layout
    for line, resume_at in lines_iterator:
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/inlines.py", line 51, in iter_line_boxes
    device_size, absolute_boxes, fixed_boxes, first_letter_style)
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/inlines.py", line 108, in get_next_linebox
    waiting_floats, line_children=[])
  File "/home/fabiobatalha/.Envs/converter-h0W4VNBh/lib/python3.6/site-packages/weasyprint/layout/inlines.py", line 838, in split_inline_box
    child_resume_at)
TypeError: 'NoneType' object is not iterable
```

**Comment by fabiobatalha** [comment]
Problem figured out, it is happening due to bad HTML structure.

a paragraph inside another paragraph.

**Comment by Tontyna** [comment]
Invalid HTML shouldnt crash WeasyPrint!
And indeed: release candidate [v43rc1](https://github.com/Kozea/WeasyPrint/releases/tag/v43rc1) doesnt crash with your sample.

**Comment by fabiobatalha** [comment]
I did a more detailed evaluation, and the HTML file is ok, the issue is with one character "»" in one common string, if  I remove the character "»" or put some other characters after this character "»sss" Weasyprint do not break.

broken file:  [sample.zip](https://github.com/Kozea/WeasyPrint/files/2497319/sample.zip)

``` html
<div class="footnote" id="no23">
  <div class="label">[<a href="#relno23">23</a>]</div>
  <p>
    <div class="block-citation">
      <p>« On donnera le nom d’analyseur à ce qui permet de révéler la structure de l’institution, de la provoquer, de la forcer à parler »</p>
      <div class="attrib"><small>Lourau</small>, 1970</div>
    </div>
  </p>
</div>
```

working file put some "sss" after "»": [sample2.zip](https://github.com/Kozea/WeasyPrint/files/2497326/sample2.zip)

``` html
<div class="footnote" id="no23">
  <div class="label">[<a href="#relno23">23</a>]</div>
  <p>
    <div class="block-citation">
      <p>« On donnera le nom d’analyseur à ce qui permet de révéler la structure de l’institution, de la provoquer, de la forcer à parler »sss</p>
      <div class="attrib"><small>Lourau</small>, 1970</div>
    </div>
  </p>
</div>
```

**Comment by Tontyna** [comment]
I guess its the same (fixed) bug like in #585 

As I said: v43rc1 doesnt crash. And you can install the release candiate like so:

```
pip install weasyprint==43rc1
```
