### ISSUE TITLE
Navigator 500 error on local html file on Windows

### ISSUE THREAD

**Issue by pfctdayelise** [Kozea/WeasyPrint#744]
Hi,

Trying to open a local file (eg with a `file:///` address) using the Navigator produces a 500 error. 

This may be something you decide not to fix, however I found a simple workaround which might be useful to add to the documentation.

* Run a Python simple HTTP server from the directory where the html file is located. (`python2 -m SimpleHTTPServer` or `python3 -m http.server`) 
* This will run a server on 127.0.0.1:8000. Open this in a browser and navigate to the local html file
* Separately, run `python -m weasyprint.tools.navigator`
* This runs a server on 127.0.0.1:5000. Open this in a browser
* Copy the URL from the port on 8000, into the Navigator box.

It's a bit clumsy but it works :)

Here is the terminal output from the 500 error. Running on Ubuntu 18.04 on Windows WSL. Weasyprint version 43.

The URL I hit was `http://127.0.0.1:5000/view/file:///U:/ha.html` . `file:///U:/ha.html` works in Chrome on Windows. So it seems like the file:/// prefix is not being cleanly stripped.

```
(confluence2pdf) bjl@BJL-LAP:/mnt/c/Users/bjl/wsl/confluence2pdf$ python -m weasyprint.tools.navigator
Listening on http://127.0.0.1:5000/ ...
127.0.0.1 - - [29/Nov/2018 14:56:50] "GET / HTTP/1.1" 200 1280
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1474, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [Errno 2] No such file or directory: '/U:/ha.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/urls.py", line 276, in fetch
    result = url_fetcher(url)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/urls.py", line 240, in default_url_fetcher
    response = urlopen(Request(url, headers=HTTP_HEADERS), timeout=timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1452, in file_open
    return self.open_local_file(req)
  File "/usr/lib/python3.6/urllib/request.py", line 1491, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: '/U:/ha.html'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/tools/navigator.py", line 132, in app
    return make_response(render_template(url))
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/tools/navigator.py", line 58, in render_template
    html = HTML(url)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/__init__.py", line 104, in __init__
    with result as (source_type, source, base_url, protocol_encoding):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/__init__.py", line 349, in _select_source
    with result as result:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/__init__.py", line 359, in _select_source
    with fetch(url_fetcher, url) as result:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/urls.py", line 278, in fetch
    raise URLFetchingError('%s: %s' % (type(exc).__name__, str(exc)))
weasyprint.urls.URLFetchingError: URLError: <urlopen error [Errno 2] No such file or directory: '/U:/ha.html'>
```

**Comment by liZe** [comment]
Thanks for this bug report.

It seems to work correctly on Linux (and probably on macOS too), I think that there's a problem in the way file URLs are normalized and/or handled by the HTML class for Windows files.

Maybe @Tontyna can help :smile:.

**Comment by Tontyna** [comment]
@liZe - this is not a Windows bug. IMHO this isn't a bug at all.

@pfctdayelise: It looks like you try to open a file called `U:\ha.html` -- i.e. a Windows path, starting with a drive letter -- in an environment that has no idea of drive letters, and consequently when stripping the file-prefix it stops right before the first slash to retrieve an `/absolut/path/to/the.html`:

```
URLError: <urlopen error [Errno 2] No such file or directory: '/U:/ha.html'>
```

When I try to display the inexistent `file:///U:/ha.html` with Python & Navigator running in a Windows shell I get a **WinError**, the requested file starts with the drive letter, all further slashes are converted to (double) backslashes: 

```
URLError: <urlopen error [WinError 3] file not found: 'U:\\ha.html'>
```

I suppose you'll succeed with a local url of `file://U/ha.hml`

**Comment by pfctdayelise** [comment]
@Tontyna thanks for your reply.

 > I suppose you'll succeed with a local url of `file://U/ha.hml`

Unfortunately not:

```
bjl@BJL-LAP:/mnt/c/Users/bjl/wsl/confluence2pdf$ pipenv run python -m weasyprint.tools.navigator
Listening on http://127.0.0.1:5000/ ...
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1474, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [Errno 2] No such file or directory: '/ha.html'
```

However you gave me a hint to try `http://127.0.0.1:5000/view/file://U://ha.html` where I did finally manage to hit on an exciting new error :)

```
bjl@BJL-LAP:/mnt/c/Users/bjl/wsl/confluence2pdf$ pipenv run python -m weasyprint.tools.navigator
Listening on http://127.0.0.1:5000/ ...
Traceback (most recent call last):
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/urls.py", line 276, in fetch
    result = url_fetcher(url)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/urls.py", line 240, in default_url_fetcher
    response = urlopen(Request(url, headers=HTTP_HEADERS), timeout=timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1450, in file_open
    raise URLError("file:// scheme is supported only on localhost")
urllib.error.URLError: <urlopen error file:// scheme is supported only on localhost>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/tools/navigator.py", line 132, in app
    return make_response(render_template(url))
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/tools/navigator.py", line 58, in render_template
    html = HTML(url)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/__init__.py", line 104, in __init__
    with result as (source_type, source, base_url, protocol_encoding):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/__init__.py", line 349, in _select_source
    with result as result:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/__init__.py", line 359, in _select_source
    with fetch(url_fetcher, url) as result:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/urls.py", line 278, in fetch
    raise URLFetchingError('%s: %s' % (type(exc).__name__, str(exc)))
weasyprint.urls.URLFetchingError: URLError: <urlopen error file:// scheme is supported only on localhost>
127.0.0.1 - - [02/Jan/2019 12:33:29] "GET /view/file://U://ha.html HTTP/1.1" 500 59

```

**Comment by Tontyna** [comment]
@pfctdayelise looking at Python's urllib/request.py I see: It wants 3 slashes. Try `file:///U/ha.hml`

**Comment by pfctdayelise** [comment]
> 
> 
> @pfctdayelise looking at Python's urllib/request.py I see: It wants 3 slashes. Try `file:///U/ha.hml`

No luck, got a similar error with an errant leading slash:

Request `http://127.0.0.1:5000/view/file:///U/ha.html`

Console output 

```
bjl@BJL-LAP:/mnt/c/Users/bjl/wsl/confluence2pdf$ pipenv run python -m weasyprint.tools.navigator
Listening on http://127.0.0.1:5000/ ...
127.0.0.1 - - [03/Jan/2019 17:00:18] "GET / HTTP/1.1" 200 1280
127.0.0.1 - - [03/Jan/2019 17:00:18] "GET /favicon.ico HTTP/1.1" 404 18
127.0.0.1 - - [03/Jan/2019 17:01:04] "GET / HTTP/1.1" 200 1280
127.0.0.1 - - [03/Jan/2019 17:01:04] "GET /favicon.ico HTTP/1.1" 404 18
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1474, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [Errno 2] No such file or directory: '/U/ha.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/urls.py", line 276, in fetch
    result = url_fetcher(url)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/urls.py", line 240, in default_url_fetcher
    response = urlopen(Request(url, headers=HTTP_HEADERS), timeout=timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1452, in file_open
    return self.open_local_file(req)
  File "/usr/lib/python3.6/urllib/request.py", line 1491, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: '/U/ha.html'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/tools/navigator.py", line 132, in app
    return make_response(render_template(url))
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/tools/navigator.py", line 58, in render_template
    html = HTML(url)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/__init__.py", line 104, in __init__
    with result as (source_type, source, base_url, protocol_encoding):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/__init__.py", line 349, in _select_source
    with result as result:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/__init__.py", line 359, in _select_source
    with fetch(url_fetcher, url) as result:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/bjl/.local/share/virtualenvs/confluence2pdf-2p7HVg-X/lib/python3.6/site-packages/weasyprint/urls.py", line 278, in fetch
    raise URLFetchingError('%s: %s' % (type(exc).__name__, str(exc)))
weasyprint.urls.URLFetchingError: URLError: <urlopen error [Errno 2] No such file or directory: '/U/ha.html'>
127.0.0.1 - - [03/Jan/2019 17:01:09] "GET /view/file:///U/ha.html HTTP/1.1" 500 59
```

**Comment by pfctdayelise** [comment]
BTW I want to clarify, since I think I have confused myself and everyone else :) I am running weasyprint in WSL Ubuntu. So it will not be able to find any Windows path file. So @Tontyna is right, it's not really a bug.

I found I could get it to work by putting the file in the same dir where I am running weasyprint, then providing an absolute file path as a 'URL' like `file:////mnt/c/Users/USER/path/to/directory/ha.html`.

**Comment by Tontyna** [comment]
> ... Ubuntu. So it will not be able to find any Windows path file.

unless you mount your Windows drives.
