### ISSUE TITLE
Compatibility with pango 1.42

### ISSUE THREAD

**Issue by gassyfeve** [Kozea/WeasyPrint#745]
Error occured when upgrade pango to 1.42.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/weasyprint/__init__.py", line 375, in <module>
    from .css import preprocess_stylesheet  # noqa
  File "/usr/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 29, in <module>
    from . import computed_values
  File "/usr/lib/python2.7/site-packages/weasyprint/css/computed_values.py", line 16, in <module>
    from .. import text
  File "/usr/lib/python2.7/site-packages/weasyprint/text.py", line 244, in <module>
    'libpango-1.0.dylib')
  File "/usr/lib/python2.7/site-packages/weasyprint/text.py", line 238, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 798, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library 'libpango-1.0.so.0': /lib64/libpango-1.0.so.0: undefined symbol: g_log_structured_standard

**Comment by liZe** [comment]
@gassyfeve How did you solve your problem? (It may be useful to other users later!)
