### ISSUE TITLE
AttributeError: module 'xml.etree.ElementTree' has no attribute '_IterParseIterator'

### ISSUE THREAD

**Issue by StevenMapes** [Kozea/WeasyPrint#777]
This library appear to be broken on Ubuntu 18.04

Steps to recreate
1. Install dependencies from apt
3. Activate venv
4. Install from pip
5. run `weasyprint http://weasyprint.org ./weasyprint-website.pdf`

```
Traceback (most recent call last):
  File "/var/www/venv/tfn/bin/weasyprint", line 6, in <module>
    from weasyprint.__main__ import main
  File "/var/www/venv/tfn/lib/python3.6/site-packages/weasyprint/__init__.py", line 394, in <module>
    from .css import preprocess_stylesheet  # noqa
  File "/var/www/venv/tfn/lib/python3.6/site-packages/weasyprint/css/__init__.py", line 25, in <module>
    from . import computed_values
  File "/var/www/venv/tfn/lib/python3.6/site-packages/weasyprint/css/computed_values.py", line 21, in <module>
    from .utils import (
  File "/var/www/venv/tfn/lib/python3.6/site-packages/weasyprint/css/utils.py", line 20, in <module>
    from ..images import LinearGradient, RadialGradient
  File "/var/www/venv/tfn/lib/python3.6/site-packages/weasyprint/images.py", line 17, in <module>
    import cairosvg.parser
  File "/var/www/venv/tfn/lib/python3.6/site-packages/cairosvg/__init__.py", line 41, in <module>
    from . import surface  # noqa
  File "/var/www/venv/tfn/lib/python3.6/site-packages/cairosvg/surface.py", line 27, in <module>
    from .defs import (
  File "/var/www/venv/tfn/lib/python3.6/site-packages/cairosvg/defs.py", line 24, in <module>
    from .bounding_box import calculate_bounding_box, is_non_empty_bounding_box
  File "/var/www/venv/tfn/lib/python3.6/site-packages/cairosvg/bounding_box.py", line 28, in <module>
    from .parser import Tree
  File "/var/www/venv/tfn/lib/python3.6/site-packages/cairosvg/parser.py", line 28, in <module>
    from defusedxml import ElementTree
  File "/var/www/venv/tfn/lib/python3.6/site-packages/defusedxml/ElementTree.py", line 62, in <module>
    _XMLParser, _iterparse, _IterParseIterator, ParseError = _get_py3_cls()
  File "/var/www/venv/tfn/lib/python3.6/site-packages/defusedxml/ElementTree.py", line 56, in _get_py3_cls
    _IterParseIterator = pure_pymod._IterParseIterator
AttributeError: module 'xml.etree.ElementTree' has no attribute '_IterParseIterator'


```

**Comment by StevenMapes** [comment]
Issue due to conflict with other requirement using older version of some dependencies. Please ignore
