### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'height'

### ISSUE THREAD

**Issue by richiedunk** [Kozea/WeasyPrint#795]
I'm getting no logging output, and I'm struggling to unpick the error below or find any similar references online. Can anyone offer an explanation, please?

```
2019-02-09 14:37:22,143: Exception on /endpoint [POST]
Traceback (most recent call last):
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/username/dunknetwork/flask_app.py", line 190, in occassional_reporter1
    return (or_make_pdf(html, css), 200, headers)
  File "/home/username/dunknetwork/flask_app.py", line 116, in or_make_pdf
    return html.write_pdf(stylesheets=[css])
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/__init__.py", line 199, in write_pdf
    font_config=font_config).write_pdf(
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/__init__.py", line 160, in render
    font_config)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/document.py", line 361, in _render
    [Page(p, enable_hinting) for p in page_boxes],
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/document.py", line 361, in <listcomp>
    [Page(p, enable_hinting) for p in page_boxes],
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/__init__.py", line 126, in layout_document
    context, root_box, html, cascaded_styles, computed_styles, pages))
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/pages.py", line 788, in make_all_pages
    i, context, root_box, html, cascaded_styles, computed_styles)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/pages.py", line 726, in remake_page
    page_number, page_state)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/pages.py", line 554, in make_page
    positioned_boxes, positioned_boxes, adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 55, in block_level_layout
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 71, in block_level_layout_switch
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 125, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 495, in block_container_layout
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 55, in block_level_layout
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 71, in block_level_layout_switch
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 125, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 495, in block_container_layout
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 55, in block_level_layout
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 71, in block_level_layout_switch
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 125, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 495, in block_container_layout
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 55, in block_level_layout
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 71, in block_level_layout_switch
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 125, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 495, in block_container_layout
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 55, in block_level_layout
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 71, in block_level_layout_switch
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 125, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 495, in block_container_layout
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 55, in block_level_layout
    adjoining_margins)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/blocks.py", line 86, in block_level_layout_switch
    device_size, page_is_empty, absolute_boxes, fixed_boxes)
  File "/home/username/.virtualenvs/apps/lib/python3.6/site-packages/weasyprint/layout/flex.py", line 446, in flex_layout
    child.height = new_child.height
AttributeError: 'NoneType' object has no attribute 'height'
```

**Comment by SimonHurst** [comment]
What’s the url the file/page you’re trying to convert.

**Comment by richiedunk** [comment]
Through a process of elimination I'm having difficulty with the following section of a custom Flask template. Turns out that the error occurs when `text3` is too short. It may be when there is insufficient text to cover all of the three columns in the div's `column-count`?

HTML
```
    <!-- Bottom article -->
<div class="bottom-articles">
    <div class="article">
        <div class="article-3">
            <div class="photo-container-3">
                <div class="photo-caption-3">
                    <p>{{caption3}}</p>
                </div>
            </div>
            <div class="article-text-container-3">
                <h1 class="headline-3">
                    {{headline3}}
                </h1>
                <div class="article-text-3">
                    {{text3}}
                </div>
            </div>
        </div>
    </div>
</div>
```

CSS
```
.bottom-articles {
  margin-top: 8px;
  background-color: #ccc;
  padding: 10pt;
}

.headline-3 {
  width: 100%;
  margin: 0;
  padding: 4px 0;
  text-align: center;
}

.article-3 {
  display: flex;
}

.article-text-container-3{
    margin-top: 6px;
  width: 75%;
}

.article-text-3 {
  text-align: justify;
  column-count: 3;
  text-indent: 50px;
}

.article-text-3 > div:first-of-type {
  text-indent: 0;
  font-weight: bold;
}

.article-text-3 > div:first-of-type:first-letter {
  float: left;
  font-size: 4em;
  line-height: 60px;
  padding-top: 0px;
  padding-right: 5px;
  padding-left: 0px;
}

.article-text-3 div:last-of-type {
  font-weight: bold;
}

.photo-container-3 {
  position: relative;
  width: 25%;
  margin-right: 10px;
  background-image: url("{{file3name}}");
  background-size: cover;
    background-repeat: no-repeat;
    background-position: 50% 50%;
}

.photo-caption-3 {
  position: absolute;
  bottom: 0px;
  background-color: black;
  color: white;
  width: 100%;
  text-align: center;
  padding: 0;
  margin: 0;
  font-size: 80%;
}
```

**Comment by liZe** [comment]
I've tried to reproduce this issue, but I can't. @richiedunk Could you please provide an HTML example with placeholders replaced by real text?

**Comment by liZe** [comment]
@richiedunk Can I close this issue?
