### ISSUE TITLE
WeasyPrint fails to run after installation on MacOS Mojave

### ISSUE THREAD

**Issue by themindstorm** [Kozea/WeasyPrint#803]
I followed the [guide](https://weasyprint.readthedocs.io/en/latest/install.html#macos) for installation, and did not run into any errors.

However, when I type `weasyprint` in the terminal, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 6, in <module>
    from weasyprint.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/weasyprint/__init__.py", line 394, in <module>
    from .css import preprocess_stylesheet  # noqa
  File "/usr/local/lib/python3.7/site-packages/weasyprint/css/__init__.py", line 25, in <module>
    from . import computed_values
  File "/usr/local/lib/python3.7/site-packages/weasyprint/css/computed_values.py", line 21, in <module>
    from .utils import (
  File "/usr/local/lib/python3.7/site-packages/weasyprint/css/utils.py", line 20, in <module>
    from ..images import LinearGradient, RadialGradient
  File "/usr/local/lib/python3.7/site-packages/weasyprint/images.py", line 17, in <module>
    import cairosvg.parser
  File "/usr/local/lib/python3.7/site-packages/cairosvg/__init__.py", line 42, in <module>
    from . import surface  # noqa
  File "/usr/local/lib/python3.7/site-packages/cairosvg/surface.py", line 28, in <module>
    from .defs import (
  File "/usr/local/lib/python3.7/site-packages/cairosvg/defs.py", line 24, in <module>
    from .bounding_box import calculate_bounding_box, is_non_empty_bounding_box
  File "/usr/local/lib/python3.7/site-packages/cairosvg/bounding_box.py", line 26, in <module>
    from .features import match_features
  File "/usr/local/lib/python3.7/site-packages/cairosvg/features.py", line 25, in <module>
    LOCALE = locale.getdefaultlocale()[0] or ''
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 568, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 495, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

```

The same happens when do `import weasyprint` in Python3.

**Comment by liZe** [comment]
Hello,

Thanks for taking the time to report this issue.

The problem is not related to WeasyPrint, but to the way Python is installed on your system. You can check #219 and [this StackOverflow article](https://stackoverflow.com/questions/1830394/python-locale-strange-error-whats-going-on-here-exactly) to understand what's going on and how to solve it.

**Comment by themindstorm** [comment]
Sorry, I should have done more research. If anyone is having the same problem, this might help:

1. Open `~/.bash_profile` with a text-editor
2. Add the following lines:

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

Type `source ~/.bash_profile` into the terminal (and restart it).

This worked for me. (found [here](https://stackoverflow.com/a/44630711/8677167))

**Comment by liZe** [comment]
> Sorry, I should have done more research.

No problem!
