### ISSUE TITLE
GLib-GObject-CRITICAL **: 17:29:26.379: g_object_ref: assertion 'old_val > 0' failed

### ISSUE THREAD

**Issue by hybridpicker** [Kozea/WeasyPrint#829]
Integrated Weasy Print in my Django-App 3 months ago. Today I just get this Error.
Really confused because I didn't change any of my code

Exception happened during processing of request from ('127.0.0.1', 59008)
Traceback (most recent call last):
  File "/Users/schoensgibl/anaconda3/envs/bl/lib/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/schoensgibl/anaconda3/envs/bl/lib/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/schoensgibl/anaconda3/envs/bl/lib/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/Users/schoensgibl/anaconda3/envs/bl/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/Users/schoensgibl/anaconda3/envs/bl/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/Users/schoensgibl/anaconda3/envs/bl/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

(process:39997): GLib-GObject-CRITICAL **: 17:29:26.379: g_object_ref: assertion 'old_val > 0' failed
Bus error: 10

Hope for some hints

**Comment by liZe** [comment]
Hello!

I've seen your report, but there's no line concerning WeasyPrint in the stacktrace. Why do you think that your problem is related to WeasyPrint?

**Comment by loganthomas** [comment]
@hybridpicker Did you find a solution to this? I am seeing a similar error message with one of my processes.

**Comment by hybridpicker** [comment]
> @hybridpicker Did you find a solution to this? I am seeing a similar error message with one of my processes.

I've checked the python versions on my system. It works till python 3.6.8 That problem occurs with upgrading to phyton 3.7
